[package]
edition      = "2024"
license-file = "../LICENSE.polyform"
name         = "bd-event-buffer"
publish      = false
version      = "1.0.0"

[dependencies]
bd-client-common.path  = "../bd-client-common"
bd-completion.path     = "../bd-completion"
bd-log-primitives.path = "../bd-log-primitives"
bd-proto.path          = "../bd-proto"
tokio.workspace        = true

[dev-dependencies]
proptest.workspace = true
