[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-runtime-config"
publish      = false
version      = "1.0.0"

[dependencies]
async-trait.workspace = true
bd-server-stats.path  = "../bd-server-stats"
log.workspace         = true
notify.workspace      = true
parking_lot.workspace = true
prometheus.workspace  = true
rand.workspace        = true
serde.workspace       = true
serde_yaml.workspace  = true
thiserror.workspace   = true
tokio.workspace       = true

[dev-dependencies]
bd-test-helpers   = { path = "../bd-test-helpers", default-features = false }
ctor.workspace    = true
tempdir.workspace = true
