[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-runtime-config"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
async-trait.workspace       = true
bd-server-stats.path        = "../bd-server-stats"
bd-workspace-hack.workspace = true
log.workspace               = true
notify.workspace            = true
parking_lot.workspace       = true
prometheus.workspace        = true
rand.workspace              = true
serde.workspace             = true
serde_yaml.workspace        = true
thiserror.workspace         = true
tokio.workspace             = true

[dev-dependencies]
bd-test-helpers    = { path = "../bd-test-helpers", default-features = false }
ctor.workspace     = true
tempfile.workspace = true
