[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-completion"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
log.workspace    = true
thiserror.workspace = true
tokio.workspace  = true
