load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("//tools/lint:linters.bzl", "rust_binary", "rust_library")
load("//tools/rust:tests.bzl", "rust_library_with_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "src/flatbuffers/buffer_log_generated.h",
    "src/flatbuffers/common_generated.h",
])

rust_binary(
    name = "generate-protos",
    data = ["@@+http_archive+shared_core_flatbuffers//:flatc"],
    env = {
        "FLATC": "$(rootpath @@+http_archive+shared_core_flatbuffers//:flatc)",
    },
    srcs = [
        "src/bin/generate_protos.rs",
        "src/proto_config.rs",
    ],
    crate_features = ["codegen"],
    crate_name = "generate_protos",
    crate_root = "src/bin/generate_protos.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "@crates//:flatc-rust",
        "@crates//:protobuf-codegen",
    ],
)

rust_library_with_test(
    name = "bd-proto",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "bd_proto",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True),
)

rust_library(
    name = "bd-proto-with-source-info",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    aliases = aliases(),
    crate_features = ["with-source-info"],
    crate_name = "bd_proto",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True),
)
