[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-proto"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-pgv.path                 = "../bd-pgv"
bd-workspace-hack.workspace = true
bytes.workspace             = true
flatbuffers.workspace       = true
protobuf.workspace          = true

[dev-dependencies]
matches.workspace = true

[build-dependencies]
flatc-rust.workspace       = true
protobuf-codegen.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
