[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-profile"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
axum.workspace              = true
bd-workspace-hack.workspace = true
tikv-jemalloc-ctl.workspace = true
