[graph]
all-features        = false
exclude             = ["bd-workspace-hack"]
no-default-features = false
targets             = []

[output]
feature-depth = 1

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "NCSA",
  "OpenSSL",
  "Unicode-3.0",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
crate         = "ring"
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
crate         = "bd-workspace-hack"
expression    = "PolyForm-Noncommercial-1.0.0"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore     = true
registries = []
