// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 36.0
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/workflows/v1/api.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FetchCapturedSessionsRequest {
    // message fields
    ///  The action ID whose captured sessions should be returned. If empty, returns
    ///  captured sessions across all actions.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.action_id)
    pub action_id: ::std::string::String,
    ///  The start time and end time of the captured sessions.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.time_range)
    pub time_range: ::protobuf::MessageField<super::common::TimeRange>,
    ///  Field filters to apply to the captured session search. This supports filtering sessions based on certain indexed fields
    ///  recorded alongside the captured session. Reach out to the bitdrift team to index additional fields.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.or_filter)
    pub or_filter: ::std::vec::Vec<super::time_series::AndFilter>,
    ///  The page number and the number of items per page. The server will use this
    ///  to paginate the results. Defaults to 1 when not set.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.page)
    pub page: ::std::option::Option<u64>,
    ///  The number of items to return per page. Defaults to 100 when not set.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.per_page)
    pub per_page: ::std::option::Option<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FetchCapturedSessionsRequest {
    fn default() -> &'a FetchCapturedSessionsRequest {
        <FetchCapturedSessionsRequest as ::protobuf::Message>::default_instance()
    }
}

impl FetchCapturedSessionsRequest {
    pub fn new() -> FetchCapturedSessionsRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "action_id",
            |m: &FetchCapturedSessionsRequest| { &m.action_id },
            |m: &mut FetchCapturedSessionsRequest| { &mut m.action_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::common::TimeRange>(
            "time_range",
            |m: &FetchCapturedSessionsRequest| { &m.time_range },
            |m: &mut FetchCapturedSessionsRequest| { &mut m.time_range },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "or_filter",
            |m: &FetchCapturedSessionsRequest| { &m.or_filter },
            |m: &mut FetchCapturedSessionsRequest| { &mut m.or_filter },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "page",
            |m: &FetchCapturedSessionsRequest| { &m.page },
            |m: &mut FetchCapturedSessionsRequest| { &mut m.page },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "per_page",
            |m: &FetchCapturedSessionsRequest| { &m.per_page },
            |m: &mut FetchCapturedSessionsRequest| { &mut m.per_page },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FetchCapturedSessionsRequest>(
            "FetchCapturedSessionsRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FetchCapturedSessionsRequest {
    const NAME: &'static str = "FetchCapturedSessionsRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.action_id = is.read_string()?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.time_range)?;
                },
                58 => {
                    self.or_filter.push(is.read_message()?);
                },
                40 => {
                    self.page = ::std::option::Option::Some(is.read_uint64()?);
                },
                48 => {
                    self.per_page = ::std::option::Option::Some(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.action_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.action_id);
        }
        if let Some(v) = self.time_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.or_filter {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.page {
            my_size += ::protobuf::rt::uint64_size(5, v);
        }
        if let Some(v) = self.per_page {
            my_size += ::protobuf::rt::uint64_size(6, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.action_id.is_empty() {
            os.write_string(1, &self.action_id)?;
        }
        if let Some(v) = self.time_range.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        for v in &self.or_filter {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        };
        if let Some(v) = self.page {
            os.write_uint64(5, v)?;
        }
        if let Some(v) = self.per_page {
            os.write_uint64(6, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FetchCapturedSessionsRequest {
        FetchCapturedSessionsRequest::new()
    }

    fn clear(&mut self) {
        self.action_id.clear();
        self.time_range.clear();
        self.or_filter.clear();
        self.page = ::std::option::Option::None;
        self.per_page = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FetchCapturedSessionsRequest {
        static instance: FetchCapturedSessionsRequest = FetchCapturedSessionsRequest {
            action_id: ::std::string::String::new(),
            time_range: ::protobuf::MessageField::none(),
            or_filter: ::std::vec::Vec::new(),
            page: ::std::option::Option::None,
            per_page: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FetchCapturedSessionsRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FetchCapturedSessionsRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FetchCapturedSessionsRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FetchCapturedSessionsRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FetchCapturedSessionsResponse {
    // message fields
    ///  The captured sessions that matched the request.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsResponse.captured_sessions)
    pub captured_sessions: ::std::vec::Vec<super::captured_sessions::CapturedSession>,
    ///  The total number of matching sessions before pagination, subject to
    ///  service limits.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsResponse.full_count)
    pub full_count: u32,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FetchCapturedSessionsResponse {
    fn default() -> &'a FetchCapturedSessionsResponse {
        <FetchCapturedSessionsResponse as ::protobuf::Message>::default_instance()
    }
}

impl FetchCapturedSessionsResponse {
    pub fn new() -> FetchCapturedSessionsResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "captured_sessions",
            |m: &FetchCapturedSessionsResponse| { &m.captured_sessions },
            |m: &mut FetchCapturedSessionsResponse| { &mut m.captured_sessions },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "full_count",
            |m: &FetchCapturedSessionsResponse| { &m.full_count },
            |m: &mut FetchCapturedSessionsResponse| { &mut m.full_count },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FetchCapturedSessionsResponse>(
            "FetchCapturedSessionsResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FetchCapturedSessionsResponse {
    const NAME: &'static str = "FetchCapturedSessionsResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                18 => {
                    self.captured_sessions.push(is.read_message()?);
                },
                24 => {
                    self.full_count = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.captured_sessions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.full_count != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.full_count);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.captured_sessions {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.full_count != 0 {
            os.write_uint32(3, self.full_count)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FetchCapturedSessionsResponse {
        FetchCapturedSessionsResponse::new()
    }

    fn clear(&mut self) {
        self.captured_sessions.clear();
        self.full_count = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FetchCapturedSessionsResponse {
        static instance: FetchCapturedSessionsResponse = FetchCapturedSessionsResponse {
            captured_sessions: ::std::vec::Vec::new(),
            full_count: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FetchCapturedSessionsResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FetchCapturedSessionsResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FetchCapturedSessionsResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FetchCapturedSessionsResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FetchCapturedSessionsByDeviceIdRequest {
    // message fields
    ///  The UUID of the device whose sessions are requested.
    // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.device_id)
    pub device_id: ::std::string::String,
    // message oneof groups
    pub query_type: ::std::option::Option<fetch_captured_sessions_by_device_id_request::Query_type>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FetchCapturedSessionsByDeviceIdRequest {
    fn default() -> &'a FetchCapturedSessionsByDeviceIdRequest {
        <FetchCapturedSessionsByDeviceIdRequest as ::protobuf::Message>::default_instance()
    }
}

impl FetchCapturedSessionsByDeviceIdRequest {
    pub fn new() -> FetchCapturedSessionsByDeviceIdRequest {
        ::std::default::Default::default()
    }

    // .bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery proximity_query = 2;

    pub fn proximity_query(&self) -> &fetch_captured_sessions_by_device_id_request::ProximityQuery {
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(ref v)) => v,
            _ => <fetch_captured_sessions_by_device_id_request::ProximityQuery as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_proximity_query(&mut self) {
        self.query_type = ::std::option::Option::None;
    }

    pub fn has_proximity_query(&self) -> bool {
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_proximity_query(&mut self, v: fetch_captured_sessions_by_device_id_request::ProximityQuery) {
        self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(v))
    }

    // Mutable pointer to the field.
    pub fn mut_proximity_query(&mut self) -> &mut fetch_captured_sessions_by_device_id_request::ProximityQuery {
        if let ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(_)) = self.query_type {
        } else {
            self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(fetch_captured_sessions_by_device_id_request::ProximityQuery::new()));
        }
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_proximity_query(&mut self) -> fetch_captured_sessions_by_device_id_request::ProximityQuery {
        if self.has_proximity_query() {
            match self.query_type.take() {
                ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(v)) => v,
                _ => panic!(),
            }
        } else {
            fetch_captured_sessions_by_device_id_request::ProximityQuery::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_id",
            |m: &FetchCapturedSessionsByDeviceIdRequest| { &m.device_id },
            |m: &mut FetchCapturedSessionsByDeviceIdRequest| { &mut m.device_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, fetch_captured_sessions_by_device_id_request::ProximityQuery>(
            "proximity_query",
            FetchCapturedSessionsByDeviceIdRequest::has_proximity_query,
            FetchCapturedSessionsByDeviceIdRequest::proximity_query,
            FetchCapturedSessionsByDeviceIdRequest::mut_proximity_query,
            FetchCapturedSessionsByDeviceIdRequest::set_proximity_query,
        ));
        oneofs.push(fetch_captured_sessions_by_device_id_request::Query_type::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FetchCapturedSessionsByDeviceIdRequest>(
            "FetchCapturedSessionsByDeviceIdRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FetchCapturedSessionsByDeviceIdRequest {
    const NAME: &'static str = "FetchCapturedSessionsByDeviceIdRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.device_id = is.read_string()?;
                },
                18 => {
                    self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.device_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.device_id);
        }
        if let ::std::option::Option::Some(ref v) = self.query_type {
            match v {
                &fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.device_id.is_empty() {
            os.write_string(1, &self.device_id)?;
        }
        if let ::std::option::Option::Some(ref v) = self.query_type {
            match v {
                &fetch_captured_sessions_by_device_id_request::Query_type::ProximityQuery(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FetchCapturedSessionsByDeviceIdRequest {
        FetchCapturedSessionsByDeviceIdRequest::new()
    }

    fn clear(&mut self) {
        self.device_id.clear();
        self.query_type = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FetchCapturedSessionsByDeviceIdRequest {
        static instance: FetchCapturedSessionsByDeviceIdRequest = FetchCapturedSessionsByDeviceIdRequest {
            device_id: ::std::string::String::new(),
            query_type: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FetchCapturedSessionsByDeviceIdRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FetchCapturedSessionsByDeviceIdRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FetchCapturedSessionsByDeviceIdRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FetchCapturedSessionsByDeviceIdRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `FetchCapturedSessionsByDeviceIdRequest`
pub mod fetch_captured_sessions_by_device_id_request {

    #[derive(Clone,PartialEq,Debug)]
    // @@protoc_insertion_point(oneof:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.query_type)
    pub enum Query_type {
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.proximity_query)
        ProximityQuery(ProximityQuery),
    }

    impl ::protobuf::Oneof for Query_type {
    }

    impl ::protobuf::OneofFull for Query_type {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::FetchCapturedSessionsByDeviceIdRequest as ::protobuf::MessageFull>::descriptor().oneof_by_name("query_type").unwrap()).clone()
        }
    }

    impl Query_type {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Query_type>("query_type")
        }
    }
    // @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ProximityQuery {
        // message fields
        ///  The approximate first-seen time of the target session. The service searches within 30 days
        ///  before and after this time to locate the target session for the device.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery.proximity_time)
        pub proximity_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
        ///  The target session ID. The target session is excluded from the results. If it cannot be
        ///  found for the device, the service returns no sessions.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery.proximity_session_id)
        pub proximity_session_id: ::std::string::String,
        ///  The maximum number of sessions to return before and after the target session. Defaults to
        ///  five sessions in each direction when unset.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery.window_size)
        pub window_size: ::std::option::Option<u32>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRequest.ProximityQuery.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ProximityQuery {
        fn default() -> &'a ProximityQuery {
            <ProximityQuery as ::protobuf::Message>::default_instance()
        }
    }

    impl ProximityQuery {
        pub fn new() -> ProximityQuery {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(3);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
                "proximity_time",
                |m: &ProximityQuery| { &m.proximity_time },
                |m: &mut ProximityQuery| { &mut m.proximity_time },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "proximity_session_id",
                |m: &ProximityQuery| { &m.proximity_session_id },
                |m: &mut ProximityQuery| { &mut m.proximity_session_id },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
                "window_size",
                |m: &ProximityQuery| { &m.window_size },
                |m: &mut ProximityQuery| { &mut m.window_size },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProximityQuery>(
                "FetchCapturedSessionsByDeviceIdRequest.ProximityQuery",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for ProximityQuery {
        const NAME: &'static str = "ProximityQuery";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.proximity_time)?;
                    },
                    18 => {
                        self.proximity_session_id = is.read_string()?;
                    },
                    24 => {
                        self.window_size = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.proximity_time.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if !self.proximity_session_id.is_empty() {
                my_size += ::protobuf::rt::string_size(2, &self.proximity_session_id);
            }
            if let Some(v) = self.window_size {
                my_size += ::protobuf::rt::uint32_size(3, v);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.proximity_time.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if !self.proximity_session_id.is_empty() {
                os.write_string(2, &self.proximity_session_id)?;
            }
            if let Some(v) = self.window_size {
                os.write_uint32(3, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ProximityQuery {
            ProximityQuery::new()
        }

        fn clear(&mut self) {
            self.proximity_time.clear();
            self.proximity_session_id.clear();
            self.window_size = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ProximityQuery {
            static instance: ProximityQuery = ProximityQuery {
                proximity_time: ::protobuf::MessageField::none(),
                proximity_session_id: ::std::string::String::new(),
                window_size: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for ProximityQuery {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("FetchCapturedSessionsByDeviceIdRequest.ProximityQuery").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for ProximityQuery {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for ProximityQuery {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

// @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FetchCapturedSessionsByDeviceIdResponse {
    // message oneof groups
    pub query_type: ::std::option::Option<fetch_captured_sessions_by_device_id_response::Query_type>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FetchCapturedSessionsByDeviceIdResponse {
    fn default() -> &'a FetchCapturedSessionsByDeviceIdResponse {
        <FetchCapturedSessionsByDeviceIdResponse as ::protobuf::Message>::default_instance()
    }
}

impl FetchCapturedSessionsByDeviceIdResponse {
    pub fn new() -> FetchCapturedSessionsByDeviceIdResponse {
        ::std::default::Default::default()
    }

    // .bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.ProximityQuery proximity_query = 1;

    pub fn proximity_query(&self) -> &fetch_captured_sessions_by_device_id_response::ProximityQuery {
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(ref v)) => v,
            _ => <fetch_captured_sessions_by_device_id_response::ProximityQuery as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_proximity_query(&mut self) {
        self.query_type = ::std::option::Option::None;
    }

    pub fn has_proximity_query(&self) -> bool {
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_proximity_query(&mut self, v: fetch_captured_sessions_by_device_id_response::ProximityQuery) {
        self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(v))
    }

    // Mutable pointer to the field.
    pub fn mut_proximity_query(&mut self) -> &mut fetch_captured_sessions_by_device_id_response::ProximityQuery {
        if let ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(_)) = self.query_type {
        } else {
            self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(fetch_captured_sessions_by_device_id_response::ProximityQuery::new()));
        }
        match self.query_type {
            ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_proximity_query(&mut self) -> fetch_captured_sessions_by_device_id_response::ProximityQuery {
        if self.has_proximity_query() {
            match self.query_type.take() {
                ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(v)) => v,
                _ => panic!(),
            }
        } else {
            fetch_captured_sessions_by_device_id_response::ProximityQuery::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, fetch_captured_sessions_by_device_id_response::ProximityQuery>(
            "proximity_query",
            FetchCapturedSessionsByDeviceIdResponse::has_proximity_query,
            FetchCapturedSessionsByDeviceIdResponse::proximity_query,
            FetchCapturedSessionsByDeviceIdResponse::mut_proximity_query,
            FetchCapturedSessionsByDeviceIdResponse::set_proximity_query,
        ));
        oneofs.push(fetch_captured_sessions_by_device_id_response::Query_type::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FetchCapturedSessionsByDeviceIdResponse>(
            "FetchCapturedSessionsByDeviceIdResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FetchCapturedSessionsByDeviceIdResponse {
    const NAME: &'static str = "FetchCapturedSessionsByDeviceIdResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.query_type = ::std::option::Option::Some(fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.query_type {
            match v {
                &fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.query_type {
            match v {
                &fetch_captured_sessions_by_device_id_response::Query_type::ProximityQuery(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FetchCapturedSessionsByDeviceIdResponse {
        FetchCapturedSessionsByDeviceIdResponse::new()
    }

    fn clear(&mut self) {
        self.query_type = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FetchCapturedSessionsByDeviceIdResponse {
        static instance: FetchCapturedSessionsByDeviceIdResponse = FetchCapturedSessionsByDeviceIdResponse {
            query_type: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FetchCapturedSessionsByDeviceIdResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FetchCapturedSessionsByDeviceIdResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FetchCapturedSessionsByDeviceIdResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FetchCapturedSessionsByDeviceIdResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `FetchCapturedSessionsByDeviceIdResponse`
pub mod fetch_captured_sessions_by_device_id_response {

    #[derive(Clone,PartialEq,Debug)]
    // @@protoc_insertion_point(oneof:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.query_type)
    pub enum Query_type {
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.proximity_query)
        ProximityQuery(ProximityQuery),
    }

    impl ::protobuf::Oneof for Query_type {
    }

    impl ::protobuf::OneofFull for Query_type {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::FetchCapturedSessionsByDeviceIdResponse as ::protobuf::MessageFull>::descriptor().oneof_by_name("query_type").unwrap()).clone()
        }
    }

    impl Query_type {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Query_type>("query_type")
        }
    }
    // @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct DeviceIdSession {
        // message fields
        ///  The captured session ID.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession.session_id)
        pub session_id: ::std::string::String,
        ///  The time when the session was first observed.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession.first_seen)
        pub first_seen: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a DeviceIdSession {
        fn default() -> &'a DeviceIdSession {
            <DeviceIdSession as ::protobuf::Message>::default_instance()
        }
    }

    impl DeviceIdSession {
        pub fn new() -> DeviceIdSession {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "session_id",
                |m: &DeviceIdSession| { &m.session_id },
                |m: &mut DeviceIdSession| { &mut m.session_id },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
                "first_seen",
                |m: &DeviceIdSession| { &m.first_seen },
                |m: &mut DeviceIdSession| { &mut m.first_seen },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DeviceIdSession>(
                "FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for DeviceIdSession {
        const NAME: &'static str = "DeviceIdSession";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.session_id = is.read_string()?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.first_seen)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.session_id.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.session_id);
            }
            if let Some(v) = self.first_seen.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.session_id.is_empty() {
                os.write_string(1, &self.session_id)?;
            }
            if let Some(v) = self.first_seen.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> DeviceIdSession {
            DeviceIdSession::new()
        }

        fn clear(&mut self) {
            self.session_id.clear();
            self.first_seen.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static DeviceIdSession {
            static instance: DeviceIdSession = DeviceIdSession {
                session_id: ::std::string::String::new(),
                first_seen: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for DeviceIdSession {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("FetchCapturedSessionsByDeviceIdResponse.DeviceIdSession").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for DeviceIdSession {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for DeviceIdSession {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    // @@protoc_insertion_point(message:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.ProximityQuery)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ProximityQuery {
        // message fields
        ///  Sessions observed before the target session.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.ProximityQuery.before_sessions)
        pub before_sessions: ::std::vec::Vec<DeviceIdSession>,
        ///  Sessions observed after the target session.
        // @@protoc_insertion_point(field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.ProximityQuery.after_sessions)
        pub after_sessions: ::std::vec::Vec<DeviceIdSession>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.ProximityQuery.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ProximityQuery {
        fn default() -> &'a ProximityQuery {
            <ProximityQuery as ::protobuf::Message>::default_instance()
        }
    }

    impl ProximityQuery {
        pub fn new() -> ProximityQuery {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "before_sessions",
                |m: &ProximityQuery| { &m.before_sessions },
                |m: &mut ProximityQuery| { &mut m.before_sessions },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "after_sessions",
                |m: &ProximityQuery| { &m.after_sessions },
                |m: &mut ProximityQuery| { &mut m.after_sessions },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProximityQuery>(
                "FetchCapturedSessionsByDeviceIdResponse.ProximityQuery",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for ProximityQuery {
        const NAME: &'static str = "ProximityQuery";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.before_sessions.push(is.read_message()?);
                    },
                    18 => {
                        self.after_sessions.push(is.read_message()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            for value in &self.before_sessions {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            for value in &self.after_sessions {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            for v in &self.before_sessions {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            };
            for v in &self.after_sessions {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            };
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ProximityQuery {
            ProximityQuery::new()
        }

        fn clear(&mut self) {
            self.before_sessions.clear();
            self.after_sessions.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ProximityQuery {
            static instance: ProximityQuery = ProximityQuery {
                before_sessions: ::std::vec::Vec::new(),
                after_sessions: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for ProximityQuery {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("FetchCapturedSessionsByDeviceIdResponse.ProximityQuery").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for ProximityQuery {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for ProximityQuery {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n,bitdrift/public/unary/workflows/v1/api.proto\x12\"bitdrift.public.una\
    ry.workflows.v1\x1a5bitdrift/public/shared/workflows/v1/time_series.prot\
    o\x1a4bitdrift/public/unary/charts/v1/chart_metadata.proto\x1a,bitdrift/\
    public/unary/common/v1/common.proto\x1a:bitdrift/public/unary/workflows/\
    v1/captured_sessions.proto\x1a1bitdrift/public/unary/workflows/v1/workfl\
    ow.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate\
    .proto\"\xc0\x02\n\x1cFetchCapturedSessionsRequest\x12$\n\taction_id\x18\
    \x01\x20\x01(\tR\x08actionIdB\x07\xfaB\x04r\x02\x18d\x12I\n\ntime_range\
    \x18\x08\x20\x01(\x0b2*.bitdrift.public.unary.common.v1.TimeRangeR\ttime\
    Range\x12U\n\tor_filter\x18\x07\x20\x03(\x0b2..bitdrift.public.shared.wo\
    rkflows.v1.AndFilterR\x08orFilterB\x08\xfaB\x05\x92\x01\x02\x10\n\x12\
    \x17\n\x04page\x18\x05\x20\x01(\x04H\0R\x04page\x88\x01\x01\x12)\n\x08pe\
    r_page\x18\x06\x20\x01(\x04H\x01R\x07perPageB\t\xfaB\x062\x04\x18d(\x01\
    \x88\x01\x01B\x07\n\x05_pageB\x0b\n\t_per_page\"\xa0\x01\n\x1dFetchCaptu\
    redSessionsResponse\x12`\n\x11captured_sessions\x18\x02\x20\x03(\x0b23.b\
    itdrift.public.unary.workflows.v1.CapturedSessionR\x10capturedSessions\
    \x12\x1d\n\nfull_count\x18\x03\x20\x01(\rR\tfullCount\"\xbe\x03\n&FetchC\
    apturedSessionsByDeviceIdRequest\x12'\n\tdevice_id\x18\x01\x20\x01(\tR\
    \x08deviceIdB\n\xfaB\x07r\x05\x18$\xb0\x01\x01\x12\x84\x01\n\x0fproximit\
    y_query\x18\x02\x20\x01(\x0b2Y.bitdrift.public.unary.workflows.v1.FetchC\
    apturedSessionsByDeviceIdRequest.ProximityQueryH\0R\x0eproximityQuery\
    \x1a\xd0\x01\n\x0eProximityQuery\x12K\n\x0eproximity_time\x18\x01\x20\
    \x01(\x0b2\x1a.google.protobuf.TimestampR\rproximityTimeB\x08\xfaB\x05\
    \x8a\x01\x02\x10\x01\x12;\n\x14proximity_session_id\x18\x02\x20\x01(\tR\
    \x12proximitySessionIdB\t\xfaB\x06r\x04\x10\x01\x18d\x12$\n\x0bwindow_si\
    ze\x18\x03\x20\x01(\rH\0R\nwindowSize\x88\x01\x01B\x0e\n\x0c_window_size\
    B\x11\n\nquery_type\x12\x03\xf8B\x01\"\xe3\x04\n'FetchCapturedSessionsBy\
    DeviceIdResponse\x12\x85\x01\n\x0fproximity_query\x18\x01\x20\x01(\x0b2Z\
    .bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDeviceIdRespo\
    nse.ProximityQueryH\0R\x0eproximityQuery\x1a~\n\x0fDeviceIdSession\x12&\
    \n\nsession_id\x18\x01\x20\x01(\tR\tsessionIdB\x07\xfaB\x04r\x02\x10\x01\
    \x12C\n\nfirst_seen\x18\x02\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\
    \tfirstSeenB\x08\xfaB\x05\x8a\x01\x02\x10\x01\x1a\x9c\x02\n\x0eProximity\
    Query\x12\x84\x01\n\x0fbefore_sessions\x18\x01\x20\x03(\x0b2[.bitdrift.p\
    ublic.unary.workflows.v1.FetchCapturedSessionsByDeviceIdResponse.DeviceI\
    dSessionR\x0ebeforeSessions\x12\x82\x01\n\x0eafter_sessions\x18\x02\x20\
    \x03(\x0b2[.bitdrift.public.unary.workflows.v1.FetchCapturedSessionsByDe\
    viceIdResponse.DeviceIdSessionR\rafterSessionsB\x11\n\nquery_type\x12\
    \x03\xf8B\x012\x96\r\n\x0fWorkflowService\x12~\n\x0bGetWorkflow\x126.bit\
    drift.public.unary.workflows.v1.GetWorkflowRequest\x1a7.bitdrift.public.\
    unary.workflows.v1.GetWorkflowResponse\x12\x84\x01\n\rListWorkflows\x128\
    .bitdrift.public.unary.workflows.v1.ListWorkflowsRequest\x1a9.bitdrift.p\
    ublic.unary.workflows.v1.ListWorkflowsResponse\x12\x87\x01\n\x0eCreateWo\
    rkflow\x129.bitdrift.public.unary.workflows.v1.CreateWorkflowRequest\x1a\
    :.bitdrift.public.unary.workflows.v1.CreateWorkflowResponse\x12\x87\x01\
    \n\x0eUpdateWorkflow\x129.bitdrift.public.unary.workflows.v1.UpdateWorkf\
    lowRequest\x1a:.bitdrift.public.unary.workflows.v1.UpdateWorkflowRespons\
    e\x12\x87\x01\n\x0eRenameWorkflow\x129.bitdrift.public.unary.workflows.v\
    1.RenameWorkflowRequest\x1a:.bitdrift.public.unary.workflows.v1.RenameWo\
    rkflowResponse\x12\x93\x01\n\x12UpsertWorkflowTags\x12=.bitdrift.public.\
    unary.workflows.v1.UpsertWorkflowTagsRequest\x1a>.bitdrift.public.unary.\
    workflows.v1.UpsertWorkflowTagsResponse\x12\x87\x01\n\x0eDeleteWorkflow\
    \x129.bitdrift.public.unary.workflows.v1.DeleteWorkflowRequest\x1a:.bitd\
    rift.public.unary.workflows.v1.DeleteWorkflowResponse\x12\x87\x01\n\x0eD\
    eployWorkflow\x129.bitdrift.public.unary.workflows.v1.DeployWorkflowRequ\
    est\x1a:.bitdrift.public.unary.workflows.v1.DeployWorkflowResponse\x12\
    \x81\x01\n\x0cStopWorkflow\x127.bitdrift.public.unary.workflows.v1.StopW\
    orkflowRequest\x1a8.bitdrift.public.unary.workflows.v1.StopWorkflowRespo\
    nse\x12u\n\x08ListTags\x123.bitdrift.public.unary.workflows.v1.ListTagsR\
    equest\x1a4.bitdrift.public.unary.workflows.v1.ListTagsResponse\x12\x8d\
    \x01\n\x10FavoriteWorkflow\x12;.bitdrift.public.unary.workflows.v1.Favor\
    iteWorkflowRequest\x1a<.bitdrift.public.unary.workflows.v1.FavoriteWorkf\
    lowResponse\x12\xa8\x01\n\x1bUpsertWorkflowChartMetadata\x12C.bitdrift.p\
    ublic.unary.charts.v1.UpsertWorkflowChartMetadataRequest\x1aD.bitdrift.p\
    ublic.unary.charts.v1.UpsertWorkflowChartMetadataResponse2\xf1\x02\n\x13\
    WorkflowDataService\x12\x9c\x01\n\x15FetchCapturedSessions\x12@.bitdrift\
    .public.unary.workflows.v1.FetchCapturedSessionsRequest\x1aA.bitdrift.pu\
    blic.unary.workflows.v1.FetchCapturedSessionsResponse\x12\xba\x01\n\x1fF\
    etchCapturedSessionsByDeviceId\x12J.bitdrift.public.unary.workflows.v1.F\
    etchCapturedSessionsByDeviceIdRequest\x1aK.bitdrift.public.unary.workflo\
    ws.v1.FetchCapturedSessionsByDeviceIdResponseJ\xcf0\n\x07\x12\x05\x06\0\
    \xa8\x01\x01\n\xb8\x02\n\x01\x0c\x12\x03\x06\0\x12\x1a\xad\x02\x20api\
    \x20-\x20bitdrift's\x20client/server\x20API\x20definitions\n\x20Copyrigh\
    t\x20Bitdrift,\x20Inc.\x20All\x20rights\x20reserved.\n\n\x20Use\x20of\
    \x20this\x20source\x20code\x20and\x20APIs\x20are\x20governed\x20by\x20a\
    \x20source\x20available\x20license\x20that\x20can\x20be\x20found\x20in\n\
    \x20the\x20LICENSE\x20file\x20or\x20at:\n\x20https://polyformproject.org\
    /wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt\n\n\x08\n\x01\x02\
    \x12\x03\x08\0+\n\t\n\x02\x03\0\x12\x03\n\0?\n\t\n\x02\x03\x01\x12\x03\
    \x0b\0>\n\t\n\x02\x03\x02\x12\x03\x0c\06\n\t\n\x02\x03\x03\x12\x03\r\0D\
    \n\t\n\x02\x03\x04\x12\x03\x0e\0;\n\t\n\x02\x03\x05\x12\x03\x0f\0)\n\t\n\
    \x02\x03\x06\x12\x03\x10\0!\n\xf4\x02\n\x02\x06\0\x12\x04\x18\0H\x01\x1a\
    \xe7\x02\x20Manages\x20workflows\x20and\x20their\x20lifecycle,\x20includ\
    ing\x20creation,\x20deployment,\x20and\x20configuration.\n\n\x20Workflow\
    s\x20are\x20the\x20core\x20primitive\x20within\x20the\x20bitdrift\x20pla\
    tform\x20for\x20specifying\x20user\n\x20journeys\x20and\x20collecting\
    \x20telemetry\x20around\x20them.\x20A\x20workflow\x20is\x20made\x20up\
    \x20of\x20a\x20series\x20of\n\x20flows\x20that\x20describe\x20the\x20use\
    r\x20journey\x20and\x20rules\x20that\x20specify\x20when\x20users\x20tran\
    sition\n\x20between\x20flows.\n\n\n\n\x03\x06\0\x01\x12\x03\x18\x08\x17\
    \nu\n\x04\x06\0\x02\0\x12\x04\x1c\x02\x8c\x01\x1ag\x20Retrieves\x20a\x20\
    workflow\x20by\x20ID.\n\n\x20Also\x20updates\x20the\x20last\x20viewed\
    \x20time\x20of\x20the\x20workflow\x20for\x20the\x20current\x20user.\n\n\
    \x0c\n\x05\x06\0\x02\0\x01\x12\x03\x1c\x06\x11\n\x0c\n\x05\x06\0\x02\0\
    \x02\x12\x03\x1c\x12H\n\r\n\x05\x06\0\x02\0\x03\x12\x04\x1cS\x8a\x01\nH\
    \n\x04\x06\0\x02\x01\x12\x04\x1f\x02\x92\x01\x1a:\x20Lists\x20all\x20wor\
    kflows\x20available\x20to\x20the\x20authenticated\x20user.\n\n\x0c\n\x05\
    \x06\0\x02\x01\x01\x12\x03\x1f\x06\x13\n\x0c\n\x05\x06\0\x02\x01\x02\x12\
    \x03\x1f\x14L\n\r\n\x05\x06\0\x02\x01\x03\x12\x04\x1fW\x90\x01\n'\n\x04\
    \x06\0\x02\x02\x12\x04\"\x02\x95\x01\x1a\x19\x20Creates\x20a\x20new\x20w\
    orkflow.\n\n\x0c\n\x05\x06\0\x02\x02\x01\x12\x03\"\x06\x14\n\x0c\n\x05\
    \x06\0\x02\x02\x02\x12\x03\"\x15N\n\r\n\x05\x06\0\x02\x02\x03\x12\x04\"Y\
    \x93\x01\nf\n\x04\x06\0\x02\x03\x12\x04%\x02\x95\x01\x1aX\x20Updates\x20\
    a\x20workflow,\x20replacing\x20the\x20existing\x20configuration\x20with\
    \x20the\x20provided\x20definition.\n\n\x0c\n\x05\x06\0\x02\x03\x01\x12\
    \x03%\x06\x14\n\x0c\n\x05\x06\0\x02\x03\x02\x12\x03%\x15N\n\r\n\x05\x06\
    \0\x02\x03\x03\x12\x04%Y\x93\x01\nF\n\x04\x06\0\x02\x04\x12\x04(\x02\x95\
    \x01\x1a8\x20Renames\x20a\x20workflow\x20without\x20modifying\x20any\x20\
    other\x20fields.\n\n\x0c\n\x05\x06\0\x02\x04\x01\x12\x03(\x06\x14\n\x0c\
    \n\x05\x06\0\x02\x04\x02\x12\x03(\x15N\n\r\n\x05\x06\0\x02\x04\x03\x12\
    \x04(Y\x93\x01\n+\n\x04\x06\0\x02\x05\x12\x04+\x02\xa1\x01\x1a\x1d\x20As\
    signs\x20tags\x20to\x20a\x20workflow.\n\n\x0c\n\x05\x06\0\x02\x05\x01\
    \x12\x03+\x06\x18\n\x0c\n\x05\x06\0\x02\x05\x02\x12\x03+\x19V\n\r\n\x05\
    \x06\0\x02\x05\x03\x12\x04+a\x9f\x01\n\x94\x01\n\x04\x06\0\x02\x06\x12\
    \x041\x02\x95\x01\x1a\x85\x01\x20Deletes\x20a\x20workflow\x20permanently\
    .\n\n\x20This\x20removes\x20the\x20workflow\x20and\x20its\x20configurati\
    on\x20from\x20the\x20system.\x20This\x20operation\n\x20is\x20irreversibl\
    e.\n\n\x0c\n\x05\x06\0\x02\x06\x01\x12\x031\x06\x14\n\x0c\n\x05\x06\0\
    \x02\x06\x02\x12\x031\x15N\n\r\n\x05\x06\0\x02\x06\x03\x12\x041Y\x93\x01\
    \n\xc9\x01\n\x04\x06\0\x02\x07\x12\x047\x02\x95\x01\x1a\xba\x01\x20Deplo\
    ys\x20a\x20workflow,\x20making\x20it\x20active\x20and\x20able\x20to\x20r\
    eceive\x20traffic.\n\n\x20Deploying\x20creates\x20a\x20new\x20immutable\
    \x20version\x20of\x20the\x20workflow\x20configuration\x20that\n\x20is\
    \x20recorded\x20in\x20the\x20deployment\x20history.\n\n\x0c\n\x05\x06\0\
    \x02\x07\x01\x12\x037\x06\x14\n\x0c\n\x05\x06\0\x02\x07\x02\x12\x037\x15\
    N\n\r\n\x05\x06\0\x02\x07\x03\x12\x047Y\x93\x01\n)\n\x04\x06\0\x02\x08\
    \x12\x04:\x02\x8f\x01\x1a\x1b\x20Stops\x20a\x20running\x20workflow.\n\n\
    \x0c\n\x05\x06\0\x02\x08\x01\x12\x03:\x06\x12\n\x0c\n\x05\x06\0\x02\x08\
    \x02\x12\x03:\x13J\n\r\n\x05\x06\0\x02\x08\x03\x12\x04:U\x8d\x01\n2\n\
    \x04\x06\0\x02\t\x12\x04=\x02\x83\x01\x1a$\x20Lists\x20all\x20available\
    \x20workflow\x20tags.\n\n\x0c\n\x05\x06\0\x02\t\x01\x12\x03=\x06\x0e\n\
    \x0c\n\x05\x06\0\x02\t\x02\x12\x03=\x0fB\n\r\n\x05\x06\0\x02\t\x03\x12\
    \x04=M\x81\x01\nM\n\x04\x06\0\x02\n\x12\x04@\x02\x9b\x01\x1a?\x20Updates\
    \x20whether\x20a\x20workflow\x20is\x20favorited\x20for\x20the\x20current\
    \x20user.\n\n\x0c\n\x05\x06\0\x02\n\x01\x12\x03@\x06\x16\n\x0c\n\x05\x06\
    \0\x02\n\x02\x12\x03@\x17R\n\r\n\x05\x06\0\x02\n\x03\x12\x04@]\x99\x01\n\
    \x81\x02\n\x04\x06\0\x02\x0b\x12\x04G\x02\xb6\x01\x1a\xf2\x01\x20Creates\
    \x20or\x20updates\x20chart\x20metadata\x20for\x20a\x20workflow.\n\n\x20C\
    hart\x20metadata\x20includes\x20information\x20such\x20as\x20the\x20char\
    t\x20title,\x20description,\x20and\n\x20the\x20metric\x20query\x20that\
    \x20the\x20chart\x20is\x20based\x20on.\x20This\x20determines\x20how\x20w\
    orkflow\x20output\n\x20data\x20is\x20rendered\x20in\x20the\x20UI.\n\n\
    \x0c\n\x05\x06\0\x02\x0b\x01\x12\x03G\x06!\n\x0c\n\x05\x06\0\x02\x0b\x02\
    \x12\x03G\"e\n\r\n\x05\x06\0\x02\x0b\x03\x12\x04Gp\xb4\x01\n\n\n\x02\x04\
    \0\x12\x04J\0_\x01\n\n\n\x03\x04\0\x01\x12\x03J\x08$\n\x81\x01\n\x04\x04\
    \0\x02\0\x12\x03M\x02B\x1at\x20The\x20action\x20ID\x20whose\x20captured\
    \x20sessions\x20should\x20be\x20returned.\x20If\x20empty,\x20returns\n\
    \x20captured\x20sessions\x20across\x20all\x20actions.\n\n\x0c\n\x05\x04\
    \0\x02\0\x05\x12\x03M\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03M\t\x12\
    \n\x0c\n\x05\x04\0\x02\0\x03\x12\x03M\x15\x16\n\x0c\n\x05\x04\0\x02\0\
    \x08\x12\x03M\x17A\n\x0f\n\x08\x04\0\x02\0\x08\xaf\x08\x0e\x12\x03M\x18@\
    \nD\n\x04\x04\0\x02\x01\x12\x03P\x02<\x1a7\x20The\x20start\x20time\x20an\
    d\x20end\x20time\x20of\x20the\x20captured\x20sessions.\n\n\x0c\n\x05\x04\
    \0\x02\x01\x06\x12\x03P\x02,\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03P-7\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03P:;\n\xec\x01\n\x04\x04\0\x02\x02\
    \x12\x03T\x02v\x1a\xde\x01\x20Field\x20filters\x20to\x20apply\x20to\x20t\
    he\x20captured\x20session\x20search.\x20This\x20supports\x20filtering\
    \x20sessions\x20based\x20on\x20certain\x20indexed\x20fields\n\x20recorde\
    d\x20alongside\x20the\x20captured\x20session.\x20Reach\x20out\x20to\x20t\
    he\x20bitdrift\x20team\x20to\x20index\x20additional\x20fields.\n\n\x0c\n\
    \x05\x04\0\x02\x02\x04\x12\x03T\x02\n\n\x0c\n\x05\x04\0\x02\x02\x06\x12\
    \x03T\x0b9\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03T:C\n\x0c\n\x05\x04\0\
    \x02\x02\x03\x12\x03TFG\n\x0c\n\x05\x04\0\x02\x02\x08\x12\x03THu\n\x0f\n\
    \x08\x04\0\x02\x02\x08\xaf\x08\x12\x12\x03TIt\n\x90\x01\n\x04\x04\0\x02\
    \x03\x12\x03X\x02\x1b\x1a\x82\x01\x20The\x20page\x20number\x20and\x20the\
    \x20number\x20of\x20items\x20per\x20page.\x20The\x20server\x20will\x20us\
    e\x20this\n\x20to\x20paginate\x20the\x20results.\x20Defaults\x20to\x201\
    \x20when\x20not\x20set.\n\n\x0c\n\x05\x04\0\x02\x03\x04\x12\x03X\x02\n\n\
    \x0c\n\x05\x04\0\x02\x03\x05\x12\x03X\x0b\x11\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03X\x12\x16\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03X\x19\x1a\nU\
    \n\x04\x04\0\x02\x04\x12\x04[\x02^\x05\x1aG\x20The\x20number\x20of\x20it\
    ems\x20to\x20return\x20per\x20page.\x20Defaults\x20to\x20100\x20when\x20\
    not\x20set.\n\n\x0c\n\x05\x04\0\x02\x04\x04\x12\x03[\x02\n\n\x0c\n\x05\
    \x04\0\x02\x04\x05\x12\x03[\x0b\x11\n\x0c\n\x05\x04\0\x02\x04\x01\x12\
    \x03[\x12\x1a\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03[\x1d\x1e\n\r\n\x05\
    \x04\0\x02\x04\x08\x12\x04[\x1f^\x04\n\x10\n\x08\x04\0\x02\x04\x08\xaf\
    \x08\x06\x12\x04[\x20^\x03\n\n\n\x02\x04\x01\x12\x04a\0h\x01\n\n\n\x03\
    \x04\x01\x01\x12\x03a\x08%\n>\n\x04\x04\x01\x02\0\x12\x03c\x02U\x1a1\x20\
    The\x20captured\x20sessions\x20that\x20matched\x20the\x20request.\n\n\
    \x0c\n\x05\x04\x01\x02\0\x04\x12\x03c\x02\n\n\x0c\n\x05\x04\x01\x02\0\
    \x06\x12\x03c\x0b>\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03c?P\n\x0c\n\x05\
    \x04\x01\x02\0\x03\x12\x03cST\nc\n\x04\x04\x01\x02\x01\x12\x03g\x02\x18\
    \x1aV\x20The\x20total\x20number\x20of\x20matching\x20sessions\x20before\
    \x20pagination,\x20subject\x20to\n\x20service\x20limits.\n\n\x0c\n\x05\
    \x04\x01\x02\x01\x05\x12\x03g\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\
    \x12\x03g\t\x13\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03g\x16\x17\n\x0b\n\
    \x02\x04\x02\x12\x05j\0\x87\x01\x01\n\n\n\x03\x04\x02\x01\x12\x03j\x08.\
    \n\x0c\n\x04\x04\x02\x03\0\x12\x04k\x02z\x03\n\x0c\n\x05\x04\x02\x03\0\
    \x01\x12\x03k\n\x18\n\xb5\x01\n\x06\x04\x02\x03\0\x02\0\x12\x03n\x04`\
    \x1a\xa5\x01\x20The\x20approximate\x20first-seen\x20time\x20of\x20the\
    \x20target\x20session.\x20The\x20service\x20searches\x20within\x2030\x20\
    days\n\x20before\x20and\x20after\x20this\x20time\x20to\x20locate\x20the\
    \x20target\x20session\x20for\x20the\x20device.\n\n\x0e\n\x07\x04\x02\x03\
    \0\x02\0\x06\x12\x03n\x04\x1e\n\x0e\n\x07\x04\x02\x03\0\x02\0\x01\x12\
    \x03n\x1f-\n\x0e\n\x07\x04\x02\x03\0\x02\0\x03\x12\x03n01\n\x0e\n\x07\
    \x04\x02\x03\0\x02\0\x08\x12\x03n2_\n\x11\n\n\x04\x02\x03\0\x02\0\x08\
    \xaf\x08\x11\x12\x03n3^\n\xa2\x01\n\x06\x04\x02\x03\0\x02\x01\x12\x04r\
    \x04u\x07\x1a\x91\x01\x20The\x20target\x20session\x20ID.\x20The\x20targe\
    t\x20session\x20is\x20excluded\x20from\x20the\x20results.\x20If\x20it\
    \x20cannot\x20be\n\x20found\x20for\x20the\x20device,\x20the\x20service\
    \x20returns\x20no\x20sessions.\n\n\x0e\n\x07\x04\x02\x03\0\x02\x01\x05\
    \x12\x03r\x04\n\n\x0e\n\x07\x04\x02\x03\0\x02\x01\x01\x12\x03r\x0b\x1f\n\
    \x0e\n\x07\x04\x02\x03\0\x02\x01\x03\x12\x03r\"#\n\x0f\n\x07\x04\x02\x03\
    \0\x02\x01\x08\x12\x04r$u\x06\n\x12\n\n\x04\x02\x03\0\x02\x01\x08\xaf\
    \x08\x0e\x12\x04r%u\x05\n\x98\x01\n\x06\x04\x02\x03\0\x02\x02\x12\x03y\
    \x04$\x1a\x88\x01\x20The\x20maximum\x20number\x20of\x20sessions\x20to\
    \x20return\x20before\x20and\x20after\x20the\x20target\x20session.\x20Def\
    aults\x20to\n\x20five\x20sessions\x20in\x20each\x20direction\x20when\x20\
    unset.\n\n\x0e\n\x07\x04\x02\x03\0\x02\x02\x04\x12\x03y\x04\x0c\n\x0e\n\
    \x07\x04\x02\x03\0\x02\x02\x05\x12\x03y\r\x13\n\x0e\n\x07\x04\x02\x03\0\
    \x02\x02\x01\x12\x03y\x14\x1f\n\x0e\n\x07\x04\x02\x03\0\x02\x02\x03\x12\
    \x03y\"#\nE\n\x04\x04\x02\x02\0\x12\x05}\x02\x80\x01\x05\x1a6\x20The\x20\
    UUID\x20of\x20the\x20device\x20whose\x20sessions\x20are\x20requested.\n\
    \n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03}\x02\x08\n\x0c\n\x05\x04\x02\x02\
    \0\x01\x12\x03}\t\x12\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03}\x15\x16\n\
    \x0e\n\x05\x04\x02\x02\0\x08\x12\x05}\x17\x80\x01\x04\n\x11\n\x08\x04\
    \x02\x02\0\x08\xaf\x08\x0e\x12\x05}\x18\x80\x01\x03\n\x0e\n\x04\x04\x02\
    \x08\0\x12\x06\x82\x01\x02\x86\x01\x03\n\r\n\x05\x04\x02\x08\0\x01\x12\
    \x04\x82\x01\x08\x12\n\r\n\x05\x04\x02\x08\0\x02\x12\x04\x83\x01\x04&\n\
    \x0f\n\x07\x04\x02\x08\0\x02\xaf\x08\x12\x04\x83\x01\x04&\nL\n\x04\x04\
    \x02\x02\x01\x12\x04\x85\x01\x04r\x1a>\x20Returns\x20sessions\x20near\
    \x20the\x20target\x20session\x20for\x20this\x20device\x20ID.\n\n\r\n\x05\
    \x04\x02\x02\x01\x06\x12\x04\x85\x01\x04]\n\r\n\x05\x04\x02\x02\x01\x01\
    \x12\x04\x85\x01^m\n\r\n\x05\x04\x02\x02\x01\x03\x12\x04\x85\x01pq\n\x0c\
    \n\x02\x04\x03\x12\x06\x89\x01\0\x9f\x01\x01\n\x0b\n\x03\x04\x03\x01\x12\
    \x04\x89\x01\x08/\n\x0e\n\x04\x04\x03\x03\0\x12\x06\x8a\x01\x02\x90\x01\
    \x03\n\r\n\x05\x04\x03\x03\0\x01\x12\x04\x8a\x01\n\x19\n*\n\x06\x04\x03\
    \x03\0\x02\0\x12\x04\x8c\x01\x04C\x1a\x1a\x20The\x20captured\x20session\
    \x20ID.\n\n\x0f\n\x07\x04\x03\x03\0\x02\0\x05\x12\x04\x8c\x01\x04\n\n\
    \x0f\n\x07\x04\x03\x03\0\x02\0\x01\x12\x04\x8c\x01\x0b\x15\n\x0f\n\x07\
    \x04\x03\x03\0\x02\0\x03\x12\x04\x8c\x01\x18\x19\n\x0f\n\x07\x04\x03\x03\
    \0\x02\0\x08\x12\x04\x8c\x01\x1aB\n\x12\n\n\x04\x03\x03\0\x02\0\x08\xaf\
    \x08\x0e\x12\x04\x8c\x01\x1bA\n?\n\x06\x04\x03\x03\0\x02\x01\x12\x04\x8f\
    \x01\x04\\\x1a/\x20The\x20time\x20when\x20the\x20session\x20was\x20first\
    \x20observed.\n\n\x0f\n\x07\x04\x03\x03\0\x02\x01\x06\x12\x04\x8f\x01\
    \x04\x1e\n\x0f\n\x07\x04\x03\x03\0\x02\x01\x01\x12\x04\x8f\x01\x1f)\n\
    \x0f\n\x07\x04\x03\x03\0\x02\x01\x03\x12\x04\x8f\x01,-\n\x0f\n\x07\x04\
    \x03\x03\0\x02\x01\x08\x12\x04\x8f\x01.[\n\x12\n\n\x04\x03\x03\0\x02\x01\
    \x08\xaf\x08\x11\x12\x04\x8f\x01/Z\n\x0e\n\x04\x04\x03\x03\x01\x12\x06\
    \x92\x01\x02\x98\x01\x03\n\r\n\x05\x04\x03\x03\x01\x01\x12\x04\x92\x01\n\
    \x18\n>\n\x06\x04\x03\x03\x01\x02\0\x12\x04\x94\x01\x04}\x1a.\x20Session\
    s\x20observed\x20before\x20the\x20target\x20session.\n\n\x0f\n\x07\x04\
    \x03\x03\x01\x02\0\x04\x12\x04\x94\x01\x04\x0c\n\x0f\n\x07\x04\x03\x03\
    \x01\x02\0\x06\x12\x04\x94\x01\rh\n\x0f\n\x07\x04\x03\x03\x01\x02\0\x01\
    \x12\x04\x94\x01ix\n\x0f\n\x07\x04\x03\x03\x01\x02\0\x03\x12\x04\x94\x01\
    {|\n=\n\x06\x04\x03\x03\x01\x02\x01\x12\x04\x97\x01\x04|\x1a-\x20Session\
    s\x20observed\x20after\x20the\x20target\x20session.\n\n\x0f\n\x07\x04\
    \x03\x03\x01\x02\x01\x04\x12\x04\x97\x01\x04\x0c\n\x0f\n\x07\x04\x03\x03\
    \x01\x02\x01\x06\x12\x04\x97\x01\rh\n\x0f\n\x07\x04\x03\x03\x01\x02\x01\
    \x01\x12\x04\x97\x01iw\n\x0f\n\x07\x04\x03\x03\x01\x02\x01\x03\x12\x04\
    \x97\x01z{\n\x0e\n\x04\x04\x03\x08\0\x12\x06\x9a\x01\x02\x9e\x01\x03\n\r\
    \n\x05\x04\x03\x08\0\x01\x12\x04\x9a\x01\x08\x12\n\r\n\x05\x04\x03\x08\0\
    \x02\x12\x04\x9b\x01\x04&\n\x0f\n\x07\x04\x03\x08\0\x02\xaf\x08\x12\x04\
    \x9b\x01\x04&\n@\n\x04\x04\x03\x02\0\x12\x04\x9d\x01\x04s\x1a2\x20The\
    \x20sessions\x20returned\x20around\x20the\x20target\x20session.\n\n\r\n\
    \x05\x04\x03\x02\0\x06\x12\x04\x9d\x01\x04^\n\r\n\x05\x04\x03\x02\0\x01\
    \x12\x04\x9d\x01_n\n\r\n\x05\x04\x03\x02\0\x03\x12\x04\x9d\x01qr\nV\n\
    \x02\x06\x01\x12\x06\xa2\x01\0\xa8\x01\x01\x1aH\x20Queries\x20data\x20co\
    llected\x20by\x20workflow\x20actions,\x20such\x20as\x20captured\x20sessi\
    ons.\n\n\x0b\n\x03\x06\x01\x01\x12\x04\xa2\x01\x08\x1b\no\n\x04\x06\x01\
    \x02\0\x12\x05\xa4\x01\x02\xaa\x01\x1a`\x20Fetches\x20captured\x20sessio\
    ns\x20matching\x20the\x20given\x20criteria,\x20optionally\x20scoped\x20t\
    o\x20a\x20specific\x20action.\n\n\r\n\x05\x06\x01\x02\0\x01\x12\x04\xa4\
    \x01\x06\x1b\n\r\n\x05\x06\x01\x02\0\x02\x12\x04\xa4\x01\x1c\\\n\x0e\n\
    \x05\x06\x01\x02\0\x03\x12\x05\xa4\x01g\xa8\x01\nZ\n\x04\x06\x01\x02\x01\
    \x12\x05\xa7\x01\x02\xc8\x01\x1aK\x20Fetches\x20sessions\x20for\x20a\x20\
    device\x20that\x20were\x20observed\x20around\x20a\x20target\x20session.\
    \n\n\r\n\x05\x06\x01\x02\x01\x01\x12\x04\xa7\x01\x06%\n\r\n\x05\x06\x01\
    \x02\x01\x02\x12\x04\xa7\x01&p\n\x0e\n\x05\x06\x01\x02\x01\x03\x12\x05\
    \xa7\x01{\xc6\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(7);
            deps.push(super::time_series::file_descriptor().clone());
            deps.push(super::chart_metadata::file_descriptor().clone());
            deps.push(super::common::file_descriptor().clone());
            deps.push(super::captured_sessions::file_descriptor().clone());
            deps.push(super::workflow::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(7);
            messages.push(FetchCapturedSessionsRequest::generated_message_descriptor_data());
            messages.push(FetchCapturedSessionsResponse::generated_message_descriptor_data());
            messages.push(FetchCapturedSessionsByDeviceIdRequest::generated_message_descriptor_data());
            messages.push(FetchCapturedSessionsByDeviceIdResponse::generated_message_descriptor_data());
            messages.push(fetch_captured_sessions_by_device_id_request::ProximityQuery::generated_message_descriptor_data());
            messages.push(fetch_captured_sessions_by_device_id_response::DeviceIdSession::generated_message_descriptor_data());
            messages.push(fetch_captured_sessions_by_device_id_response::ProximityQuery::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
