[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-metadata"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dev-dependencies]
bd-test-helpers             = { path = "../bd-test-helpers", default-features = false }
ctor.workspace              = true
parking_lot.workspace       = true
pretty_assertions.workspace = true

[dependencies]
bd-workspace-hack.workspace = true
