[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-time"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
async-trait.workspace = true
parking_lot.workspace = true
protobuf.workspace    = true
rand.workspace        = true
time.workspace        = true
tokio.workspace       = true
