[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-panic"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
color-backtrace.workspace = true
log.workspace             = true
