[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-panic"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-workspace-hack.workspace = true
color-backtrace.workspace   = true
log.workspace               = true
termcolor.workspace         = true
