[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-session-replay"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
bd-client-common.path       = "../bd-client-common"
bd-client-stats-store.path  = "../bd-client-stats-store"
bd-error-reporter.path      = "../bd-error-reporter"
bd-log-primitives.path      = "../bd-log-primitives"
bd-proto.path               = "../bd-proto"
bd-runtime.path             = "../bd-runtime"
bd-shutdown.path            = "../bd-shutdown"
bd-stats-common.path        = "../bd-stats-common"
bd-time.path                = "../bd-time"
bd-workspace-hack.workspace = true
log.workspace               = true
parking_lot.workspace       = true
time.workspace              = true
tokio.workspace             = true

[dev-dependencies]
bd-test-helpers.path  = "../bd-test-helpers"
bd-time.path          = "../bd-time"
ctor.workspace        = true
parking_lot.workspace = true
tempfile.workspace    = true
time.workspace        = true
tokio-test.workspace  = true
