[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-session-replay"
publish      = false
version      = "1.0.0"

[dependencies]
anyhow.workspace         = true
bd-internal-logging.path = "../bd-internal-logging"
bd-log-primitives.path   = "../bd-log-primitives"
bd-runtime.path          = "../bd-runtime"
bd-shutdown.path         = "../bd-shutdown"
bd-time.path             = "../bd-time"
ctor.workspace           = true
log.workspace            = true
parking_lot.workspace    = true
time.workspace           = true
tokio.workspace          = true

[dev-dependencies]
bd-test-helpers.path  = "../bd-test-helpers"
bd-time.path          = "../bd-time"
parking_lot.workspace = true
tempfile.workspace    = true
time.workspace        = true
tokio-test.workspace  = true
