[package]
edition = "2024"
license = "Apache-2.0"
name    = "bd-log"
publish = false
version = "1.0.0"

[lib]
doctest = false

[features]
default = ["otel"]
otel    = [
  "dep:http",
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
  "dep:tracing-opentelemetry",
]

[dependencies]
anyhow.workspace                = true
bd-workspace-hack.workspace     = true
http                            = { workspace = true, optional = true }
log.workspace                   = true
opentelemetry                   = { workspace = true, optional = true }
opentelemetry-otlp              = { workspace = true, optional = true }
opentelemetry_sdk               = { workspace = true, optional = true }
parking_lot.workspace           = true
time.workspace                  = true
tokio.workspace                 = true
tracing.workspace               = true
tracing-log.workspace           = true
tracing-opentelemetry           = { workspace = true, optional = true }
tracing-subscriber.workspace    = true

[dev-dependencies]
bd-time = { path = "../bd-time" }
