[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-server-stats"
publish      = false
version      = "1.0.0"

[dependencies]
bd-stats-common.path    = "../bd-stats-common"
bd-time.path            = "../bd-time"
concat-string.workspace = true
dashmap.workspace       = true
itertools.workspace     = true
log.workspace           = true
parking_lot.workspace   = true
prometheus.workspace    = true
regex.workspace         = true
thiserror.workspace     = true
time.workspace          = true
tokio.workspace         = true

[dev-dependencies]
bd-log.path       = "../bd-log"
ctor.workspace    = true
matches.workspace = true
