load("@crates//:defs.bzl", "aliases")
load("//tools/rust:feature_variants.bzl", "rust_library_with_feature_variants")

package(default_visibility = ["//visibility:public"])

rust_library_with_feature_variants(
    name = "bd-resilient-kv",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "bd_resilient_kv",
    crate_root = "src/lib.rs",
    edition = "2024",
    feature_variants = {
        "fuzz": {
            "dependency_overrides": {
                "//shared-core/bd-client-stats-store": "//shared-core/bd-client-stats-store:bd-client-stats-store-fuzz",
                "//shared-core/bd-stats-common": "//shared-core/bd-stats-common:bd-stats-common-fuzz",
            },
        },
    },
)
