[package]
edition      = "2024"
license-file = "../LICENSE.polyform"
name         = "bd-macros"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-macros-impl.path         = "../bd-macros-impl"
bd-workspace-hack.workspace = true
time.workspace              = true
uuid.workspace              = true
