[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-resource-utilization"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace       = true
bd-client-common.path  = "../bd-client-common"
bd-log-primitives.path = "../bd-log-primitives"
bd-runtime.path        = "../bd-runtime"
bd-shutdown.path       = "../bd-shutdown"
bd-time.path           = "../bd-time"
log.workspace          = true
time.workspace         = true
tokio.workspace        = true

[dev-dependencies]
bd-test-helpers.path  = "../bd-test-helpers"
bd-time.path          = "../bd-time"
ctor.workspace        = true
parking_lot.workspace = true
tempfile.workspace    = true
time.workspace        = true
tokio-test.workspace  = true
