[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-report-convert"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
bd-workspace-hack.workspace = true

[build-dependencies]
bindgen.workspace    = true
cc.workspace         = true
cmake.workspace      = true
flatc-rust.workspace = true
