[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-report-convert"
publish      = false
version      = "1.0.0"

[build-dependencies]
cc.workspace         = true
cmake.workspace      = true
flatc-rust.workspace = true
