[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-bonjson"
publish      = false
version      = "1.0.0"

[dev-dependencies]
assert_no_alloc = "1.1.2"
bd-test-helpers.path     = "../bd-test-helpers"
ctor.workspace           = true
tempfile.workspace = true
