[package]
name = "bd-bonjson"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tempfile.workspace = true

[dev-dependencies]
assert_no_alloc = "1.1.2"
