[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-bonjson"
publish      = false
version      = "1.0.0"

[dependencies]
tempfile.workspace = true

[dev-dependencies]
assert_no_alloc = "1.1.2"
