"""Render decoding-only declarations for protobuf values retained by response consumers.

Input is a protoc FileDescriptorSet including imports. No generated Rust is read.
Run this script with a Python environment containing the standard protobuf package.
"""

import argparse
import pathlib
import re
from collections import defaultdict

from google.protobuf import descriptor_pb2


MODULES = {
    "api": "client::api",
    "runtime": "client::runtime",
    "config": "config::v1::config",
    "filter": "filter::filter",
    "bdtail_config": "bdtail::bdtail_config",
    "log_matcher": "log_matcher::log_matcher",
    "value_matcher": "value_matcher::value_matcher",
    "matcher": "state::matcher",
    "scope": "state::scope",
    "state_payload": "state::state_payload",
    "payload": "logging::payload",
    "workflow": "workflow::workflow",
    "save_field": "workflow::save_field",
    "workflow_command": "workflow::workflow_command",
}
CLIENT = ".bitdrift_public.protobuf.client.v1."
ROOTS = [CLIENT + name for name in (
    "HandshakeResponse", "LogUploadResponse", "RuntimeUpdate", "ErrorShutdown",
    "StatsUploadResponse", "LogUploadIntentResponse", "FlushBuffers",
    "SankeyPathUploadResponse", "SankeyIntentResponse", "UploadArtifactResponse",
    "UploadArtifactIntentResponse", "DeviceCommandUpdateAck", "ClientStateUpdate",
)] + [
    ".bitdrift_public.protobuf.bdtail.v1.DeviceCommandRequest",
    ".bitdrift_public.protobuf.workflow.v1.Workflow.Action.ActionGenerateLog",
]
FIELD = descriptor_pb2.FieldDescriptorProto
SCALARS = {
    FIELD.TYPE_DOUBLE: "f64", FIELD.TYPE_FLOAT: "f32",
    FIELD.TYPE_INT64: "i64", FIELD.TYPE_UINT64: "u64",
    FIELD.TYPE_INT32: "i32", FIELD.TYPE_UINT32: "u32",
    FIELD.TYPE_BOOL: "bool", FIELD.TYPE_STRING: "String", FIELD.TYPE_BYTES: "Vec<u8>",
}
KEYWORDS = {"type", "match", "ref", "self", "Self", "loop", "mod", "move", "use"}


def write_modules(groups, output, public=False):
    output.mkdir(parents=True, exist_ok=True)
    header = "// Generated by generate-response-decoders.py from source-schema descriptors.\n"
    for existing in output.glob("*.rs"):
        if existing.stem not in groups and existing.name != "mod.rs" and existing.read_text().startswith(header):
            existing.unlink()
    for name, declarations in sorted(groups.items()):
        aliases, imports = {}, []

        def bind(path):
            if path in aliases:
                return aliases[path]
            parent, _, symbol = path.rpartition("::")
            if len(path) > 72:
                parent = bind(parent)
            alias = ("Proto" if symbol[:1].isupper() else "proto_") + str(len(aliases))
            aliases[path] = alias
            imports.append(f"use {parent}::{symbol} as {alias};")
            return alias

        body = re.sub(r"\bbd_proto(?:::[A-Za-z_][A-Za-z_0-9]*)+", lambda match: bind(match.group()), "\n\n".join(declarations))
        (output / (name + ".rs")).write_text(header + "use crate as bd_proto_util;\nuse bd_macros::proto_deserialize;\n" + "\n".join(imports) + "\n\n" + body + "\n")
    visibility = "pub " if public else ""
    (output / "mod.rs").write_text(header + "\n" + "\n".join(visibility + "mod " + name + ";" for name in sorted(groups)) + "\n")


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def camel(name):
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def field_name(name):
    return name + "_" if name in KEYWORDS else name


def generate(descriptors, output):
    messages, enums, paths, files = {}, {}, {}, {}

    def module(file):
        basename = pathlib.Path(file.name).stem
        if basename == "matcher" and ".client." in file.package:
            return "client::matcher"
        return MODULES.get(basename, basename)

    def register(file, parents, message):
        full = "." + file.package + "." + ".".join(parents + [message.name])
        basename = pathlib.Path(file.name).stem
        if file.name.startswith("google/protobuf/"):
            root = "protobuf::well_known_types::" + ("struct_" if basename == "struct" else basename)
        else:
            root = "bd_proto::protos::" + module(file)
        paths[full] = root + "::" + "::".join([snake(parent) for parent in parents] + [message.name])
        messages[full], files[full] = message, basename
        for enum in message.enum_type:
            enum_full = full + "." + enum.name
            enums[enum_full] = enum
            paths[enum_full] = root + "::" + "::".join([snake(parent) for parent in parents + [message.name]] + [enum.name])
        for nested in message.nested_type:
            register(file, parents + [message.name], nested)

    for file in descriptors.file:
        if file.name.startswith("validate/") or file.name.startswith("google/protobuf/descriptor"):
            continue
        for message in file.message_type:
            register(file, [], message)
        for enum in file.enum_type:
            full = "." + file.package + "." + enum.name
            enums[full] = enum
            basename = pathlib.Path(file.name).stem
            paths[full] = "bd_proto::protos::" + module(file) + "::" + enum.name

    required = set()

    def visit(full):
        if full in required:
            return
        required.add(full)
        for field in messages[full].field:
            if field.type == FIELD.TYPE_MESSAGE:
                visit(field.type_name)

    for root in ROOTS:
        visit(root)

    def rust_type(field, map_value=False):
        if field.type == FIELD.TYPE_MESSAGE:
            message = messages[field.type_name]
            if message.options.map_entry:
                return "std::collections::HashMap<" + rust_type(message.field[0]) + ", " + rust_type(message.field[1], map_value=True) + ">"
            base = paths[field.type_name]
        elif field.type == FIELD.TYPE_ENUM:
            base = "protobuf::EnumOrUnknown<" + paths[field.type_name] + ">"
        else:
            base = SCALARS[field.type]
        if field.label == FIELD.LABEL_REPEATED:
            return "Vec<" + base + ">"
        if field.proto3_optional:
            return "Option<" + base + ">"
        if field.type == FIELD.TYPE_MESSAGE and not field.HasField("oneof_index") and not map_value:
            return "protobuf::MessageField<" + base + ">"
        return base

    groups = defaultdict(list)
    for index, full in enumerate(sorted(required)):
        message = messages[full]
        if message.options.map_entry:
            continue
        path = paths[full]
        fields = []
        real_oneofs = {}
        for field in message.field:
            if field.HasField("oneof_index") and not field.proto3_optional:
                real_oneofs.setdefault(field.oneof_index, []).append(field)
            else:
                fields.extend([f"  #[field(id = {field.number})]", f"  {field_name(field.name)}: {rust_type(field)},"])
        nested_module = path.rsplit("::", 1)[0] + "::" + snake(message.name)
        for oneof_index, variants in real_oneofs.items():
            oneof_name = message.oneof_decl[oneof_index].name
            enum_path = nested_module + "::" + oneof_name[:1].upper() + oneof_name[1:]
            fields.extend(["  #[field(oneof)]", f"  {field_name(oneof_name)}: Option<{enum_path}>,"])
            lines = [f'#[proto_deserialize(target = "{enum_path}")]', f"enum Oneof{index}_{oneof_index} {{"]
            for field in variants:
                lines.extend([f"  #[field(id = {field.number})]", f"  {camel(field.name)}({rust_type(field)}),"])
            lines.append("}")
            groups[files[full]].append("\n".join(lines))
        groups[files[full]].append("\n".join([f'#[proto_deserialize(target = "{path}")]', f"struct Decoder{index} {{"] + fields + ["}"]))

    write_modules(groups, output)
    print(f"Rendered {len(required)} reachable messages into {len(groups)} schema modules")
    generate_views(messages, paths, files, output.parent / "views")


def generate_views(messages, paths, files, output):
    roots = [
        ".bitdrift_public.protobuf.client.v1.ConfigurationUpdate",
        ".bitdrift_public.protobuf.config.v1.LogMatcher",
        ".bitdrift_public.protobuf.matcher.v1.LogMatcher",
    ]
    required = set()
    retained = {
        ".bitdrift_public.protobuf.client.v1.ClientStateUpdate",
        ".bitdrift_public.protobuf.logging.v1.Data",
        ".bitdrift_public.protobuf.bdtail.v1.DeviceCommandRequest",
        ".bitdrift_public.protobuf.workflow.v1.Workflow.Action.ActionGenerateLog",
        ".bitdrift_public.protobuf.workflow.v1.WorkflowCommandSelector",
    }

    def visit(full):
        if full in required or full in retained:
            return
        required.add(full)
        for field in messages[full].field:
            if field.type == FIELD.TYPE_MESSAGE:
                visit(field.type_name)

    for root in roots:
        visit(root)

    def name(full):
        parts = full.split(".")
        index = next(index for index, part in enumerate(parts) if part[:1].isupper())
        return "".join(parts[index:])

    def reference(full):
        if full in retained:
            return paths[full]
        return "super::" + files[full] + "::" + name(full) + "<'a>"

    def rust_type(field, map_value=False):
        if field.type == FIELD.TYPE_MESSAGE:
            nested = messages[field.type_name]
            if nested.options.map_entry:
                return "std::collections::HashMap<" + rust_type(nested.field[0]) + ", " + rust_type(nested.field[1], True) + ">"
            base = reference(field.type_name)
        elif field.type == FIELD.TYPE_ENUM:
            base = "protobuf::EnumOrUnknown<" + paths[field.type_name] + ">"
        else:
            base = SCALARS[field.type]
            if field.label != FIELD.LABEL_REPEATED and field.type == FIELD.TYPE_STRING:
                base = "&'a str"
            elif field.type == FIELD.TYPE_BYTES:
                base = "&'a [u8]"
        if field.label == FIELD.LABEL_REPEATED:
            return "Vec<" + base + ">"
        if field.proto3_optional or (field.type == FIELD.TYPE_MESSAGE and not field.HasField("oneof_index") and not map_value):
            return "Option<" + base + ">"
        return base

    groups = defaultdict(list)
    for full in sorted(required):
        message = messages[full]
        if message.options.map_entry:
            continue
        fields, oneofs = [], {}
        for field in message.field:
            if field.HasField("oneof_index") and not field.proto3_optional:
                oneofs.setdefault(field.oneof_index, []).append(field)
            else:
                fields.extend([f"  #[field(id = {field.number})]", f"  {field_name(field.name)}: {rust_type(field)},"])
        for index, variants in oneofs.items():
            oneof_name = message.oneof_decl[index].name
            enum_name = name(full) + camel(oneof_name)
            fields.extend(["  #[field(oneof)]", f"  {field_name(oneof_name)}: Option<{enum_name}<'a>>,"])
            lines = ["#[proto_deserialize]", "#[derive(Clone, Debug)]", f"pub enum {enum_name}<'a> {{"]
            for field in variants:
                lines.extend([f"  #[field(id = {field.number})]", f"  {camel(field.name)}({rust_type(field)}),"])
            lines.append("}")
            groups[files[full]].append("\n".join(lines))
        groups[files[full]].append("\n".join(["#[proto_deserialize(view)]", f"pub struct {name(full)}<'a> {{"] + fields + ["}"]))
    write_modules(groups, output, public=True)
    print(f"Rendered {len(required)} borrowed configuration message views")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("descriptor_set", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()
    descriptor = descriptor_pb2.FileDescriptorSet.FromString(args.descriptor_set.read_bytes())
    generate(descriptor, args.output)


if __name__ == "__main__":
    main()
