load("@crates//:defs.bzl", "aliases")
load("//tools/rust:feature_variants.bzl", "rust_library_with_feature_variants")
load("//tools/rust:tests.bzl", "rust_library_test")

package(default_visibility = ["//visibility:public"])

rust_library_with_feature_variants(
    name = "bd-workflows",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["cloneable-config"],
    crate_name = "bd_workflows",
    crate_root = "src/lib.rs",
    edition = "2024",
    feature_variants = {
        "fuzz": {
            "crate_features": ["fuzzing"],
            "dependency_overrides": {
                "//shared-core/bd-client-stats": "//shared-core/bd-client-stats:bd-client-stats-fuzz",
                "//shared-core/bd-client-stats-store": "//shared-core/bd-client-stats-store:bd-client-stats-store-fuzz",
                "//shared-core/bd-stats-common": "//shared-core/bd-stats-common:bd-stats-common-fuzz",
                "//shared-core/bd-workflow-stats": "//shared-core/bd-workflow-stats:bd-workflow-stats-fuzz",
            },
        },
    },
)

rust_library_test(crate = ":bd-workflows")
