// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 34.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/timeline/v1/info.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.GetSessionInfoRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetSessionInfoRequest {
    // message fields
    ///  The session ID to query for.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoRequest.session_id)
    pub session_id: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.GetSessionInfoRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetSessionInfoRequest {
    fn default() -> &'a GetSessionInfoRequest {
        <GetSessionInfoRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetSessionInfoRequest {
    pub fn new() -> GetSessionInfoRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "session_id",
            |m: &GetSessionInfoRequest| { &m.session_id },
            |m: &mut GetSessionInfoRequest| { &mut m.session_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetSessionInfoRequest>(
            "GetSessionInfoRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetSessionInfoRequest {
    const NAME: &'static str = "GetSessionInfoRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.session_id = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.session_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.session_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.session_id.is_empty() {
            os.write_string(1, &self.session_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetSessionInfoRequest {
        GetSessionInfoRequest::new()
    }

    fn clear(&mut self) {
        self.session_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetSessionInfoRequest {
        static instance: GetSessionInfoRequest = GetSessionInfoRequest {
            session_id: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetSessionInfoRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetSessionInfoRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetSessionInfoRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetSessionInfoRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetSessionInfoResponse {
    // message fields
    ///  The model of the device.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.device_model)
    pub device_model: ::std::string::String,
    ///  The user id associated with the session.
    ///  This one is a special case, where we rely on the SDK being configured to return this.
    ///  There may be other special cases like this in the future.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.user_id)
    pub user_id: ::std::option::Option<::std::string::String>,
    ///  The start time of the session.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.start_time)
    pub start_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  The end time of the session.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.end_time)
    pub end_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  The device ID associated with the session.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.device_id)
    pub device_id: ::std::string::String,
    ///  The platform and app information associated with the session.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.platform)
    pub platform: ::protobuf::MessageField<super::platform::Platform>,
    ///  The operating system of the device.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.os)
    pub os: ::std::string::String,
    ///  The version of the operating system of the device.
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.os_version)
    pub os_version: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.GetSessionInfoResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetSessionInfoResponse {
    fn default() -> &'a GetSessionInfoResponse {
        <GetSessionInfoResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetSessionInfoResponse {
    pub fn new() -> GetSessionInfoResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_model",
            |m: &GetSessionInfoResponse| { &m.device_model },
            |m: &mut GetSessionInfoResponse| { &mut m.device_model },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "user_id",
            |m: &GetSessionInfoResponse| { &m.user_id },
            |m: &mut GetSessionInfoResponse| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "start_time",
            |m: &GetSessionInfoResponse| { &m.start_time },
            |m: &mut GetSessionInfoResponse| { &mut m.start_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "end_time",
            |m: &GetSessionInfoResponse| { &m.end_time },
            |m: &mut GetSessionInfoResponse| { &mut m.end_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_id",
            |m: &GetSessionInfoResponse| { &m.device_id },
            |m: &mut GetSessionInfoResponse| { &mut m.device_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::platform::Platform>(
            "platform",
            |m: &GetSessionInfoResponse| { &m.platform },
            |m: &mut GetSessionInfoResponse| { &mut m.platform },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "os",
            |m: &GetSessionInfoResponse| { &m.os },
            |m: &mut GetSessionInfoResponse| { &mut m.os },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "os_version",
            |m: &GetSessionInfoResponse| { &m.os_version },
            |m: &mut GetSessionInfoResponse| { &mut m.os_version },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetSessionInfoResponse>(
            "GetSessionInfoResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetSessionInfoResponse {
    const NAME: &'static str = "GetSessionInfoResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                18 => {
                    self.device_model = is.read_string()?;
                },
                34 => {
                    self.user_id = ::std::option::Option::Some(is.read_string()?);
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.start_time)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.end_time)?;
                },
                66 => {
                    self.device_id = is.read_string()?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.platform)?;
                },
                82 => {
                    self.os = is.read_string()?;
                },
                90 => {
                    self.os_version = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.device_model.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.device_model);
        }
        if let Some(v) = self.user_id.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(v) = self.start_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.end_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.device_id.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.device_id);
        }
        if let Some(v) = self.platform.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.os.is_empty() {
            my_size += ::protobuf::rt::string_size(10, &self.os);
        }
        if !self.os_version.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.os_version);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.device_model.is_empty() {
            os.write_string(2, &self.device_model)?;
        }
        if let Some(v) = self.user_id.as_ref() {
            os.write_string(4, v)?;
        }
        if let Some(v) = self.start_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.end_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if !self.device_id.is_empty() {
            os.write_string(8, &self.device_id)?;
        }
        if let Some(v) = self.platform.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if !self.os.is_empty() {
            os.write_string(10, &self.os)?;
        }
        if !self.os_version.is_empty() {
            os.write_string(11, &self.os_version)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetSessionInfoResponse {
        GetSessionInfoResponse::new()
    }

    fn clear(&mut self) {
        self.device_model.clear();
        self.user_id = ::std::option::Option::None;
        self.start_time.clear();
        self.end_time.clear();
        self.device_id.clear();
        self.platform.clear();
        self.os.clear();
        self.os_version.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetSessionInfoResponse {
        static instance: GetSessionInfoResponse = GetSessionInfoResponse {
            device_model: ::std::string::String::new(),
            user_id: ::std::option::Option::None,
            start_time: ::protobuf::MessageField::none(),
            end_time: ::protobuf::MessageField::none(),
            device_id: ::std::string::String::new(),
            platform: ::protobuf::MessageField::none(),
            os: ::std::string::String::new(),
            os_version: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetSessionInfoResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetSessionInfoResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetSessionInfoResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetSessionInfoResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n,bitdrift/public/unary/timeline/v1/info.proto\x12!bitdrift.public.unar\
    y.timeline.v1\x1a1bitdrift/public/shared/platform/v1/platform.proto\x1a\
    \x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"A\n\
    \x15GetSessionInfoRequest\x12(\n\nsession_id\x18\x01\x20\x01(\tR\tsessio\
    nIdB\t\xfaB\x06r\x04\x10\x01\x18d\"\xed\x02\n\x16GetSessionInfoResponse\
    \x12!\n\x0cdevice_model\x18\x02\x20\x01(\tR\x0bdeviceModel\x12\x1c\n\x07\
    user_id\x18\x04\x20\x01(\tH\0R\x06userId\x88\x01\x01\x129\n\nstart_time\
    \x18\x05\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\tstartTime\x125\n\
    \x08end_time\x18\x06\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x07end\
    Time\x12\x1b\n\tdevice_id\x18\x08\x20\x01(\tR\x08deviceId\x12H\n\x08plat\
    form\x18\t\x20\x01(\x0b2,.bitdrift.public.shared.platform.v1.PlatformR\
    \x08platform\x12\x0e\n\x02os\x18\n\x20\x01(\tR\x02os\x12\x1d\n\nos_versi\
    on\x18\x0b\x20\x01(\tR\tosVersionB\n\n\x08_user_idJ\xc7\x0b\n\x06\x12\
    \x04\x06\00\x01\n\xb8\x02\n\x01\x0c\x12\x03\x06\0\x12\x1a\xad\x02\x20api\
    \x20-\x20bitdrift's\x20client/server\x20API\x20definitions\n\x20Copyrigh\
    t\x20Bitdrift,\x20Inc.\x20All\x20rights\x20reserved.\n\n\x20Use\x20of\
    \x20this\x20source\x20code\x20and\x20APIs\x20are\x20governed\x20by\x20a\
    \x20source\x20available\x20license\x20that\x20can\x20be\x20found\x20in\n\
    \x20the\x20LICENSE\x20file\x20or\x20at:\n\x20https://polyformproject.org\
    /wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt\n\n\x08\n\x01\x02\
    \x12\x03\x08\0*\n\t\n\x02\x03\0\x12\x03\n\0;\n\t\n\x02\x03\x01\x12\x03\
    \x0b\0)\n\t\n\x02\x03\x02\x12\x03\x0c\0!\n\n\n\x02\x04\0\x12\x04\x0e\0\
    \x14\x01\n\n\n\x03\x04\0\x01\x12\x03\x0e\x08\x1d\n,\n\x04\x04\0\x02\0\
    \x12\x04\x10\x02\x13\x05\x1a\x1e\x20The\x20session\x20ID\x20to\x20query\
    \x20for.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x10\x02\x08\n\x0c\n\x05\
    \x04\0\x02\0\x01\x12\x03\x10\t\x13\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\
    \x10\x16\x17\n\r\n\x05\x04\0\x02\0\x08\x12\x04\x10\x18\x13\x04\n\x10\n\
    \x08\x04\0\x02\0\x08\xaf\x08\x0e\x12\x04\x10\x19\x13\x03\n\n\n\x02\x04\
    \x01\x12\x04\x16\00\x01\n\n\n\x03\x04\x01\x01\x12\x03\x16\x08\x1e\n'\n\
    \x04\x04\x01\x02\0\x12\x03\x18\x02\x1a\x1a\x1a\x20The\x20model\x20of\x20\
    the\x20device.\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x18\x02\x08\n\x0c\
    \n\x05\x04\x01\x02\0\x01\x12\x03\x18\t\x15\n\x0c\n\x05\x04\x01\x02\0\x03\
    \x12\x03\x18\x18\x19\n\xca\x01\n\x04\x04\x01\x02\x01\x12\x03\x1d\x02\x1e\
    \x1a\xbc\x01\x20The\x20user\x20id\x20associated\x20with\x20the\x20sessio\
    n.\n\x20This\x20one\x20is\x20a\x20special\x20case,\x20where\x20we\x20rel\
    y\x20on\x20the\x20SDK\x20being\x20configured\x20to\x20return\x20this.\n\
    \x20There\x20may\x20be\x20other\x20special\x20cases\x20like\x20this\x20i\
    n\x20the\x20future.\n\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03\x1d\x02\n\
    \n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x1d\x0b\x11\n\x0c\n\x05\x04\x01\
    \x02\x01\x01\x12\x03\x1d\x12\x19\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\
    \x1d\x1c\x1d\n-\n\x04\x04\x01\x02\x02\x12\x03\x20\x02,\x1a\x20\x20The\
    \x20start\x20time\x20of\x20the\x20session.\n\n\x0c\n\x05\x04\x01\x02\x02\
    \x06\x12\x03\x20\x02\x1c\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x20\x1d\
    '\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x20*+\n+\n\x04\x04\x01\x02\x03\
    \x12\x03#\x02*\x1a\x1e\x20The\x20end\x20time\x20of\x20the\x20session.\n\
    \n\x0c\n\x05\x04\x01\x02\x03\x06\x12\x03#\x02\x1c\n\x0c\n\x05\x04\x01\
    \x02\x03\x01\x12\x03#\x1d%\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03#()\n9\
    \n\x04\x04\x01\x02\x04\x12\x03&\x02\x17\x1a,\x20The\x20device\x20ID\x20a\
    ssociated\x20with\x20the\x20session.\n\n\x0c\n\x05\x04\x01\x02\x04\x05\
    \x12\x03&\x02\x08\n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x03&\t\x12\n\x0c\n\
    \x05\x04\x01\x02\x04\x03\x12\x03&\x15\x16\nL\n\x04\x04\x01\x02\x05\x12\
    \x03)\x02<\x1a?\x20The\x20platform\x20and\x20app\x20information\x20assoc\
    iated\x20with\x20the\x20session.\n\n\x0c\n\x05\x04\x01\x02\x05\x06\x12\
    \x03)\x02.\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x03)/7\n\x0c\n\x05\x04\
    \x01\x02\x05\x03\x12\x03):;\n2\n\x04\x04\x01\x02\x06\x12\x03,\x02\x11\
    \x1a%\x20The\x20operating\x20system\x20of\x20the\x20device.\n\n\x0c\n\
    \x05\x04\x01\x02\x06\x05\x12\x03,\x02\x08\n\x0c\n\x05\x04\x01\x02\x06\
    \x01\x12\x03,\t\x0b\n\x0c\n\x05\x04\x01\x02\x06\x03\x12\x03,\x0e\x10\nA\
    \n\x04\x04\x01\x02\x07\x12\x03/\x02\x19\x1a4\x20The\x20version\x20of\x20\
    the\x20operating\x20system\x20of\x20the\x20device.\n\n\x0c\n\x05\x04\x01\
    \x02\x07\x05\x12\x03/\x02\x08\n\x0c\n\x05\x04\x01\x02\x07\x01\x12\x03/\t\
    \x13\n\x0c\n\x05\x04\x01\x02\x07\x03\x12\x03/\x16\x18b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::platform::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(GetSessionInfoRequest::generated_message_descriptor_data());
            messages.push(GetSessionInfoResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
