[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-shutdown"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
log.workspace   = true
tokio.workspace = true
