// Generated by generate-response-decoders.py from source-schema descriptors.
use crate as bd_proto_util;
use bd_macros::proto_deserialize;
use bd_proto::protos::bdtail::bdtail_config::DeviceCommandRequest as Proto0;
use bd_proto::protos::workflow::workflow_command::WorkflowCommandSelector as Proto1;

#[proto_deserialize(target = "Proto0")]
struct Decoder0 {
  #[field(id = 1)]
  command_id: String,
  #[field(id = 2)]
  command_selector: protobuf::MessageField<Proto1>,
}
