// Generated by generate-response-decoders.py from source-schema descriptors.
use crate as bd_proto_util;
use bd_macros::proto_deserialize;

#[proto_deserialize(target = "protobuf::well_known_types::duration::Duration")]
struct Decoder45 {
  #[field(id = 1)]
  seconds: i64,
  #[field(id = 2)]
  nanos: i32,
}
