// Generated by generate-response-decoders.py from source-schema descriptors.
use crate as bd_proto_util;
use bd_macros::proto_deserialize;
use bd_proto::protos::logging::payload::Data as Proto5;
use bd_proto::protos::workflow::workflow_command::{
  WellKnownCommandType as Proto6,
  WorkflowCommandSelector as Proto4,
  workflow_command_selector as proto_0,
};
use proto_0::{BuiltinCommand as Proto2, Command_selector as Proto1, RegisteredCommand as Proto3};

#[proto_deserialize(target = "Proto1")]
enum Oneof41_0 {
  #[field(id = 1)]
  BuiltinCommand(Proto2),
  #[field(id = 2)]
  RegisteredCommand(Proto3),
}

#[proto_deserialize(target = "Proto4")]
struct Decoder41 {
  #[field(id = 3)]
  arguments: std::collections::HashMap<String, Proto5>,
  #[field(oneof)]
  command_selector: Option<Proto1>,
}

#[proto_deserialize(target = "Proto2")]
struct Decoder43 {
  #[field(id = 1)]
  type_: protobuf::EnumOrUnknown<Proto6>,
}

#[proto_deserialize(target = "Proto3")]
struct Decoder44 {
  #[field(id = 1)]
  registered_command_id: String,
}
