load("//tools/rust:feature_variants.bzl", "rust_library_with_feature_variants")
load("//tools/rust:tests.bzl", "rust_library_test")

package(default_visibility = ["//visibility:public"])

rust_library_with_feature_variants(
    name = "bd-buffer",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "bd_buffer",
    crate_root = "src/lib.rs",
    edition = "2024",
    feature_variants = {
        "fuzz": {
            "dependency_overrides": {
                "//shared-core/bd-client-stats-store": "//shared-core/bd-client-stats-store:bd-client-stats-store-fuzz",
                "//shared-core/bd-versioned-kv": "//shared-core/bd-versioned-kv:bd-versioned-kv-fuzz",
                "//shared-core/bd-stats-common": "//shared-core/bd-stats-common:bd-stats-common-fuzz",
            },
        },
    },
)

rust_library_test(crate = ":bd-buffer")
