[package]
edition      = "2024"
license-file = "../LICENSE.polyform"
name         = "bd-script"
publish      = false
version      = "1.0.0"

[dependencies]
anyhow.workspace            = true
bd-proto.path               = "../bd-proto"
bd-workspace-hack.workspace = true
flatbuffers.workspace       = true
ordered-float.workspace     = true
ripsaw.workspace            = true
time.workspace              = true

[build-dependencies]
anyhow.workspace     = true
serde_json.workspace = true
