[package]
edition = "2024"
license = "Apache-2.0"
name    = "bd-stats-common"
publish = false
version = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
arbitrary                   = { workspace = true, optional = true }
bd-workspace-hack.workspace = true
sketches-rust.workspace     = true

[features]
fuzzing = ["arbitrary"]
