// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 34.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/debug_files/v1/debug_files.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.debug_files.v1.DebugFileAppScope)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DebugFileAppScope {
    // message fields
    ///  The platform associated with the app build.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFileAppScope.platform)
    pub platform: ::protobuf::EnumOrUnknown<DebugFilePlatform>,
    ///  The application identifier associated with this app scope.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFileAppScope.app_id)
    pub app_id: ::std::string::String,
    ///  The application version associated with this app scope.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFileAppScope.app_version)
    pub app_version: ::std::string::String,
    ///  The application build identifier associated with this app scope.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFileAppScope.app_build_id)
    pub app_build_id: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.debug_files.v1.DebugFileAppScope.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DebugFileAppScope {
    fn default() -> &'a DebugFileAppScope {
        <DebugFileAppScope as ::protobuf::Message>::default_instance()
    }
}

impl DebugFileAppScope {
    pub fn new() -> DebugFileAppScope {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "platform",
            |m: &DebugFileAppScope| { &m.platform },
            |m: &mut DebugFileAppScope| { &mut m.platform },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "app_id",
            |m: &DebugFileAppScope| { &m.app_id },
            |m: &mut DebugFileAppScope| { &mut m.app_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "app_version",
            |m: &DebugFileAppScope| { &m.app_version },
            |m: &mut DebugFileAppScope| { &mut m.app_version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "app_build_id",
            |m: &DebugFileAppScope| { &m.app_build_id },
            |m: &mut DebugFileAppScope| { &mut m.app_build_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DebugFileAppScope>(
            "DebugFileAppScope",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DebugFileAppScope {
    const NAME: &'static str = "DebugFileAppScope";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.platform = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.app_id = is.read_string()?;
                },
                26 => {
                    self.app_version = is.read_string()?;
                },
                34 => {
                    self.app_build_id = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.platform != ::protobuf::EnumOrUnknown::new(DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.platform.value());
        }
        if !self.app_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.app_id);
        }
        if !self.app_version.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.app_version);
        }
        if !self.app_build_id.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.app_build_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.platform != ::protobuf::EnumOrUnknown::new(DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.platform))?;
        }
        if !self.app_id.is_empty() {
            os.write_string(2, &self.app_id)?;
        }
        if !self.app_version.is_empty() {
            os.write_string(3, &self.app_version)?;
        }
        if !self.app_build_id.is_empty() {
            os.write_string(4, &self.app_build_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DebugFileAppScope {
        DebugFileAppScope::new()
    }

    fn clear(&mut self) {
        self.platform = ::protobuf::EnumOrUnknown::new(DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED);
        self.app_id.clear();
        self.app_version.clear();
        self.app_build_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DebugFileAppScope {
        static instance: DebugFileAppScope = DebugFileAppScope {
            platform: ::protobuf::EnumOrUnknown::from_i32(0),
            app_id: ::std::string::String::new(),
            app_version: ::std::string::String::new(),
            app_build_id: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DebugFileAppScope {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DebugFileAppScope").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DebugFileAppScope {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DebugFileAppScope {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListDebugFilesRequest {
    // message fields
    ///  A structured way to provide pagination information.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.pagination)
    pub pagination: ::protobuf::MessageField<super::common::Pagination>,
    ///  Filters debug files by file type.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.type)
    pub type_: ::std::option::Option<::protobuf::EnumOrUnknown<DebugFileType>>,
    ///  Filters debug files by processing state.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.processing_state)
    pub processing_state: ::std::option::Option<::protobuf::EnumOrUnknown<DebugFileProcessingState>>,
    ///  Filters debug files by the uploaded file hash.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.file_hash)
    pub file_hash: ::std::option::Option<::std::string::String>,
    ///  Filters debug files by a matching app scope.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.app_scopes)
    pub app_scopes: ::std::vec::Vec<DebugFileAppScope>,
    ///  Orders debug files by caller-visible attributes. Apply criteria in the order provided.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.sort)
    pub sort: ::std::vec::Vec<list_debug_files_request::Sort>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListDebugFilesRequest {
    fn default() -> &'a ListDebugFilesRequest {
        <ListDebugFilesRequest as ::protobuf::Message>::default_instance()
    }
}

impl ListDebugFilesRequest {
    pub fn new() -> ListDebugFilesRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::common::Pagination>(
            "pagination",
            |m: &ListDebugFilesRequest| { &m.pagination },
            |m: &mut ListDebugFilesRequest| { &mut m.pagination },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "type",
            |m: &ListDebugFilesRequest| { &m.type_ },
            |m: &mut ListDebugFilesRequest| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "processing_state",
            |m: &ListDebugFilesRequest| { &m.processing_state },
            |m: &mut ListDebugFilesRequest| { &mut m.processing_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "file_hash",
            |m: &ListDebugFilesRequest| { &m.file_hash },
            |m: &mut ListDebugFilesRequest| { &mut m.file_hash },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "app_scopes",
            |m: &ListDebugFilesRequest| { &m.app_scopes },
            |m: &mut ListDebugFilesRequest| { &mut m.app_scopes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "sort",
            |m: &ListDebugFilesRequest| { &m.sort },
            |m: &mut ListDebugFilesRequest| { &mut m.sort },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListDebugFilesRequest>(
            "ListDebugFilesRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListDebugFilesRequest {
    const NAME: &'static str = "ListDebugFilesRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pagination)?;
                },
                16 => {
                    self.type_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                24 => {
                    self.processing_state = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                34 => {
                    self.file_hash = ::std::option::Option::Some(is.read_string()?);
                },
                42 => {
                    self.app_scopes.push(is.read_message()?);
                },
                50 => {
                    self.sort.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pagination.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.type_ {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        if let Some(v) = self.processing_state {
            my_size += ::protobuf::rt::int32_size(3, v.value());
        }
        if let Some(v) = self.file_hash.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        for value in &self.app_scopes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.sort {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pagination.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.type_ {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.processing_state {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.file_hash.as_ref() {
            os.write_string(4, v)?;
        }
        for v in &self.app_scopes {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        for v in &self.sort {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListDebugFilesRequest {
        ListDebugFilesRequest::new()
    }

    fn clear(&mut self) {
        self.pagination.clear();
        self.type_ = ::std::option::Option::None;
        self.processing_state = ::std::option::Option::None;
        self.file_hash = ::std::option::Option::None;
        self.app_scopes.clear();
        self.sort.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListDebugFilesRequest {
        static instance: ListDebugFilesRequest = ListDebugFilesRequest {
            pagination: ::protobuf::MessageField::none(),
            type_: ::std::option::Option::None,
            processing_state: ::std::option::Option::None,
            file_hash: ::std::option::Option::None,
            app_scopes: ::std::vec::Vec::new(),
            sort: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListDebugFilesRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListDebugFilesRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListDebugFilesRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListDebugFilesRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ListDebugFilesRequest`
pub mod list_debug_files_request {
    // @@protoc_insertion_point(message:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Sort {
        // message fields
        ///  Selects which caller-visible debug file attribute to order by.
        // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.key)
        pub key: ::protobuf::EnumOrUnknown<sort::SortKey>,
        ///  Selects whether results are returned in ascending or descending order.
        // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.direction)
        pub direction: ::protobuf::EnumOrUnknown<super::super::common::SortDirection>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Sort {
        fn default() -> &'a Sort {
            <Sort as ::protobuf::Message>::default_instance()
        }
    }

    impl Sort {
        pub fn new() -> Sort {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "key",
                |m: &Sort| { &m.key },
                |m: &mut Sort| { &mut m.key },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "direction",
                |m: &Sort| { &m.direction },
                |m: &mut Sort| { &mut m.direction },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Sort>(
                "ListDebugFilesRequest.Sort",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Sort {
        const NAME: &'static str = "Sort";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.key = is.read_enum_or_unknown()?;
                    },
                    16 => {
                        self.direction = is.read_enum_or_unknown()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.key != ::protobuf::EnumOrUnknown::new(sort::SortKey::SORT_KEY_UNSPECIFIED) {
                my_size += ::protobuf::rt::int32_size(1, self.key.value());
            }
            if self.direction != ::protobuf::EnumOrUnknown::new(super::super::common::SortDirection::ASCENDING) {
                my_size += ::protobuf::rt::int32_size(2, self.direction.value());
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.key != ::protobuf::EnumOrUnknown::new(sort::SortKey::SORT_KEY_UNSPECIFIED) {
                os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.key))?;
            }
            if self.direction != ::protobuf::EnumOrUnknown::new(super::super::common::SortDirection::ASCENDING) {
                os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.direction))?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Sort {
            Sort::new()
        }

        fn clear(&mut self) {
            self.key = ::protobuf::EnumOrUnknown::new(sort::SortKey::SORT_KEY_UNSPECIFIED);
            self.direction = ::protobuf::EnumOrUnknown::new(super::super::common::SortDirection::ASCENDING);
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Sort {
            static instance: Sort = Sort {
                key: ::protobuf::EnumOrUnknown::from_i32(0),
                direction: ::protobuf::EnumOrUnknown::from_i32(0),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Sort {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("ListDebugFilesRequest.Sort").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Sort {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Sort {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    /// Nested message and enums of message `Sort`
    pub mod sort {
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.SortKey)
        pub enum SortKey {
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.SortKey.SORT_KEY_UNSPECIFIED)
            SORT_KEY_UNSPECIFIED = 0,
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.SortKey.CREATED_AT)
            CREATED_AT = 1,
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.ListDebugFilesRequest.Sort.SortKey.UPDATED_AT)
            UPDATED_AT = 2,
        }

        impl ::protobuf::Enum for SortKey {
            const NAME: &'static str = "SortKey";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<SortKey> {
                match value {
                    0 => ::std::option::Option::Some(SortKey::SORT_KEY_UNSPECIFIED),
                    1 => ::std::option::Option::Some(SortKey::CREATED_AT),
                    2 => ::std::option::Option::Some(SortKey::UPDATED_AT),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<SortKey> {
                match str {
                    "SORT_KEY_UNSPECIFIED" => ::std::option::Option::Some(SortKey::SORT_KEY_UNSPECIFIED),
                    "CREATED_AT" => ::std::option::Option::Some(SortKey::CREATED_AT),
                    "UPDATED_AT" => ::std::option::Option::Some(SortKey::UPDATED_AT),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [SortKey] = &[
                SortKey::SORT_KEY_UNSPECIFIED,
                SortKey::CREATED_AT,
                SortKey::UPDATED_AT,
            ];
        }

        impl ::protobuf::EnumFull for SortKey {
            fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| super::super::file_descriptor().enum_by_package_relative_name("ListDebugFilesRequest.Sort.SortKey").unwrap()).clone()
            }

            fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
                let index = *self as usize;
                Self::enum_descriptor().value_by_index(index)
            }
        }

        impl ::std::default::Default for SortKey {
            fn default() -> Self {
                SortKey::SORT_KEY_UNSPECIFIED
            }
        }

        impl SortKey {
            pub(in super::super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
                ::protobuf::reflect::GeneratedEnumDescriptorData::new::<SortKey>("ListDebugFilesRequest.Sort.SortKey")
            }
        }
    }
}

// @@protoc_insertion_point(message:bitdrift.public.unary.debug_files.v1.DebugFile)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DebugFile {
    // message fields
    ///  The debug file type.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.type)
    pub type_: ::protobuf::EnumOrUnknown<DebugFileType>,
    ///  The current processing state of the debug file.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.processing_state)
    pub processing_state: ::protobuf::EnumOrUnknown<DebugFileProcessingState>,
    ///  The SHA-256 hash of the uploaded file.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.file_hash)
    pub file_hash: ::std::string::String,
    ///  The time the debug file record was created.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.created_at)
    pub created_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  The time the debug file record was last updated.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.updated_at)
    pub updated_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  The app scopes associated with this debug file.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.DebugFile.app_scopes)
    pub app_scopes: ::std::vec::Vec<DebugFileAppScope>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.debug_files.v1.DebugFile.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DebugFile {
    fn default() -> &'a DebugFile {
        <DebugFile as ::protobuf::Message>::default_instance()
    }
}

impl DebugFile {
    pub fn new() -> DebugFile {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &DebugFile| { &m.type_ },
            |m: &mut DebugFile| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "processing_state",
            |m: &DebugFile| { &m.processing_state },
            |m: &mut DebugFile| { &mut m.processing_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "file_hash",
            |m: &DebugFile| { &m.file_hash },
            |m: &mut DebugFile| { &mut m.file_hash },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "created_at",
            |m: &DebugFile| { &m.created_at },
            |m: &mut DebugFile| { &mut m.created_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "updated_at",
            |m: &DebugFile| { &m.updated_at },
            |m: &mut DebugFile| { &mut m.updated_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "app_scopes",
            |m: &DebugFile| { &m.app_scopes },
            |m: &mut DebugFile| { &mut m.app_scopes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DebugFile>(
            "DebugFile",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DebugFile {
    const NAME: &'static str = "DebugFile";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                24 => {
                    self.processing_state = is.read_enum_or_unknown()?;
                },
                42 => {
                    self.file_hash = is.read_string()?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.created_at)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.updated_at)?;
                },
                74 => {
                    self.app_scopes.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(2, self.type_.value());
        }
        if self.processing_state != ::protobuf::EnumOrUnknown::new(DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(3, self.processing_state.value());
        }
        if !self.file_hash.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.file_hash);
        }
        if let Some(v) = self.created_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.updated_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.app_scopes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if self.processing_state != ::protobuf::EnumOrUnknown::new(DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.processing_state))?;
        }
        if !self.file_hash.is_empty() {
            os.write_string(5, &self.file_hash)?;
        }
        if let Some(v) = self.created_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.updated_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        for v in &self.app_scopes {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DebugFile {
        DebugFile::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED);
        self.processing_state = ::protobuf::EnumOrUnknown::new(DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED);
        self.file_hash.clear();
        self.created_at.clear();
        self.updated_at.clear();
        self.app_scopes.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DebugFile {
        static instance: DebugFile = DebugFile {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            processing_state: ::protobuf::EnumOrUnknown::from_i32(0),
            file_hash: ::std::string::String::new(),
            created_at: ::protobuf::MessageField::none(),
            updated_at: ::protobuf::MessageField::none(),
            app_scopes: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DebugFile {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DebugFile").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DebugFile {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DebugFile {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.debug_files.v1.ListDebugFilesResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListDebugFilesResponse {
    // message fields
    ///  The debug files that matched the request.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesResponse.debug_files)
    pub debug_files: ::std::vec::Vec<DebugFile>,
    ///  The total number of debug files that matched the request.
    // @@protoc_insertion_point(field:bitdrift.public.unary.debug_files.v1.ListDebugFilesResponse.total_count)
    pub total_count: u32,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.debug_files.v1.ListDebugFilesResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListDebugFilesResponse {
    fn default() -> &'a ListDebugFilesResponse {
        <ListDebugFilesResponse as ::protobuf::Message>::default_instance()
    }
}

impl ListDebugFilesResponse {
    pub fn new() -> ListDebugFilesResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "debug_files",
            |m: &ListDebugFilesResponse| { &m.debug_files },
            |m: &mut ListDebugFilesResponse| { &mut m.debug_files },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "total_count",
            |m: &ListDebugFilesResponse| { &m.total_count },
            |m: &mut ListDebugFilesResponse| { &mut m.total_count },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListDebugFilesResponse>(
            "ListDebugFilesResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListDebugFilesResponse {
    const NAME: &'static str = "ListDebugFilesResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.debug_files.push(is.read_message()?);
                },
                16 => {
                    self.total_count = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.debug_files {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.total_count != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.total_count);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.debug_files {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if self.total_count != 0 {
            os.write_uint32(2, self.total_count)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListDebugFilesResponse {
        ListDebugFilesResponse::new()
    }

    fn clear(&mut self) {
        self.debug_files.clear();
        self.total_count = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListDebugFilesResponse {
        static instance: ListDebugFilesResponse = ListDebugFilesResponse {
            debug_files: ::std::vec::Vec::new(),
            total_count: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListDebugFilesResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListDebugFilesResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListDebugFilesResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListDebugFilesResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:bitdrift.public.unary.debug_files.v1.DebugFileType)
pub enum DebugFileType {
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileType.DEBUG_FILE_TYPE_UNSPECIFIED)
    DEBUG_FILE_TYPE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileType.PROGUARD)
    PROGUARD = 1,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileType.DEBUG_FILE)
    DEBUG_FILE = 2,
}

impl ::protobuf::Enum for DebugFileType {
    const NAME: &'static str = "DebugFileType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DebugFileType> {
        match value {
            0 => ::std::option::Option::Some(DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED),
            1 => ::std::option::Option::Some(DebugFileType::PROGUARD),
            2 => ::std::option::Option::Some(DebugFileType::DEBUG_FILE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DebugFileType> {
        match str {
            "DEBUG_FILE_TYPE_UNSPECIFIED" => ::std::option::Option::Some(DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED),
            "PROGUARD" => ::std::option::Option::Some(DebugFileType::PROGUARD),
            "DEBUG_FILE" => ::std::option::Option::Some(DebugFileType::DEBUG_FILE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DebugFileType] = &[
        DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED,
        DebugFileType::PROGUARD,
        DebugFileType::DEBUG_FILE,
    ];
}

impl ::protobuf::EnumFull for DebugFileType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("DebugFileType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for DebugFileType {
    fn default() -> Self {
        DebugFileType::DEBUG_FILE_TYPE_UNSPECIFIED
    }
}

impl DebugFileType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<DebugFileType>("DebugFileType")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:bitdrift.public.unary.debug_files.v1.DebugFileProcessingState)
pub enum DebugFileProcessingState {
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileProcessingState.DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED)
    DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileProcessingState.PENDING)
    PENDING = 1,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileProcessingState.PROCESSED)
    PROCESSED = 2,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFileProcessingState.FAILED)
    FAILED = 3,
}

impl ::protobuf::Enum for DebugFileProcessingState {
    const NAME: &'static str = "DebugFileProcessingState";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DebugFileProcessingState> {
        match value {
            0 => ::std::option::Option::Some(DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED),
            1 => ::std::option::Option::Some(DebugFileProcessingState::PENDING),
            2 => ::std::option::Option::Some(DebugFileProcessingState::PROCESSED),
            3 => ::std::option::Option::Some(DebugFileProcessingState::FAILED),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DebugFileProcessingState> {
        match str {
            "DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED" => ::std::option::Option::Some(DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED),
            "PENDING" => ::std::option::Option::Some(DebugFileProcessingState::PENDING),
            "PROCESSED" => ::std::option::Option::Some(DebugFileProcessingState::PROCESSED),
            "FAILED" => ::std::option::Option::Some(DebugFileProcessingState::FAILED),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DebugFileProcessingState] = &[
        DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED,
        DebugFileProcessingState::PENDING,
        DebugFileProcessingState::PROCESSED,
        DebugFileProcessingState::FAILED,
    ];
}

impl ::protobuf::EnumFull for DebugFileProcessingState {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("DebugFileProcessingState").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for DebugFileProcessingState {
    fn default() -> Self {
        DebugFileProcessingState::DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED
    }
}

impl DebugFileProcessingState {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<DebugFileProcessingState>("DebugFileProcessingState")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:bitdrift.public.unary.debug_files.v1.DebugFilePlatform)
pub enum DebugFilePlatform {
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFilePlatform.DEBUG_FILE_PLATFORM_UNSPECIFIED)
    DEBUG_FILE_PLATFORM_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFilePlatform.APPLE)
    APPLE = 1,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.debug_files.v1.DebugFilePlatform.ANDROID)
    ANDROID = 2,
}

impl ::protobuf::Enum for DebugFilePlatform {
    const NAME: &'static str = "DebugFilePlatform";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DebugFilePlatform> {
        match value {
            0 => ::std::option::Option::Some(DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED),
            1 => ::std::option::Option::Some(DebugFilePlatform::APPLE),
            2 => ::std::option::Option::Some(DebugFilePlatform::ANDROID),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DebugFilePlatform> {
        match str {
            "DEBUG_FILE_PLATFORM_UNSPECIFIED" => ::std::option::Option::Some(DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED),
            "APPLE" => ::std::option::Option::Some(DebugFilePlatform::APPLE),
            "ANDROID" => ::std::option::Option::Some(DebugFilePlatform::ANDROID),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DebugFilePlatform] = &[
        DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED,
        DebugFilePlatform::APPLE,
        DebugFilePlatform::ANDROID,
    ];
}

impl ::protobuf::EnumFull for DebugFilePlatform {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("DebugFilePlatform").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for DebugFilePlatform {
    fn default() -> Self {
        DebugFilePlatform::DEBUG_FILE_PLATFORM_UNSPECIFIED
    }
}

impl DebugFilePlatform {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<DebugFilePlatform>("DebugFilePlatform")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n6bitdrift/public/unary/debug_files/v1/debug_files.proto\x12$bitdrift.p\
    ublic.unary.debug_files.v1\x1a,bitdrift/public/unary/common/v1/common.pr\
    oto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.prot\
    o\"\xf0\x01\n\x11DebugFileAppScope\x12]\n\x08platform\x18\x01\x20\x01(\
    \x0e27.bitdrift.public.unary.debug_files.v1.DebugFilePlatformR\x08platfo\
    rmB\x08\xfaB\x05\x82\x01\x02\x10\x01\x12!\n\x06app_id\x18\x02\x20\x01(\t\
    R\x05appIdB\n\xfaB\x07r\x05\x10\x01\x18\xff\x01\x12+\n\x0bapp_version\
    \x18\x03\x20\x01(\tR\nappVersionB\n\xfaB\x07r\x05\x10\x01\x18\xff\x01\
    \x12,\n\x0capp_build_id\x18\x04\x20\x01(\tR\nappBuildIdB\n\xfaB\x07r\x05\
    \x10\x01\x18\xff\x01\"\xe4\x06\n\x15ListDebugFilesRequest\x12K\n\npagina\
    tion\x18\x01\x20\x01(\x0b2+.bitdrift.public.unary.common.v1.PaginationR\
    \npagination\x12X\n\x04type\x18\x02\x20\x01(\x0e23.bitdrift.public.unary\
    .debug_files.v1.DebugFileTypeH\0R\x04typeB\n\xfaB\x07\x82\x01\x04\x10\
    \x01\x20\0\x88\x01\x01\x12z\n\x10processing_state\x18\x03\x20\x01(\x0e2>\
    .bitdrift.public.unary.debug_files.v1.DebugFileProcessingStateH\x01R\x0f\
    processingStateB\n\xfaB\x07\x82\x01\x04\x10\x01\x20\0\x88\x01\x01\x12,\n\
    \tfile_hash\x18\x04\x20\x01(\tH\x02R\x08fileHashB\n\xfaB\x07r\x05\x10\
    \x01\x18\xff\x01\x88\x01\x01\x12`\n\napp_scopes\x18\x05\x20\x03(\x0b27.b\
    itdrift.public.unary.debug_files.v1.DebugFileAppScopeR\tappScopesB\x08\
    \xfaB\x05\x92\x01\x02\x10d\x12^\n\x04sort\x18\x06\x20\x03(\x0b2@.bitdrif\
    t.public.unary.debug_files.v1.ListDebugFilesRequest.SortR\x04sortB\x08\
    \xfaB\x05\x92\x01\x02\x10\n\x1a\x8b\x02\n\x04Sort\x12f\n\x03key\x18\x01\
    \x20\x01(\x0e2H.bitdrift.public.unary.debug_files.v1.ListDebugFilesReque\
    st.Sort.SortKeyR\x03keyB\n\xfaB\x07\x82\x01\x04\x10\x01\x20\0\x12V\n\tdi\
    rection\x18\x02\x20\x01(\x0e2..bitdrift.public.unary.common.v1.SortDirec\
    tionR\tdirectionB\x08\xfaB\x05\x82\x01\x02\x10\x01\"C\n\x07SortKey\x12\
    \x18\n\x14SORT_KEY_UNSPECIFIED\x10\0\x12\x0e\n\nCREATED_AT\x10\x01\x12\
    \x0e\n\nUPDATED_AT\x10\x02B\x07\n\x05_typeB\x13\n\x11_processing_stateB\
    \x0c\n\n_file_hash\"\xe6\x03\n\tDebugFile\x12Q\n\x04type\x18\x02\x20\x01\
    (\x0e23.bitdrift.public.unary.debug_files.v1.DebugFileTypeR\x04typeB\x08\
    \xfaB\x05\x82\x01\x02\x10\x01\x12s\n\x10processing_state\x18\x03\x20\x01\
    (\x0e2>.bitdrift.public.unary.debug_files.v1.DebugFileProcessingStateR\
    \x0fprocessingStateB\x08\xfaB\x05\x82\x01\x02\x10\x01\x12%\n\tfile_hash\
    \x18\x05\x20\x01(\tR\x08fileHashB\x08\xfaB\x05r\x03\x18\xff\x01\x12C\n\n\
    created_at\x18\x07\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\tcreated\
    AtB\x08\xfaB\x05\x8a\x01\x02\x10\x01\x12C\n\nupdated_at\x18\x08\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\tupdatedAtB\x08\xfaB\x05\x8a\x01\
    \x02\x10\x01\x12`\n\napp_scopes\x18\t\x20\x03(\x0b27.bitdrift.public.una\
    ry.debug_files.v1.DebugFileAppScopeR\tappScopesB\x08\xfaB\x05\x92\x01\
    \x02\x10d\"\x8b\x01\n\x16ListDebugFilesResponse\x12P\n\x0bdebug_files\
    \x18\x01\x20\x03(\x0b2/.bitdrift.public.unary.debug_files.v1.DebugFileR\
    \ndebugFiles\x12\x1f\n\x0btotal_count\x18\x02\x20\x01(\rR\ntotalCount*N\
    \n\rDebugFileType\x12\x1f\n\x1bDEBUG_FILE_TYPE_UNSPECIFIED\x10\0\x12\x0c\
    \n\x08PROGUARD\x10\x01\x12\x0e\n\nDEBUG_FILE\x10\x02*o\n\x18DebugFilePro\
    cessingState\x12+\n'DEBUG_FILE_PROCESSING_STATE_UNSPECIFIED\x10\0\x12\
    \x0b\n\x07PENDING\x10\x01\x12\r\n\tPROCESSED\x10\x02\x12\n\n\x06FAILED\
    \x10\x03*P\n\x11DebugFilePlatform\x12#\n\x1fDEBUG_FILE_PLATFORM_UNSPECIF\
    IED\x10\0\x12\t\n\x05APPLE\x10\x01\x12\x0b\n\x07ANDROID\x10\x02J\xb2\x1f\
    \n\x07\x12\x05\x06\0\x80\x01\x01\n\xb8\x02\n\x01\x0c\x12\x03\x06\0\x12\
    \x1a\xad\x02\x20api\x20-\x20bitdrift's\x20client/server\x20API\x20defini\
    tions\n\x20Copyright\x20Bitdrift,\x20Inc.\x20All\x20rights\x20reserved.\
    \n\n\x20Use\x20of\x20this\x20source\x20code\x20and\x20APIs\x20are\x20gov\
    erned\x20by\x20a\x20source\x20available\x20license\x20that\x20can\x20be\
    \x20found\x20in\n\x20the\x20LICENSE\x20file\x20or\x20at:\n\x20https://po\
    lyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt\n\
    \n\x08\n\x01\x02\x12\x03\x08\0-\n\t\n\x02\x03\0\x12\x03\n\06\n\t\n\x02\
    \x03\x01\x12\x03\x0b\0)\n\t\n\x02\x03\x02\x12\x03\x0c\0!\n\n\n\x02\x05\0\
    \x12\x04\x0e\0\x12\x01\n\n\n\x03\x05\0\x01\x12\x03\x0e\x05\x12\n\x0b\n\
    \x04\x05\0\x02\0\x12\x03\x0f\x02\"\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\
    \x0f\x02\x1d\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x0f\x20!\n\x0b\n\x04\
    \x05\0\x02\x01\x12\x03\x10\x02\x0f\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\
    \x10\x02\n\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x10\r\x0e\n\x0b\n\x04\
    \x05\0\x02\x02\x12\x03\x11\x02\x11\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\
    \x11\x02\x0c\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\x11\x0f\x10\n\n\n\x02\
    \x05\x01\x12\x04\x14\0\x19\x01\n\n\n\x03\x05\x01\x01\x12\x03\x14\x05\x1d\
    \n\x0b\n\x04\x05\x01\x02\0\x12\x03\x15\x02.\n\x0c\n\x05\x05\x01\x02\0\
    \x01\x12\x03\x15\x02)\n\x0c\n\x05\x05\x01\x02\0\x02\x12\x03\x15,-\n\x0b\
    \n\x04\x05\x01\x02\x01\x12\x03\x16\x02\x0e\n\x0c\n\x05\x05\x01\x02\x01\
    \x01\x12\x03\x16\x02\t\n\x0c\n\x05\x05\x01\x02\x01\x02\x12\x03\x16\x0c\r\
    \n\x0b\n\x04\x05\x01\x02\x02\x12\x03\x17\x02\x10\n\x0c\n\x05\x05\x01\x02\
    \x02\x01\x12\x03\x17\x02\x0b\n\x0c\n\x05\x05\x01\x02\x02\x02\x12\x03\x17\
    \x0e\x0f\n\x0b\n\x04\x05\x01\x02\x03\x12\x03\x18\x02\r\n\x0c\n\x05\x05\
    \x01\x02\x03\x01\x12\x03\x18\x02\x08\n\x0c\n\x05\x05\x01\x02\x03\x02\x12\
    \x03\x18\x0b\x0c\n\n\n\x02\x05\x02\x12\x04\x1b\0\x1f\x01\n\n\n\x03\x05\
    \x02\x01\x12\x03\x1b\x05\x16\n\x0b\n\x04\x05\x02\x02\0\x12\x03\x1c\x02&\
    \n\x0c\n\x05\x05\x02\x02\0\x01\x12\x03\x1c\x02!\n\x0c\n\x05\x05\x02\x02\
    \0\x02\x12\x03\x1c$%\n\x0b\n\x04\x05\x02\x02\x01\x12\x03\x1d\x02\x0c\n\
    \x0c\n\x05\x05\x02\x02\x01\x01\x12\x03\x1d\x02\x07\n\x0c\n\x05\x05\x02\
    \x02\x01\x02\x12\x03\x1d\n\x0b\n\x0b\n\x04\x05\x02\x02\x02\x12\x03\x1e\
    \x02\x0e\n\x0c\n\x05\x05\x02\x02\x02\x01\x12\x03\x1e\x02\t\n\x0c\n\x05\
    \x05\x02\x02\x02\x02\x12\x03\x1e\x0c\r\n\n\n\x02\x04\0\x12\x04!\06\x01\n\
    \n\n\x03\x04\0\x01\x12\x03!\x08\x19\n:\n\x04\x04\0\x02\0\x12\x03#\x02v\
    \x1a-\x20The\x20platform\x20associated\x20with\x20the\x20app\x20build.\n\
    \n\x0c\n\x05\x04\0\x02\0\x06\x12\x03#\x029\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03#:B\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03#EF\n\x0c\n\x05\x04\0\x02\
    \0\x08\x12\x03#Gu\n\x0f\n\x08\x04\0\x02\0\x08\xaf\x08\x10\x12\x03#Ht\nJ\
    \n\x04\x04\0\x02\x01\x12\x04&\x02)\x05\x1a<\x20The\x20application\x20ide\
    ntifier\x20associated\x20with\x20this\x20app\x20scope.\n\n\x0c\n\x05\x04\
    \0\x02\x01\x05\x12\x03&\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03&\t\
    \x0f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03&\x12\x13\n\r\n\x05\x04\0\x02\
    \x01\x08\x12\x04&\x14)\x04\n\x10\n\x08\x04\0\x02\x01\x08\xaf\x08\x0e\x12\
    \x04&\x15)\x03\nG\n\x04\x04\0\x02\x02\x12\x04,\x02/\x05\x1a9\x20The\x20a\
    pplication\x20version\x20associated\x20with\x20this\x20app\x20scope.\n\n\
    \x0c\n\x05\x04\0\x02\x02\x05\x12\x03,\x02\x08\n\x0c\n\x05\x04\0\x02\x02\
    \x01\x12\x03,\t\x14\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03,\x17\x18\n\r\n\
    \x05\x04\0\x02\x02\x08\x12\x04,\x19/\x04\n\x10\n\x08\x04\0\x02\x02\x08\
    \xaf\x08\x0e\x12\x04,\x1a/\x03\nP\n\x04\x04\0\x02\x03\x12\x042\x025\x05\
    \x1aB\x20The\x20application\x20build\x20identifier\x20associated\x20with\
    \x20this\x20app\x20scope.\n\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x032\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x032\t\x15\n\x0c\n\x05\x04\0\x02\
    \x03\x03\x12\x032\x18\x19\n\r\n\x05\x04\0\x02\x03\x08\x12\x042\x1a5\x04\
    \n\x10\n\x08\x04\0\x02\x03\x08\xaf\x08\x0e\x12\x042\x1b5\x03\n\n\n\x02\
    \x04\x01\x12\x048\0d\x01\n\n\n\x03\x04\x01\x01\x12\x038\x08\x1d\n\x0c\n\
    \x04\x04\x01\x03\0\x12\x049\x02H\x03\n\x0c\n\x05\x04\x01\x03\0\x01\x12\
    \x039\n\x0e\n\x0e\n\x06\x04\x01\x03\0\x04\0\x12\x04:\x04>\x05\n\x0e\n\
    \x07\x04\x01\x03\0\x04\0\x01\x12\x03:\t\x10\n\x0f\n\x08\x04\x01\x03\0\
    \x04\0\x02\0\x12\x03;\x06\x1f\n\x10\n\t\x04\x01\x03\0\x04\0\x02\0\x01\
    \x12\x03;\x06\x1a\n\x10\n\t\x04\x01\x03\0\x04\0\x02\0\x02\x12\x03;\x1d\
    \x1e\n\x0f\n\x08\x04\x01\x03\0\x04\0\x02\x01\x12\x03<\x06\x15\n\x10\n\t\
    \x04\x01\x03\0\x04\0\x02\x01\x01\x12\x03<\x06\x10\n\x10\n\t\x04\x01\x03\
    \0\x04\0\x02\x01\x02\x12\x03<\x13\x14\n\x0f\n\x08\x04\x01\x03\0\x04\0\
    \x02\x02\x12\x03=\x06\x15\n\x10\n\t\x04\x01\x03\0\x04\0\x02\x02\x01\x12\
    \x03=\x06\x10\n\x10\n\t\x04\x01\x03\0\x04\0\x02\x02\x02\x12\x03=\x13\x14\
    \nP\n\x06\x04\x01\x03\0\x02\0\x12\x04A\x04D\x07\x1a@\x20Selects\x20which\
    \x20caller-visible\x20debug\x20file\x20attribute\x20to\x20order\x20by.\n\
    \n\x0e\n\x07\x04\x01\x03\0\x02\0\x06\x12\x03A\x04L\n\x0e\n\x07\x04\x01\
    \x03\0\x02\0\x01\x12\x03AMP\n\x0e\n\x07\x04\x01\x03\0\x02\0\x03\x12\x03A\
    ST\n\x0f\n\x07\x04\x01\x03\0\x02\0\x08\x12\x04AUD\x06\n\x12\n\n\x04\x01\
    \x03\0\x02\0\x08\xaf\x08\x10\x12\x04AVD\x05\nW\n\x06\x04\x01\x03\0\x02\
    \x01\x12\x03G\x04p\x1aH\x20Selects\x20whether\x20results\x20are\x20retur\
    ned\x20in\x20ascending\x20or\x20descending\x20order.\n\n\x0e\n\x07\x04\
    \x01\x03\0\x02\x01\x06\x12\x03G\x042\n\x0e\n\x07\x04\x01\x03\0\x02\x01\
    \x01\x12\x03G3<\n\x0e\n\x07\x04\x01\x03\0\x02\x01\x03\x12\x03G?@\n\x0e\n\
    \x07\x04\x01\x03\0\x02\x01\x08\x12\x03GAo\n\x11\n\n\x04\x01\x03\0\x02\
    \x01\x08\xaf\x08\x10\x12\x03GBn\nB\n\x04\x04\x01\x02\0\x12\x03K\x02=\x1a\
    5\x20A\x20structured\x20way\x20to\x20provide\x20pagination\x20informatio\
    n.\n\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03K\x02-\n\x0c\n\x05\x04\x01\x02\
    \0\x01\x12\x03K.8\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03K;<\n1\n\x04\x04\
    \x01\x02\x01\x12\x04N\x02Q\x05\x1a#\x20Filters\x20debug\x20files\x20by\
    \x20file\x20type.\n\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03N\x02\n\n\x0c\
    \n\x05\x04\x01\x02\x01\x06\x12\x03N\x0b>\n\x0c\n\x05\x04\x01\x02\x01\x01\
    \x12\x03N?C\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03NFG\n\r\n\x05\x04\x01\
    \x02\x01\x08\x12\x04NHQ\x04\n\x10\n\x08\x04\x01\x02\x01\x08\xaf\x08\x10\
    \x12\x04NIQ\x03\n8\n\x04\x04\x01\x02\x02\x12\x04T\x02W\x05\x1a*\x20Filte\
    rs\x20debug\x20files\x20by\x20processing\x20state.\n\n\x0c\n\x05\x04\x01\
    \x02\x02\x04\x12\x03T\x02\n\n\x0c\n\x05\x04\x01\x02\x02\x06\x12\x03T\x0b\
    I\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03TJZ\n\x0c\n\x05\x04\x01\x02\x02\
    \x03\x12\x03T]^\n\r\n\x05\x04\x01\x02\x02\x08\x12\x04T_W\x04\n\x10\n\x08\
    \x04\x01\x02\x02\x08\xaf\x08\x10\x12\x04T`W\x03\n>\n\x04\x04\x01\x02\x03\
    \x12\x04Z\x02]\x05\x1a0\x20Filters\x20debug\x20files\x20by\x20the\x20upl\
    oaded\x20file\x20hash.\n\n\x0c\n\x05\x04\x01\x02\x03\x04\x12\x03Z\x02\n\
    \n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03Z\x0b\x11\n\x0c\n\x05\x04\x01\
    \x02\x03\x01\x12\x03Z\x12\x1b\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03Z\
    \x1e\x1f\n\r\n\x05\x04\x01\x02\x03\x08\x12\x04Z\x20]\x04\n\x10\n\x08\x04\
    \x01\x02\x03\x08\xaf\x08\x0e\x12\x04Z!]\x03\n<\n\x04\x04\x01\x02\x04\x12\
    \x04`\x02\x81\x01\x1a.\x20Filters\x20debug\x20files\x20by\x20a\x20matchi\
    ng\x20app\x20scope.\n\n\x0c\n\x05\x04\x01\x02\x04\x04\x12\x03`\x02\n\n\
    \x0c\n\x05\x04\x01\x02\x04\x06\x12\x03`\x0bB\n\x0c\n\x05\x04\x01\x02\x04\
    \x01\x12\x03`CM\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x03`PQ\n\r\n\x05\x04\
    \x01\x02\x04\x08\x12\x04`R\x80\x01\n\x0f\n\x08\x04\x01\x02\x04\x08\xaf\
    \x08\x12\x12\x03`S\x7f\nf\n\x04\x04\x01\x02\x05\x12\x04c\x02\x83\x01\x1a\
    X\x20Orders\x20debug\x20files\x20by\x20caller-visible\x20attributes.\x20\
    Apply\x20criteria\x20in\x20the\x20order\x20provided.\n\n\x0c\n\x05\x04\
    \x01\x02\x05\x04\x12\x03c\x02\n\n\x0c\n\x05\x04\x01\x02\x05\x06\x12\x03c\
    \x0bK\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x03cLP\n\x0c\n\x05\x04\x01\x02\
    \x05\x03\x12\x03cST\n\r\n\x05\x04\x01\x02\x05\x08\x12\x04cU\x82\x01\n\
    \x10\n\x08\x04\x01\x02\x05\x08\xaf\x08\x12\x12\x04cV\x81\x01\n\n\n\x02\
    \x04\x02\x12\x04f\0x\x01\n\n\n\x03\x04\x02\x01\x12\x03f\x08\x11\n#\n\x04\
    \x04\x02\x02\0\x12\x03h\x02n\x1a\x16\x20The\x20debug\x20file\x20type.\n\
    \n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03h\x025\n\x0c\n\x05\x04\x02\x02\0\
    \x01\x12\x03h6:\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03h=>\n\x0c\n\x05\x04\
    \x02\x02\0\x08\x12\x03h?m\n\x0f\n\x08\x04\x02\x02\0\x08\xaf\x08\x10\x12\
    \x03h@l\n?\n\x04\x04\x02\x02\x01\x12\x04k\x02\x85\x01\x1a1\x20The\x20cur\
    rent\x20processing\x20state\x20of\x20the\x20debug\x20file.\n\n\x0c\n\x05\
    \x04\x02\x02\x01\x06\x12\x03k\x02@\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\
    \x03kAQ\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03kTU\n\r\n\x05\x04\x02\x02\
    \x01\x08\x12\x04kV\x84\x01\n\x10\n\x08\x04\x02\x02\x01\x08\xaf\x08\x10\
    \x12\x04kW\x83\x01\n5\n\x04\x04\x02\x02\x02\x12\x03n\x02B\x1a(\x20The\
    \x20SHA-256\x20hash\x20of\x20the\x20uploaded\x20file.\n\n\x0c\n\x05\x04\
    \x02\x02\x02\x05\x12\x03n\x02\x08\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\
    \x03n\t\x12\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03n\x15\x16\n\x0c\n\x05\
    \x04\x02\x02\x02\x08\x12\x03n\x17A\n\x0f\n\x08\x04\x02\x02\x02\x08\xaf\
    \x08\x0e\x12\x03n\x18@\n:\n\x04\x04\x02\x02\x03\x12\x03q\x02Z\x1a-\x20Th\
    e\x20time\x20the\x20debug\x20file\x20record\x20was\x20created.\n\n\x0c\n\
    \x05\x04\x02\x02\x03\x06\x12\x03q\x02\x1c\n\x0c\n\x05\x04\x02\x02\x03\
    \x01\x12\x03q\x1d'\n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x03q*+\n\x0c\n\
    \x05\x04\x02\x02\x03\x08\x12\x03q,Y\n\x0f\n\x08\x04\x02\x02\x03\x08\xaf\
    \x08\x11\x12\x03q-X\n?\n\x04\x04\x02\x02\x04\x12\x03t\x02Z\x1a2\x20The\
    \x20time\x20the\x20debug\x20file\x20record\x20was\x20last\x20updated.\n\
    \n\x0c\n\x05\x04\x02\x02\x04\x06\x12\x03t\x02\x1c\n\x0c\n\x05\x04\x02\
    \x02\x04\x01\x12\x03t\x1d'\n\x0c\n\x05\x04\x02\x02\x04\x03\x12\x03t*+\n\
    \x0c\n\x05\x04\x02\x02\x04\x08\x12\x03t,Y\n\x0f\n\x08\x04\x02\x02\x04\
    \x08\xaf\x08\x11\x12\x03t-X\n?\n\x04\x04\x02\x02\x05\x12\x04w\x02\x81\
    \x01\x1a1\x20The\x20app\x20scopes\x20associated\x20with\x20this\x20debug\
    \x20file.\n\n\x0c\n\x05\x04\x02\x02\x05\x04\x12\x03w\x02\n\n\x0c\n\x05\
    \x04\x02\x02\x05\x06\x12\x03w\x0bB\n\x0c\n\x05\x04\x02\x02\x05\x01\x12\
    \x03wCM\n\x0c\n\x05\x04\x02\x02\x05\x03\x12\x03wPQ\n\r\n\x05\x04\x02\x02\
    \x05\x08\x12\x04wR\x80\x01\n\x0f\n\x08\x04\x02\x02\x05\x08\xaf\x08\x12\
    \x12\x03wS\x7f\n\x0b\n\x02\x04\x03\x12\x05z\0\x80\x01\x01\n\n\n\x03\x04\
    \x03\x01\x12\x03z\x08\x1e\n8\n\x04\x04\x03\x02\0\x12\x03|\x02K\x1a+\x20T\
    he\x20debug\x20files\x20that\x20matched\x20the\x20request.\n\n\x0c\n\x05\
    \x04\x03\x02\0\x04\x12\x03|\x02\n\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03|\
    \x0b:\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03|;F\n\x0c\n\x05\x04\x03\x02\0\
    \x03\x12\x03|IJ\nH\n\x04\x04\x03\x02\x01\x12\x03\x7f\x02\x19\x1a;\x20The\
    \x20total\x20number\x20of\x20debug\x20files\x20that\x20matched\x20the\
    \x20request.\n\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x03\x7f\x02\x08\n\x0c\
    \n\x05\x04\x03\x02\x01\x01\x12\x03\x7f\t\x14\n\x0c\n\x05\x04\x03\x02\x01\
    \x03\x12\x03\x7f\x17\x18b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::common::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(DebugFileAppScope::generated_message_descriptor_data());
            messages.push(ListDebugFilesRequest::generated_message_descriptor_data());
            messages.push(DebugFile::generated_message_descriptor_data());
            messages.push(ListDebugFilesResponse::generated_message_descriptor_data());
            messages.push(list_debug_files_request::Sort::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(4);
            enums.push(DebugFileType::generated_enum_descriptor_data());
            enums.push(DebugFileProcessingState::generated_enum_descriptor_data());
            enums.push(DebugFilePlatform::generated_enum_descriptor_data());
            enums.push(list_debug_files_request::sort::SortKey::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
