[package]
edition = "2024"
license = "Apache-2.0"
name    = "bd-pgv"
publish = false
version = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-workspace-hack.workspace = true
log.workspace               = true
protobuf.workspace          = true
protobuf-codegen            = { workspace = true, optional = true }
thiserror.workspace         = true
uuid.workspace              = true

[dev-dependencies]
bd-time           = { path = "../bd-time" }
matches.workspace = true
time.workspace    = true

[features]
codegen = ["dep:protobuf-codegen"]

[build-dependencies]
protobuf-codegen.workspace = true

[[bin]]
name              = "generate_protos"
path              = "src/bin/generate_protos.rs"
required-features = ["codegen"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
