[package]
edition      = "2021"
license-file = "../LICENSE"
name         = "bd-pgv"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
log.workspace       = true
protobuf.workspace  = true
thiserror.workspace = true

[dev-dependencies]
bd-time           = { path = "../bd-time" }
matches.workspace = true
time.workspace    = true

[build-dependencies]
protobuf-codegen.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
