[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-report-writer"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-proto.path               = "../bd-proto"
bd-workspace-hack.workspace = true
flatbuffers.workspace       = true

[build-dependencies]
cbindgen.workspace = true
