// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 34.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/common/v1/common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.common.v1.Owner)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Owner {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.Owner.email)
    pub email: ::std::string::String,
    // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.Owner.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.Owner.name)
    pub name: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.common.v1.Owner.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Owner {
    fn default() -> &'a Owner {
        <Owner as ::protobuf::Message>::default_instance()
    }
}

impl Owner {
    pub fn new() -> Owner {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "email",
            |m: &Owner| { &m.email },
            |m: &mut Owner| { &mut m.email },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Owner| { &m.id },
            |m: &mut Owner| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "name",
            |m: &Owner| { &m.name },
            |m: &mut Owner| { &mut m.name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Owner>(
            "Owner",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Owner {
    const NAME: &'static str = "Owner";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.email = is.read_string()?;
                },
                18 => {
                    self.id = is.read_string()?;
                },
                26 => {
                    self.name = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.email.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.email);
        }
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.id);
        }
        if let Some(v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.email.is_empty() {
            os.write_string(1, &self.email)?;
        }
        if !self.id.is_empty() {
            os.write_string(2, &self.id)?;
        }
        if let Some(v) = self.name.as_ref() {
            os.write_string(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Owner {
        Owner::new()
    }

    fn clear(&mut self) {
        self.email.clear();
        self.id.clear();
        self.name = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Owner {
        static instance: Owner = Owner {
            email: ::std::string::String::new(),
            id: ::std::string::String::new(),
            name: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Owner {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Owner").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Owner {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Owner {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.common.v1.Pagination)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Pagination {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.Pagination.offset)
    pub offset: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.Pagination.limit)
    pub limit: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.common.v1.Pagination.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Pagination {
    fn default() -> &'a Pagination {
        <Pagination as ::protobuf::Message>::default_instance()
    }
}

impl Pagination {
    pub fn new() -> Pagination {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "offset",
            |m: &Pagination| { &m.offset },
            |m: &mut Pagination| { &mut m.offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "limit",
            |m: &Pagination| { &m.limit },
            |m: &mut Pagination| { &mut m.limit },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Pagination>(
            "Pagination",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Pagination {
    const NAME: &'static str = "Pagination";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.offset = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.limit = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.offset {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.limit {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.offset {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.limit {
            os.write_uint32(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Pagination {
        Pagination::new()
    }

    fn clear(&mut self) {
        self.offset = ::std::option::Option::None;
        self.limit = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Pagination {
        static instance: Pagination = Pagination {
            offset: ::std::option::Option::None,
            limit: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Pagination {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Pagination").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Pagination {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Pagination {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.common.v1.TimeRange)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TimeRange {
    // message oneof groups
    pub time_range_type: ::std::option::Option<time_range::Time_range_type>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.common.v1.TimeRange.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TimeRange {
    fn default() -> &'a TimeRange {
        <TimeRange as ::protobuf::Message>::default_instance()
    }
}

impl TimeRange {
    pub fn new() -> TimeRange {
        ::std::default::Default::default()
    }

    // .bitdrift.public.unary.common.v1.TimeRange.FixedTimeRange fixed_time_range = 1;

    pub fn fixed_time_range(&self) -> &time_range::FixedTimeRange {
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(ref v)) => v,
            _ => <time_range::FixedTimeRange as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_fixed_time_range(&mut self) {
        self.time_range_type = ::std::option::Option::None;
    }

    pub fn has_fixed_time_range(&self) -> bool {
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_fixed_time_range(&mut self, v: time_range::FixedTimeRange) {
        self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(v))
    }

    // Mutable pointer to the field.
    pub fn mut_fixed_time_range(&mut self) -> &mut time_range::FixedTimeRange {
        if let ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(_)) = self.time_range_type {
        } else {
            self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(time_range::FixedTimeRange::new()));
        }
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_fixed_time_range(&mut self) -> time_range::FixedTimeRange {
        if self.has_fixed_time_range() {
            match self.time_range_type.take() {
                ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(v)) => v,
                _ => panic!(),
            }
        } else {
            time_range::FixedTimeRange::new()
        }
    }

    // .bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRange relative_time_range = 2;

    pub fn relative_time_range(&self) -> &time_range::RelativeTimeRange {
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(ref v)) => v,
            _ => <time_range::RelativeTimeRange as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_relative_time_range(&mut self) {
        self.time_range_type = ::std::option::Option::None;
    }

    pub fn has_relative_time_range(&self) -> bool {
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_relative_time_range(&mut self, v: time_range::RelativeTimeRange) {
        self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(v))
    }

    // Mutable pointer to the field.
    pub fn mut_relative_time_range(&mut self) -> &mut time_range::RelativeTimeRange {
        if let ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(_)) = self.time_range_type {
        } else {
            self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(time_range::RelativeTimeRange::new()));
        }
        match self.time_range_type {
            ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_relative_time_range(&mut self) -> time_range::RelativeTimeRange {
        if self.has_relative_time_range() {
            match self.time_range_type.take() {
                ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(v)) => v,
                _ => panic!(),
            }
        } else {
            time_range::RelativeTimeRange::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, time_range::FixedTimeRange>(
            "fixed_time_range",
            TimeRange::has_fixed_time_range,
            TimeRange::fixed_time_range,
            TimeRange::mut_fixed_time_range,
            TimeRange::set_fixed_time_range,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, time_range::RelativeTimeRange>(
            "relative_time_range",
            TimeRange::has_relative_time_range,
            TimeRange::relative_time_range,
            TimeRange::mut_relative_time_range,
            TimeRange::set_relative_time_range,
        ));
        oneofs.push(time_range::Time_range_type::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TimeRange>(
            "TimeRange",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TimeRange {
    const NAME: &'static str = "TimeRange";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::FixedTimeRange(is.read_message()?));
                },
                18 => {
                    self.time_range_type = ::std::option::Option::Some(time_range::Time_range_type::RelativeTimeRange(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.time_range_type {
            match v {
                &time_range::Time_range_type::FixedTimeRange(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &time_range::Time_range_type::RelativeTimeRange(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.time_range_type {
            match v {
                &time_range::Time_range_type::FixedTimeRange(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &time_range::Time_range_type::RelativeTimeRange(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TimeRange {
        TimeRange::new()
    }

    fn clear(&mut self) {
        self.time_range_type = ::std::option::Option::None;
        self.time_range_type = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TimeRange {
        static instance: TimeRange = TimeRange {
            time_range_type: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TimeRange {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TimeRange").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TimeRange {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TimeRange {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `TimeRange`
pub mod time_range {

    #[derive(Clone,PartialEq,Debug)]
    // @@protoc_insertion_point(oneof:bitdrift.public.unary.common.v1.TimeRange.time_range_type)
    pub enum Time_range_type {
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.common.v1.TimeRange.fixed_time_range)
        FixedTimeRange(FixedTimeRange),
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.common.v1.TimeRange.relative_time_range)
        RelativeTimeRange(RelativeTimeRange),
    }

    impl ::protobuf::Oneof for Time_range_type {
    }

    impl ::protobuf::OneofFull for Time_range_type {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::TimeRange as ::protobuf::MessageFull>::descriptor().oneof_by_name("time_range_type").unwrap()).clone()
        }
    }

    impl Time_range_type {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Time_range_type>("time_range_type")
        }
    }
    // @@protoc_insertion_point(message:bitdrift.public.unary.common.v1.TimeRange.FixedTimeRange)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct FixedTimeRange {
        // message fields
        // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.TimeRange.FixedTimeRange.start_time)
        pub start_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
        // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.TimeRange.FixedTimeRange.end_time)
        pub end_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.common.v1.TimeRange.FixedTimeRange.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a FixedTimeRange {
        fn default() -> &'a FixedTimeRange {
            <FixedTimeRange as ::protobuf::Message>::default_instance()
        }
    }

    impl FixedTimeRange {
        pub fn new() -> FixedTimeRange {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
                "start_time",
                |m: &FixedTimeRange| { &m.start_time },
                |m: &mut FixedTimeRange| { &mut m.start_time },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
                "end_time",
                |m: &FixedTimeRange| { &m.end_time },
                |m: &mut FixedTimeRange| { &mut m.end_time },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FixedTimeRange>(
                "TimeRange.FixedTimeRange",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for FixedTimeRange {
        const NAME: &'static str = "FixedTimeRange";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.start_time)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.end_time)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.start_time.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.end_time.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.start_time.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.end_time.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> FixedTimeRange {
            FixedTimeRange::new()
        }

        fn clear(&mut self) {
            self.start_time.clear();
            self.end_time.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static FixedTimeRange {
            static instance: FixedTimeRange = FixedTimeRange {
                start_time: ::protobuf::MessageField::none(),
                end_time: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for FixedTimeRange {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("TimeRange.FixedTimeRange").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for FixedTimeRange {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for FixedTimeRange {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    // @@protoc_insertion_point(message:bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRange)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct RelativeTimeRange {
        // message fields
        // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRange.duration)
        pub duration: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
        // @@protoc_insertion_point(field:bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRange.offset)
        pub offset: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRange.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a RelativeTimeRange {
        fn default() -> &'a RelativeTimeRange {
            <RelativeTimeRange as ::protobuf::Message>::default_instance()
        }
    }

    impl RelativeTimeRange {
        pub fn new() -> RelativeTimeRange {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
                "duration",
                |m: &RelativeTimeRange| { &m.duration },
                |m: &mut RelativeTimeRange| { &mut m.duration },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
                "offset",
                |m: &RelativeTimeRange| { &m.offset },
                |m: &mut RelativeTimeRange| { &mut m.offset },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RelativeTimeRange>(
                "TimeRange.RelativeTimeRange",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for RelativeTimeRange {
        const NAME: &'static str = "RelativeTimeRange";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.duration)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.offset)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.duration.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.offset.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.duration.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.offset.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> RelativeTimeRange {
            RelativeTimeRange::new()
        }

        fn clear(&mut self) {
            self.duration.clear();
            self.offset.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static RelativeTimeRange {
            static instance: RelativeTimeRange = RelativeTimeRange {
                duration: ::protobuf::MessageField::none(),
                offset: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for RelativeTimeRange {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("TimeRange.RelativeTimeRange").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for RelativeTimeRange {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for RelativeTimeRange {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:bitdrift.public.unary.common.v1.SortDirection)
pub enum SortDirection {
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.SortDirection.ASCENDING)
    ASCENDING = 0,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.SortDirection.DESCENDING)
    DESCENDING = 1,
}

impl ::protobuf::Enum for SortDirection {
    const NAME: &'static str = "SortDirection";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SortDirection> {
        match value {
            0 => ::std::option::Option::Some(SortDirection::ASCENDING),
            1 => ::std::option::Option::Some(SortDirection::DESCENDING),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<SortDirection> {
        match str {
            "ASCENDING" => ::std::option::Option::Some(SortDirection::ASCENDING),
            "DESCENDING" => ::std::option::Option::Some(SortDirection::DESCENDING),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [SortDirection] = &[
        SortDirection::ASCENDING,
        SortDirection::DESCENDING,
    ];
}

impl ::protobuf::EnumFull for SortDirection {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("SortDirection").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for SortDirection {
    fn default() -> Self {
        SortDirection::ASCENDING
    }
}

impl SortDirection {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<SortDirection>("SortDirection")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:bitdrift.public.unary.common.v1.Operator)
pub enum Operator {
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.EQUAL)
    EQUAL = 0,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.NOT_EQUAL)
    NOT_EQUAL = 1,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.GREATER_THAN)
    GREATER_THAN = 2,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.GREATER_THAN_OR_EQUAL)
    GREATER_THAN_OR_EQUAL = 3,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.LESS_THAN)
    LESS_THAN = 4,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.LESS_THAN_OR_EQUAL)
    LESS_THAN_OR_EQUAL = 5,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.WILDCARD)
    WILDCARD = 6,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.NOT_WILDCARD)
    NOT_WILDCARD = 7,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.IN)
    IN = 9,
    // @@protoc_insertion_point(enum_value:bitdrift.public.unary.common.v1.Operator.NOT_IN)
    NOT_IN = 10,
}

impl ::protobuf::Enum for Operator {
    const NAME: &'static str = "Operator";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Operator> {
        match value {
            0 => ::std::option::Option::Some(Operator::EQUAL),
            1 => ::std::option::Option::Some(Operator::NOT_EQUAL),
            2 => ::std::option::Option::Some(Operator::GREATER_THAN),
            3 => ::std::option::Option::Some(Operator::GREATER_THAN_OR_EQUAL),
            4 => ::std::option::Option::Some(Operator::LESS_THAN),
            5 => ::std::option::Option::Some(Operator::LESS_THAN_OR_EQUAL),
            6 => ::std::option::Option::Some(Operator::WILDCARD),
            7 => ::std::option::Option::Some(Operator::NOT_WILDCARD),
            9 => ::std::option::Option::Some(Operator::IN),
            10 => ::std::option::Option::Some(Operator::NOT_IN),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Operator> {
        match str {
            "EQUAL" => ::std::option::Option::Some(Operator::EQUAL),
            "NOT_EQUAL" => ::std::option::Option::Some(Operator::NOT_EQUAL),
            "GREATER_THAN" => ::std::option::Option::Some(Operator::GREATER_THAN),
            "GREATER_THAN_OR_EQUAL" => ::std::option::Option::Some(Operator::GREATER_THAN_OR_EQUAL),
            "LESS_THAN" => ::std::option::Option::Some(Operator::LESS_THAN),
            "LESS_THAN_OR_EQUAL" => ::std::option::Option::Some(Operator::LESS_THAN_OR_EQUAL),
            "WILDCARD" => ::std::option::Option::Some(Operator::WILDCARD),
            "NOT_WILDCARD" => ::std::option::Option::Some(Operator::NOT_WILDCARD),
            "IN" => ::std::option::Option::Some(Operator::IN),
            "NOT_IN" => ::std::option::Option::Some(Operator::NOT_IN),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Operator] = &[
        Operator::EQUAL,
        Operator::NOT_EQUAL,
        Operator::GREATER_THAN,
        Operator::GREATER_THAN_OR_EQUAL,
        Operator::LESS_THAN,
        Operator::LESS_THAN_OR_EQUAL,
        Operator::WILDCARD,
        Operator::NOT_WILDCARD,
        Operator::IN,
        Operator::NOT_IN,
    ];
}

impl ::protobuf::EnumFull for Operator {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Operator").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            Operator::EQUAL => 0,
            Operator::NOT_EQUAL => 1,
            Operator::GREATER_THAN => 2,
            Operator::GREATER_THAN_OR_EQUAL => 3,
            Operator::LESS_THAN => 4,
            Operator::LESS_THAN_OR_EQUAL => 5,
            Operator::WILDCARD => 6,
            Operator::NOT_WILDCARD => 7,
            Operator::IN => 8,
            Operator::NOT_IN => 9,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Operator {
    fn default() -> Self {
        Operator::EQUAL
    }
}

impl Operator {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Operator>("Operator")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n,bitdrift/public/unary/common/v1/common.proto\x12\x1fbitdrift.public.u\
    nary.common.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/proto\
    buf/timestamp.proto\x1a\x17validate/validate.proto\"k\n\x05Owner\x12\x1e\
    \n\x05email\x18\x01\x20\x01(\tR\x05emailB\x08\xfaB\x05r\x03\x18\xff\x01\
    \x12\x17\n\x02id\x18\x02\x20\x01(\tR\x02idB\x07\xfaB\x04r\x02\x18d\x12\
    \x20\n\x04name\x18\x03\x20\x01(\tH\0R\x04nameB\x07\xfaB\x04r\x02\x18d\
    \x88\x01\x01B\x07\n\x05_name\"d\n\nPagination\x12\x1b\n\x06offset\x18\
    \x01\x20\x01(\rH\0R\x06offset\x88\x01\x01\x12$\n\x05limit\x18\x02\x20\
    \x01(\rH\x01R\x05limitB\t\xfaB\x06*\x04\x18d\x20\0\x88\x01\x01B\t\n\x07_\
    offsetB\x08\n\x06_limit\"\x9d\x04\n\tTimeRange\x12e\n\x10fixed_time_rang\
    e\x18\x01\x20\x01(\x0b29.bitdrift.public.unary.common.v1.TimeRange.Fixed\
    TimeRangeH\0R\x0efixedTimeRange\x12n\n\x13relative_time_range\x18\x02\
    \x20\x01(\x0b2<.bitdrift.public.unary.common.v1.TimeRange.RelativeTimeRa\
    ngeH\0R\x11relativeTimeRange\x1a\x96\x01\n\x0eFixedTimeRange\x12C\n\nsta\
    rt_time\x18\x01\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\tstartTimeB\
    \x08\xfaB\x05\x8a\x01\x02\x10\x01\x12?\n\x08end_time\x18\x02\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\x07endTimeB\x08\xfaB\x05\x8a\x01\
    \x02\x10\x01\x1a\x87\x01\n\x11RelativeTimeRange\x12?\n\x08duration\x18\
    \x01\x20\x01(\x0b2\x19.google.protobuf.DurationR\x08durationB\x08\xfaB\
    \x05\x8a\x01\x02\x10\x01\x121\n\x06offset\x18\x02\x20\x01(\x0b2\x19.goog\
    le.protobuf.DurationR\x06offsetB\x16\n\x0ftime_range_type\x12\x03\xf8B\
    \x01*.\n\rSortDirection\x12\r\n\tASCENDING\x10\0\x12\x0e\n\nDESCENDING\
    \x10\x01*\xac\x01\n\x08Operator\x12\t\n\x05EQUAL\x10\0\x12\r\n\tNOT_EQUA\
    L\x10\x01\x12\x10\n\x0cGREATER_THAN\x10\x02\x12\x19\n\x15GREATER_THAN_OR\
    _EQUAL\x10\x03\x12\r\n\tLESS_THAN\x10\x04\x12\x16\n\x12LESS_THAN_OR_EQUA\
    L\x10\x05\x12\x0c\n\x08WILDCARD\x10\x06\x12\x10\n\x0cNOT_WILDCARD\x10\
    \x07\x12\x06\n\x02IN\x10\t\x12\n\n\x06NOT_IN\x10\nb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(::protobuf::well_known_types::duration::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(Owner::generated_message_descriptor_data());
            messages.push(Pagination::generated_message_descriptor_data());
            messages.push(TimeRange::generated_message_descriptor_data());
            messages.push(time_range::FixedTimeRange::generated_message_descriptor_data());
            messages.push(time_range::RelativeTimeRange::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(SortDirection::generated_enum_descriptor_data());
            enums.push(Operator::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
