// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 34.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/health/v1/health.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.health.v1.GetSystemStatusRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetSystemStatusRequest {
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.health.v1.GetSystemStatusRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetSystemStatusRequest {
    fn default() -> &'a GetSystemStatusRequest {
        <GetSystemStatusRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetSystemStatusRequest {
    pub fn new() -> GetSystemStatusRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetSystemStatusRequest>(
            "GetSystemStatusRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetSystemStatusRequest {
    const NAME: &'static str = "GetSystemStatusRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetSystemStatusRequest {
        GetSystemStatusRequest::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetSystemStatusRequest {
        static instance: GetSystemStatusRequest = GetSystemStatusRequest {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetSystemStatusRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetSystemStatusRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetSystemStatusRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetSystemStatusRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.health.v1.GetSystemStatusResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetSystemStatusResponse {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.health.v1.GetSystemStatusResponse.connected_clients)
    pub connected_clients: u64,
    // @@protoc_insertion_point(field:bitdrift.public.unary.health.v1.GetSystemStatusResponse.metrics_ingestion_delay)
    pub metrics_ingestion_delay: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.health.v1.GetSystemStatusResponse.issues_ingestion_delay)
    pub issues_ingestion_delay: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.health.v1.GetSystemStatusResponse.logs_ingestion_delay)
    pub logs_ingestion_delay: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.health.v1.GetSystemStatusResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetSystemStatusResponse {
    fn default() -> &'a GetSystemStatusResponse {
        <GetSystemStatusResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetSystemStatusResponse {
    pub fn new() -> GetSystemStatusResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connected_clients",
            |m: &GetSystemStatusResponse| { &m.connected_clients },
            |m: &mut GetSystemStatusResponse| { &mut m.connected_clients },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
            "metrics_ingestion_delay",
            |m: &GetSystemStatusResponse| { &m.metrics_ingestion_delay },
            |m: &mut GetSystemStatusResponse| { &mut m.metrics_ingestion_delay },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
            "issues_ingestion_delay",
            |m: &GetSystemStatusResponse| { &m.issues_ingestion_delay },
            |m: &mut GetSystemStatusResponse| { &mut m.issues_ingestion_delay },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
            "logs_ingestion_delay",
            |m: &GetSystemStatusResponse| { &m.logs_ingestion_delay },
            |m: &mut GetSystemStatusResponse| { &mut m.logs_ingestion_delay },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetSystemStatusResponse>(
            "GetSystemStatusResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetSystemStatusResponse {
    const NAME: &'static str = "GetSystemStatusResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connected_clients = is.read_uint64()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.metrics_ingestion_delay)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.issues_ingestion_delay)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.logs_ingestion_delay)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.connected_clients != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.connected_clients);
        }
        if let Some(v) = self.metrics_ingestion_delay.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.issues_ingestion_delay.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.logs_ingestion_delay.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.connected_clients != 0 {
            os.write_uint64(1, self.connected_clients)?;
        }
        if let Some(v) = self.metrics_ingestion_delay.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.issues_ingestion_delay.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.logs_ingestion_delay.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetSystemStatusResponse {
        GetSystemStatusResponse::new()
    }

    fn clear(&mut self) {
        self.connected_clients = 0;
        self.metrics_ingestion_delay.clear();
        self.issues_ingestion_delay.clear();
        self.logs_ingestion_delay.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetSystemStatusResponse {
        static instance: GetSystemStatusResponse = GetSystemStatusResponse {
            connected_clients: 0,
            metrics_ingestion_delay: ::protobuf::MessageField::none(),
            issues_ingestion_delay: ::protobuf::MessageField::none(),
            logs_ingestion_delay: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetSystemStatusResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetSystemStatusResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetSystemStatusResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetSystemStatusResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n,bitdrift/public/unary/health/v1/health.proto\x12\x1fbitdrift.public.u\
    nary.health.v1\x1a\x1egoogle/protobuf/duration.proto\"\x18\n\x16GetSyste\
    mStatusRequest\"\xb7\x02\n\x17GetSystemStatusResponse\x12+\n\x11connecte\
    d_clients\x18\x01\x20\x01(\x04R\x10connectedClients\x12Q\n\x17metrics_in\
    gestion_delay\x18\x02\x20\x01(\x0b2\x19.google.protobuf.DurationR\x15met\
    ricsIngestionDelay\x12O\n\x16issues_ingestion_delay\x18\x03\x20\x01(\x0b\
    2\x19.google.protobuf.DurationR\x14issuesIngestionDelay\x12K\n\x14logs_i\
    ngestion_delay\x18\x04\x20\x01(\x0b2\x19.google.protobuf.DurationR\x12lo\
    gsIngestionDelay2\x96\x01\n\rHealthService\x12\x84\x01\n\x0fGetSystemSta\
    tus\x127.bitdrift.public.unary.health.v1.GetSystemStatusRequest\x1a8.bit\
    drift.public.unary.health.v1.GetSystemStatusResponseb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::well_known_types::duration::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(GetSystemStatusRequest::generated_message_descriptor_data());
            messages.push(GetSystemStatusResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
