// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 35.0
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/timeline/v1/spans.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.Span)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Span {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.started_at)
    pub started_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.finished_at)
    pub finished_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.parent_id)
    pub parent_id: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.Span.fields)
    pub fields: ::protobuf::MessageField<super::logs::log::LogFields>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.Span.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Span {
    fn default() -> &'a Span {
        <Span as ::protobuf::Message>::default_instance()
    }
}

impl Span {
    pub fn new() -> Span {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Span| { &m.id },
            |m: &mut Span| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "started_at",
            |m: &Span| { &m.started_at },
            |m: &mut Span| { &mut m.started_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "finished_at",
            |m: &Span| { &m.finished_at },
            |m: &mut Span| { &mut m.finished_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &Span| { &m.name },
            |m: &mut Span| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "parent_id",
            |m: &Span| { &m.parent_id },
            |m: &mut Span| { &mut m.parent_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::logs::log::LogFields>(
            "fields",
            |m: &Span| { &m.fields },
            |m: &mut Span| { &mut m.fields },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Span>(
            "Span",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Span {
    const NAME: &'static str = "Span";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.started_at)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.finished_at)?;
                },
                34 => {
                    self.name = is.read_string()?;
                },
                42 => {
                    self.parent_id = ::std::option::Option::Some(is.read_string()?);
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.fields)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if let Some(v) = self.started_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.finished_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.name);
        }
        if let Some(v) = self.parent_id.as_ref() {
            my_size += ::protobuf::rt::string_size(5, &v);
        }
        if let Some(v) = self.fields.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if let Some(v) = self.started_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.finished_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if !self.name.is_empty() {
            os.write_string(4, &self.name)?;
        }
        if let Some(v) = self.parent_id.as_ref() {
            os.write_string(5, v)?;
        }
        if let Some(v) = self.fields.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Span {
        Span::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.started_at.clear();
        self.finished_at.clear();
        self.name.clear();
        self.parent_id = ::std::option::Option::None;
        self.fields.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Span {
        static instance: Span = Span {
            id: ::std::string::String::new(),
            started_at: ::protobuf::MessageField::none(),
            finished_at: ::protobuf::MessageField::none(),
            name: ::std::string::String::new(),
            parent_id: ::std::option::Option::None,
            fields: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Span {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Span").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Span {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Span {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SessionSearchSpanRequest {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.session_id)
    pub session_id: ::std::string::String,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.filters)
    pub filters: ::std::vec::Vec<session_search_span_request::Filter>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.max_depth)
    pub max_depth: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.page)
    pub page: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.per_page)
    pub per_page: ::std::option::Option<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SessionSearchSpanRequest {
    fn default() -> &'a SessionSearchSpanRequest {
        <SessionSearchSpanRequest as ::protobuf::Message>::default_instance()
    }
}

impl SessionSearchSpanRequest {
    pub fn new() -> SessionSearchSpanRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "session_id",
            |m: &SessionSearchSpanRequest| { &m.session_id },
            |m: &mut SessionSearchSpanRequest| { &mut m.session_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "filters",
            |m: &SessionSearchSpanRequest| { &m.filters },
            |m: &mut SessionSearchSpanRequest| { &mut m.filters },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "max_depth",
            |m: &SessionSearchSpanRequest| { &m.max_depth },
            |m: &mut SessionSearchSpanRequest| { &mut m.max_depth },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "page",
            |m: &SessionSearchSpanRequest| { &m.page },
            |m: &mut SessionSearchSpanRequest| { &mut m.page },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "per_page",
            |m: &SessionSearchSpanRequest| { &m.per_page },
            |m: &mut SessionSearchSpanRequest| { &mut m.per_page },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SessionSearchSpanRequest>(
            "SessionSearchSpanRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SessionSearchSpanRequest {
    const NAME: &'static str = "SessionSearchSpanRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.session_id = is.read_string()?;
                },
                18 => {
                    self.filters.push(is.read_message()?);
                },
                24 => {
                    self.max_depth = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.page = ::std::option::Option::Some(is.read_uint64()?);
                },
                40 => {
                    self.per_page = ::std::option::Option::Some(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.session_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.session_id);
        }
        for value in &self.filters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.max_depth {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.page {
            my_size += ::protobuf::rt::uint64_size(4, v);
        }
        if let Some(v) = self.per_page {
            my_size += ::protobuf::rt::uint64_size(5, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.session_id.is_empty() {
            os.write_string(1, &self.session_id)?;
        }
        for v in &self.filters {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.max_depth {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.page {
            os.write_uint64(4, v)?;
        }
        if let Some(v) = self.per_page {
            os.write_uint64(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SessionSearchSpanRequest {
        SessionSearchSpanRequest::new()
    }

    fn clear(&mut self) {
        self.session_id.clear();
        self.filters.clear();
        self.max_depth = ::std::option::Option::None;
        self.page = ::std::option::Option::None;
        self.per_page = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SessionSearchSpanRequest {
        static instance: SessionSearchSpanRequest = SessionSearchSpanRequest {
            session_id: ::std::string::String::new(),
            filters: ::std::vec::Vec::new(),
            max_depth: ::std::option::Option::None,
            page: ::std::option::Option::None,
            per_page: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SessionSearchSpanRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SessionSearchSpanRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SessionSearchSpanRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SessionSearchSpanRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `SessionSearchSpanRequest`
pub mod session_search_span_request {
    // @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Filter {
        // message fields
        // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.operator)
        pub operator: ::protobuf::EnumOrUnknown<filter::Operator>,
        // message oneof groups
        pub filter: ::std::option::Option<filter::Filter>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Filter {
        fn default() -> &'a Filter {
            <Filter as ::protobuf::Message>::default_instance()
        }
    }

    impl Filter {
        pub fn new() -> Filter {
            ::std::default::Default::default()
        }

        // string span_name = 1;

        pub fn span_name(&self) -> &str {
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanName(ref v)) => v,
                _ => "",
            }
        }

        pub fn clear_span_name(&mut self) {
            self.filter = ::std::option::Option::None;
        }

        pub fn has_span_name(&self) -> bool {
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanName(..)) => true,
                _ => false,
            }
        }

        // Param is passed by value, moved
        pub fn set_span_name(&mut self, v: ::std::string::String) {
            self.filter = ::std::option::Option::Some(filter::Filter::SpanName(v))
        }

        // Mutable pointer to the field.
        pub fn mut_span_name(&mut self) -> &mut ::std::string::String {
            if let ::std::option::Option::Some(filter::Filter::SpanName(_)) = self.filter {
            } else {
                self.filter = ::std::option::Option::Some(filter::Filter::SpanName(::std::string::String::new()));
            }
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanName(ref mut v)) => v,
                _ => panic!(),
            }
        }

        // Take field
        pub fn take_span_name(&mut self) -> ::std::string::String {
            if self.has_span_name() {
                match self.filter.take() {
                    ::std::option::Option::Some(filter::Filter::SpanName(v)) => v,
                    _ => panic!(),
                }
            } else {
                ::std::string::String::new()
            }
        }

        // string span_id = 2;

        pub fn span_id(&self) -> &str {
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanId(ref v)) => v,
                _ => "",
            }
        }

        pub fn clear_span_id(&mut self) {
            self.filter = ::std::option::Option::None;
        }

        pub fn has_span_id(&self) -> bool {
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanId(..)) => true,
                _ => false,
            }
        }

        // Param is passed by value, moved
        pub fn set_span_id(&mut self, v: ::std::string::String) {
            self.filter = ::std::option::Option::Some(filter::Filter::SpanId(v))
        }

        // Mutable pointer to the field.
        pub fn mut_span_id(&mut self) -> &mut ::std::string::String {
            if let ::std::option::Option::Some(filter::Filter::SpanId(_)) = self.filter {
            } else {
                self.filter = ::std::option::Option::Some(filter::Filter::SpanId(::std::string::String::new()));
            }
            match self.filter {
                ::std::option::Option::Some(filter::Filter::SpanId(ref mut v)) => v,
                _ => panic!(),
            }
        }

        // Take field
        pub fn take_span_id(&mut self) -> ::std::string::String {
            if self.has_span_id() {
                match self.filter.take() {
                    ::std::option::Option::Some(filter::Filter::SpanId(v)) => v,
                    _ => panic!(),
                }
            } else {
                ::std::string::String::new()
            }
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(3);
            let mut oneofs = ::std::vec::Vec::with_capacity(1);
            fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
                "span_name",
                Filter::has_span_name,
                Filter::span_name,
                Filter::set_span_name,
            ));
            fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
                "span_id",
                Filter::has_span_id,
                Filter::span_id,
                Filter::set_span_id,
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "operator",
                |m: &Filter| { &m.operator },
                |m: &mut Filter| { &mut m.operator },
            ));
            oneofs.push(filter::Filter::generated_oneof_descriptor_data());
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Filter>(
                "SessionSearchSpanRequest.Filter",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Filter {
        const NAME: &'static str = "Filter";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.filter = ::std::option::Option::Some(filter::Filter::SpanName(is.read_string()?));
                    },
                    18 => {
                        self.filter = ::std::option::Option::Some(filter::Filter::SpanId(is.read_string()?));
                    },
                    24 => {
                        self.operator = is.read_enum_or_unknown()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.operator != ::protobuf::EnumOrUnknown::new(filter::Operator::EQUALS) {
                my_size += ::protobuf::rt::int32_size(3, self.operator.value());
            }
            if let ::std::option::Option::Some(ref v) = self.filter {
                match v {
                    &filter::Filter::SpanName(ref v) => {
                        my_size += ::protobuf::rt::string_size(1, &v);
                    },
                    &filter::Filter::SpanId(ref v) => {
                        my_size += ::protobuf::rt::string_size(2, &v);
                    },
                };
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.operator != ::protobuf::EnumOrUnknown::new(filter::Operator::EQUALS) {
                os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.operator))?;
            }
            if let ::std::option::Option::Some(ref v) = self.filter {
                match v {
                    &filter::Filter::SpanName(ref v) => {
                        os.write_string(1, v)?;
                    },
                    &filter::Filter::SpanId(ref v) => {
                        os.write_string(2, v)?;
                    },
                };
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Filter {
            Filter::new()
        }

        fn clear(&mut self) {
            self.filter = ::std::option::Option::None;
            self.filter = ::std::option::Option::None;
            self.operator = ::protobuf::EnumOrUnknown::new(filter::Operator::EQUALS);
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Filter {
            static instance: Filter = Filter {
                operator: ::protobuf::EnumOrUnknown::from_i32(0),
                filter: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Filter {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("SessionSearchSpanRequest.Filter").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Filter {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Filter {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    /// Nested message and enums of message `Filter`
    pub mod filter {

        #[derive(Clone,PartialEq,Debug)]
        // @@protoc_insertion_point(oneof:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.filter)
        pub enum Filter {
            // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.span_name)
            SpanName(::std::string::String),
            // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.span_id)
            SpanId(::std::string::String),
        }

        impl ::protobuf::Oneof for Filter {
        }

        impl ::protobuf::OneofFull for Filter {
            fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| <super::Filter as ::protobuf::MessageFull>::descriptor().oneof_by_name("filter").unwrap()).clone()
            }
        }

        impl Filter {
            pub(in super::super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
                ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Filter>("filter")
            }
        }
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.Operator)
        pub enum Operator {
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.Operator.EQUALS)
            EQUALS = 0,
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.Operator.PREFIX)
            PREFIX = 1,
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.Operator.SUBSTRING)
            SUBSTRING = 2,
            // @@protoc_insertion_point(enum_value:bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter.Operator.NOT_EQUALS)
            NOT_EQUALS = 3,
        }

        impl ::protobuf::Enum for Operator {
            const NAME: &'static str = "Operator";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<Operator> {
                match value {
                    0 => ::std::option::Option::Some(Operator::EQUALS),
                    1 => ::std::option::Option::Some(Operator::PREFIX),
                    2 => ::std::option::Option::Some(Operator::SUBSTRING),
                    3 => ::std::option::Option::Some(Operator::NOT_EQUALS),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<Operator> {
                match str {
                    "EQUALS" => ::std::option::Option::Some(Operator::EQUALS),
                    "PREFIX" => ::std::option::Option::Some(Operator::PREFIX),
                    "SUBSTRING" => ::std::option::Option::Some(Operator::SUBSTRING),
                    "NOT_EQUALS" => ::std::option::Option::Some(Operator::NOT_EQUALS),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [Operator] = &[
                Operator::EQUALS,
                Operator::PREFIX,
                Operator::SUBSTRING,
                Operator::NOT_EQUALS,
            ];
        }

        impl ::protobuf::EnumFull for Operator {
            fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| super::super::file_descriptor().enum_by_package_relative_name("SessionSearchSpanRequest.Filter.Operator").unwrap()).clone()
            }

            fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
                let index = *self as usize;
                Self::enum_descriptor().value_by_index(index)
            }
        }

        impl ::std::default::Default for Operator {
            fn default() -> Self {
                Operator::EQUALS
            }
        }

        impl Operator {
            pub(in super::super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
                ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Operator>("SessionSearchSpanRequest.Filter.Operator")
            }
        }
    }
}

// @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SessionSearchSpanResponse {
    // message fields
    // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.spans)
    pub spans: ::std::vec::Vec<session_search_span_response::SpanNode>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SessionSearchSpanResponse {
    fn default() -> &'a SessionSearchSpanResponse {
        <SessionSearchSpanResponse as ::protobuf::Message>::default_instance()
    }
}

impl SessionSearchSpanResponse {
    pub fn new() -> SessionSearchSpanResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "spans",
            |m: &SessionSearchSpanResponse| { &m.spans },
            |m: &mut SessionSearchSpanResponse| { &mut m.spans },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SessionSearchSpanResponse>(
            "SessionSearchSpanResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SessionSearchSpanResponse {
    const NAME: &'static str = "SessionSearchSpanResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.spans.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.spans {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.spans {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SessionSearchSpanResponse {
        SessionSearchSpanResponse::new()
    }

    fn clear(&mut self) {
        self.spans.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SessionSearchSpanResponse {
        static instance: SessionSearchSpanResponse = SessionSearchSpanResponse {
            spans: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SessionSearchSpanResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SessionSearchSpanResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SessionSearchSpanResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SessionSearchSpanResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `SessionSearchSpanResponse`
pub mod session_search_span_response {
    // @@protoc_insertion_point(message:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.SpanNode)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct SpanNode {
        // message fields
        // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.SpanNode.log_id)
        pub log_id: i64,
        // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.SpanNode.span)
        pub span: ::protobuf::MessageField<super::Span>,
        // @@protoc_insertion_point(field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.SpanNode.has_children)
        pub has_children: bool,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.timeline.v1.SessionSearchSpanResponse.SpanNode.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a SpanNode {
        fn default() -> &'a SpanNode {
            <SpanNode as ::protobuf::Message>::default_instance()
        }
    }

    impl SpanNode {
        pub fn new() -> SpanNode {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(3);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "log_id",
                |m: &SpanNode| { &m.log_id },
                |m: &mut SpanNode| { &mut m.log_id },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Span>(
                "span",
                |m: &SpanNode| { &m.span },
                |m: &mut SpanNode| { &mut m.span },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "has_children",
                |m: &SpanNode| { &m.has_children },
                |m: &mut SpanNode| { &mut m.has_children },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SpanNode>(
                "SessionSearchSpanResponse.SpanNode",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for SpanNode {
        const NAME: &'static str = "SpanNode";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.log_id = is.read_int64()?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.span)?;
                    },
                    24 => {
                        self.has_children = is.read_bool()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.log_id != 0 {
                my_size += ::protobuf::rt::int64_size(1, self.log_id);
            }
            if let Some(v) = self.span.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if self.has_children != false {
                my_size += 1 + 1;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.log_id != 0 {
                os.write_int64(1, self.log_id)?;
            }
            if let Some(v) = self.span.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if self.has_children != false {
                os.write_bool(3, self.has_children)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> SpanNode {
            SpanNode::new()
        }

        fn clear(&mut self) {
            self.log_id = 0;
            self.span.clear();
            self.has_children = false;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static SpanNode {
            static instance: SpanNode = SpanNode {
                log_id: 0,
                span: ::protobuf::MessageField::none(),
                has_children: false,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for SpanNode {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("SessionSearchSpanResponse.SpanNode").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for SpanNode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for SpanNode {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n-bitdrift/public/unary/timeline/v1/spans.proto\x12!bitdrift.public.una\
    ry.timeline.v1\x1a,bitdrift/public/unary/timeline/v1/logs.proto\x1a\x1fg\
    oogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xc2\x02\
    \n\x04Span\x12\x17\n\x02id\x18\x01\x20\x01(\tR\x02idB\x07\xfaB\x04r\x02\
    \x10\x01\x12C\n\nstarted_at\x18\x02\x20\x01(\x0b2\x1a.google.protobuf.Ti\
    mestampR\tstartedAtB\x08\xfaB\x05\xb2\x01\x02\x08\x01\x12E\n\x0bfinished\
    _at\x18\x03\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\nfinishedAtB\
    \x08\xfaB\x05\xb2\x01\x02\x08\x01\x12\x1b\n\x04name\x18\x04\x20\x01(\tR\
    \x04nameB\x07\xfaB\x04r\x02\x10\x01\x12\x20\n\tparent_id\x18\x05\x20\x01\
    (\tH\0R\x08parentId\x88\x01\x01\x12H\n\x06fields\x18\x06\x20\x01(\x0b20.\
    bitdrift.public.unary.timeline.v1.Log.LogFieldsR\x06fieldsB\x0c\n\n_pare\
    nt_id\"\xe4\x04\n\x18SessionSearchSpanRequest\x12(\n\nsession_id\x18\x01\
    \x20\x01(\tR\tsessionIdB\t\xfaB\x06r\x04\x10\x01\x18d\x12h\n\x07filters\
    \x18\x02\x20\x03(\x0b2B.bitdrift.public.unary.timeline.v1.SessionSearchS\
    panRequest.FilterR\x07filtersB\n\xfaB\x07\x92\x01\x04\x08\x01\x10\x14\
    \x12\x20\n\tmax_depth\x18\x03\x20\x01(\rH\0R\x08maxDepth\x88\x01\x01\x12\
    \x20\n\x04page\x18\x04\x20\x01(\x04H\x01R\x04pageB\x07\xfaB\x042\x02(\
    \x01\x88\x01\x01\x12*\n\x08per_page\x18\x05\x20\x01(\x04H\x02R\x07perPag\
    eB\n\xfaB\x072\x05\x18\xf4\x03(\x01\x88\x01\x01\x1a\x9f\x02\n\x06Filter\
    \x12)\n\tspan_name\x18\x01\x20\x01(\tH\0R\x08spanNameB\n\xfaB\x07r\x05\
    \x10\x01\x18\xc8\x01\x12%\n\x07span_id\x18\x02\x20\x01(\tH\0R\x06spanIdB\
    \n\xfaB\x07r\x05\x10\x01\x18\xc8\x01\x12q\n\x08operator\x18\x03\x20\x01(\
    \x0e2K.bitdrift.public.unary.timeline.v1.SessionSearchSpanRequest.Filter\
    .OperatorR\x08operatorB\x08\xfaB\x05\x82\x01\x02\x10\x01\"A\n\x08Operato\
    r\x12\n\n\x06EQUALS\x10\0\x12\n\n\x06PREFIX\x10\x01\x12\r\n\tSUBSTRING\
    \x10\x02\x12\x0e\n\nNOT_EQUALS\x10\x03B\r\n\x06filter\x12\x03\xf8B\x01B\
    \x0c\n\n_max_depthB\x07\n\x05_pageB\x0b\n\t_per_page\"\xfc\x01\n\x19Sess\
    ionSearchSpanResponse\x12[\n\x05spans\x18\x01\x20\x03(\x0b2E.bitdrift.pu\
    blic.unary.timeline.v1.SessionSearchSpanResponse.SpanNodeR\x05spans\x1a\
    \x81\x01\n\x08SpanNode\x12\x15\n\x06log_id\x18\x01\x20\x01(\x03R\x05logI\
    d\x12;\n\x04span\x18\x02\x20\x01(\x0b2'.bitdrift.public.unary.timeline.v\
    1.SpanR\x04span\x12!\n\x0chas_children\x18\x03\x20\x01(\x08R\x0bhasChild\
    renb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::logs::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(Span::generated_message_descriptor_data());
            messages.push(SessionSearchSpanRequest::generated_message_descriptor_data());
            messages.push(SessionSearchSpanResponse::generated_message_descriptor_data());
            messages.push(session_search_span_request::Filter::generated_message_descriptor_data());
            messages.push(session_search_span_response::SpanNode::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(session_search_span_request::filter::Operator::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
