[package]
edition      = "2021"
name         = "bd-report-writer-tests"
version      = "1.0.0"
license-file = "../LICENSE"
publish      = false

[lib]
doctest = false

[dependencies]
bd-report-writer.path = "../bd-report-writer"
flatbuffers.workspace = true

[dev-dependencies]
bd-test-helpers.path  = "../bd-test-helpers"
bd-proto.path = "../bd-proto"

[build-dependencies]
cc.workspace = true
bd-report-writer.path = "../bd-report-writer"
