[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-report-writer-tests"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
bd-report-writer.path       = "../bd-report-writer"
bd-workspace-hack.workspace = true
flatbuffers.workspace       = true

[dev-dependencies]
bd-proto.path        = "../bd-proto"
bd-test-helpers.path = "../bd-test-helpers"

[build-dependencies]
bd-report-writer.path = "../bd-report-writer"
cc.workspace          = true
