[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-runtime"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
async-trait.workspace       = true
bd-client-common.path       = "../bd-client-common"
bd-proto.path               = "../bd-proto"
bd-workspace-hack.workspace = true
log.workspace               = true
parking_lot.workspace       = true
protobuf.workspace          = true
tempfile.workspace          = true
time.workspace              = true
tokio.workspace             = true

[dev-dependencies]
assert_matches.workspace = true
bd-test-helpers          = { path = "../bd-test-helpers", default-features = false }
ctor.workspace           = true
