[package]
edition      = "2024"
license-file = "../LICENSE.polyform"
name         = "bd-workflow-stats"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
arbitrary                   = { workspace = true, optional = true }
bd-macros.path              = "../bd-macros"
bd-proto-util.path          = "../bd-proto-util"
bd-stats-common.path        = "../bd-stats-common"
bd-workspace-hack.workspace = true
protobuf.workspace          = true

[features]
fuzzing = ["dep:arbitrary"]
