[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-report-parsers"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
bd-proto.path               = "../bd-proto"
bd-workspace-hack.workspace = true
flatbuffers.workspace       = true
itertools.workspace         = true
memmap2.workspace           = true
nom.workspace               = true

[dev-dependencies]
insta.workspace        = true
nom-language.workspace = true
tempfile.workspace     = true
