// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 34.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/admin/v1/keys.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.SdkKeyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SdkKeyResponse {
    // message fields
    ///  The generated key, base64 encoded.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.SdkKeyResponse.key)
    pub key: ::std::string::String,
    ///  The app/bundle ID regex that the key is associated with.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.SdkKeyResponse.bundle_id_regex)
    pub bundle_id_regex: ::std::string::String,
    ///  An optional postfix for the app ID associated with the key. The server
    ///  appends this to the base app ID during authentication.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.SdkKeyResponse.app_id_postfix)
    pub app_id_postfix: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.SdkKeyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SdkKeyResponse {
    fn default() -> &'a SdkKeyResponse {
        <SdkKeyResponse as ::protobuf::Message>::default_instance()
    }
}

impl SdkKeyResponse {
    pub fn new() -> SdkKeyResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &SdkKeyResponse| { &m.key },
            |m: &mut SdkKeyResponse| { &mut m.key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bundle_id_regex",
            |m: &SdkKeyResponse| { &m.bundle_id_regex },
            |m: &mut SdkKeyResponse| { &mut m.bundle_id_regex },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "app_id_postfix",
            |m: &SdkKeyResponse| { &m.app_id_postfix },
            |m: &mut SdkKeyResponse| { &mut m.app_id_postfix },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SdkKeyResponse>(
            "SdkKeyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SdkKeyResponse {
    const NAME: &'static str = "SdkKeyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.key = is.read_string()?;
                },
                18 => {
                    self.bundle_id_regex = is.read_string()?;
                },
                26 => {
                    self.app_id_postfix = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.key);
        }
        if !self.bundle_id_regex.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.bundle_id_regex);
        }
        if let Some(v) = self.app_id_postfix.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.key.is_empty() {
            os.write_string(1, &self.key)?;
        }
        if !self.bundle_id_regex.is_empty() {
            os.write_string(2, &self.bundle_id_regex)?;
        }
        if let Some(v) = self.app_id_postfix.as_ref() {
            os.write_string(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SdkKeyResponse {
        SdkKeyResponse::new()
    }

    fn clear(&mut self) {
        self.key.clear();
        self.bundle_id_regex.clear();
        self.app_id_postfix = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SdkKeyResponse {
        static instance: SdkKeyResponse = SdkKeyResponse {
            key: ::std::string::String::new(),
            bundle_id_regex: ::std::string::String::new(),
            app_id_postfix: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SdkKeyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SdkKeyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SdkKeyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SdkKeyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.ApiKeyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ApiKeyResponse {
    // message fields
    ///  The fingerprint of the API key, base64 encoded. API keys are not stored by the server and
    ///  cannot be recovered if lost.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.ApiKeyResponse.fingerprint)
    pub fingerprint: ::std::string::String,
    ///  The generated key, base64 encoded. This value is returned only when the
    ///  key is created and is empty on subsequent responses.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.ApiKeyResponse.key)
    pub key: ::std::string::String,
    ///  The permissions that the key has.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.ApiKeyResponse.permissions)
    pub permissions: ::std::vec::Vec<::protobuf::EnumOrUnknown<super::permission::Permission>>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.ApiKeyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ApiKeyResponse {
    fn default() -> &'a ApiKeyResponse {
        <ApiKeyResponse as ::protobuf::Message>::default_instance()
    }
}

impl ApiKeyResponse {
    pub fn new() -> ApiKeyResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "fingerprint",
            |m: &ApiKeyResponse| { &m.fingerprint },
            |m: &mut ApiKeyResponse| { &mut m.fingerprint },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &ApiKeyResponse| { &m.key },
            |m: &mut ApiKeyResponse| { &mut m.key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "permissions",
            |m: &ApiKeyResponse| { &m.permissions },
            |m: &mut ApiKeyResponse| { &mut m.permissions },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ApiKeyResponse>(
            "ApiKeyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ApiKeyResponse {
    const NAME: &'static str = "ApiKeyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.fingerprint = is.read_string()?;
                },
                18 => {
                    self.key = is.read_string()?;
                },
                32 => {
                    self.permissions.push(is.read_enum_or_unknown()?);
                },
                34 => {
                    ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.permissions)?
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.fingerprint.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.fingerprint);
        }
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.key);
        }
        my_size += ::protobuf::rt::vec_packed_enum_or_unknown_size(4, &self.permissions);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.fingerprint.is_empty() {
            os.write_string(1, &self.fingerprint)?;
        }
        if !self.key.is_empty() {
            os.write_string(2, &self.key)?;
        }
        os.write_repeated_packed_enum_or_unknown(4, &self.permissions)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ApiKeyResponse {
        ApiKeyResponse::new()
    }

    fn clear(&mut self) {
        self.fingerprint.clear();
        self.key.clear();
        self.permissions.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ApiKeyResponse {
        static instance: ApiKeyResponse = ApiKeyResponse {
            fingerprint: ::std::string::String::new(),
            key: ::std::string::String::new(),
            permissions: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ApiKeyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ApiKeyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ApiKeyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ApiKeyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.KeyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KeyResponse {
    // message fields
    ///  The ID of the key to be used for revocation and further operations.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.KeyResponse.id)
    pub id: u64,
    ///  The creation time of the key.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.KeyResponse.created_at)
    pub created_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  An optional expiration time for the key. If the key expires the behavior will be similar to
    ///  revocation which will cause an unauthenticated response to be returned.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.KeyResponse.expires_at)
    pub expires_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  Whether the key was explicitly revoked.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.KeyResponse.revoked)
    pub revoked: bool,
    ///  The name of the key, used for (human) identification purposes.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.KeyResponse.name)
    pub name: ::std::string::String,
    // message oneof groups
    pub key_type: ::std::option::Option<key_response::Key_type>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.KeyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KeyResponse {
    fn default() -> &'a KeyResponse {
        <KeyResponse as ::protobuf::Message>::default_instance()
    }
}

impl KeyResponse {
    pub fn new() -> KeyResponse {
        ::std::default::Default::default()
    }

    // .bitdrift.public.unary.admin.v1.SdkKeyResponse sdk_key = 5;

    pub fn sdk_key(&self) -> &SdkKeyResponse {
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::SdkKey(ref v)) => v,
            _ => <SdkKeyResponse as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_sdk_key(&mut self) {
        self.key_type = ::std::option::Option::None;
    }

    pub fn has_sdk_key(&self) -> bool {
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::SdkKey(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_sdk_key(&mut self, v: SdkKeyResponse) {
        self.key_type = ::std::option::Option::Some(key_response::Key_type::SdkKey(v))
    }

    // Mutable pointer to the field.
    pub fn mut_sdk_key(&mut self) -> &mut SdkKeyResponse {
        if let ::std::option::Option::Some(key_response::Key_type::SdkKey(_)) = self.key_type {
        } else {
            self.key_type = ::std::option::Option::Some(key_response::Key_type::SdkKey(SdkKeyResponse::new()));
        }
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::SdkKey(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_sdk_key(&mut self) -> SdkKeyResponse {
        if self.has_sdk_key() {
            match self.key_type.take() {
                ::std::option::Option::Some(key_response::Key_type::SdkKey(v)) => v,
                _ => panic!(),
            }
        } else {
            SdkKeyResponse::new()
        }
    }

    // .bitdrift.public.unary.admin.v1.ApiKeyResponse api_key = 6;

    pub fn api_key(&self) -> &ApiKeyResponse {
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::ApiKey(ref v)) => v,
            _ => <ApiKeyResponse as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_api_key(&mut self) {
        self.key_type = ::std::option::Option::None;
    }

    pub fn has_api_key(&self) -> bool {
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::ApiKey(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_api_key(&mut self, v: ApiKeyResponse) {
        self.key_type = ::std::option::Option::Some(key_response::Key_type::ApiKey(v))
    }

    // Mutable pointer to the field.
    pub fn mut_api_key(&mut self) -> &mut ApiKeyResponse {
        if let ::std::option::Option::Some(key_response::Key_type::ApiKey(_)) = self.key_type {
        } else {
            self.key_type = ::std::option::Option::Some(key_response::Key_type::ApiKey(ApiKeyResponse::new()));
        }
        match self.key_type {
            ::std::option::Option::Some(key_response::Key_type::ApiKey(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_api_key(&mut self) -> ApiKeyResponse {
        if self.has_api_key() {
            match self.key_type.take() {
                ::std::option::Option::Some(key_response::Key_type::ApiKey(v)) => v,
                _ => panic!(),
            }
        } else {
            ApiKeyResponse::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &KeyResponse| { &m.id },
            |m: &mut KeyResponse| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "created_at",
            |m: &KeyResponse| { &m.created_at },
            |m: &mut KeyResponse| { &mut m.created_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "expires_at",
            |m: &KeyResponse| { &m.expires_at },
            |m: &mut KeyResponse| { &mut m.expires_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "revoked",
            |m: &KeyResponse| { &m.revoked },
            |m: &mut KeyResponse| { &mut m.revoked },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, SdkKeyResponse>(
            "sdk_key",
            KeyResponse::has_sdk_key,
            KeyResponse::sdk_key,
            KeyResponse::mut_sdk_key,
            KeyResponse::set_sdk_key,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, ApiKeyResponse>(
            "api_key",
            KeyResponse::has_api_key,
            KeyResponse::api_key,
            KeyResponse::mut_api_key,
            KeyResponse::set_api_key,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &KeyResponse| { &m.name },
            |m: &mut KeyResponse| { &mut m.name },
        ));
        oneofs.push(key_response::Key_type::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KeyResponse>(
            "KeyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KeyResponse {
    const NAME: &'static str = "KeyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint64()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.created_at)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.expires_at)?;
                },
                32 => {
                    self.revoked = is.read_bool()?;
                },
                42 => {
                    self.key_type = ::std::option::Option::Some(key_response::Key_type::SdkKey(is.read_message()?));
                },
                50 => {
                    self.key_type = ::std::option::Option::Some(key_response::Key_type::ApiKey(is.read_message()?));
                },
                58 => {
                    self.name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.id);
        }
        if let Some(v) = self.created_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.expires_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.revoked != false {
            my_size += 1 + 1;
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.name);
        }
        if let ::std::option::Option::Some(ref v) = self.key_type {
            match v {
                &key_response::Key_type::SdkKey(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &key_response::Key_type::ApiKey(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint64(1, self.id)?;
        }
        if let Some(v) = self.created_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.expires_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.revoked != false {
            os.write_bool(4, self.revoked)?;
        }
        if !self.name.is_empty() {
            os.write_string(7, &self.name)?;
        }
        if let ::std::option::Option::Some(ref v) = self.key_type {
            match v {
                &key_response::Key_type::SdkKey(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
                },
                &key_response::Key_type::ApiKey(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KeyResponse {
        KeyResponse::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.created_at.clear();
        self.expires_at.clear();
        self.revoked = false;
        self.key_type = ::std::option::Option::None;
        self.key_type = ::std::option::Option::None;
        self.name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KeyResponse {
        static instance: KeyResponse = KeyResponse {
            id: 0,
            created_at: ::protobuf::MessageField::none(),
            expires_at: ::protobuf::MessageField::none(),
            revoked: false,
            name: ::std::string::String::new(),
            key_type: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KeyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KeyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KeyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KeyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `KeyResponse`
pub mod key_response {

    #[derive(Clone,PartialEq,Debug)]
    // @@protoc_insertion_point(oneof:bitdrift.public.unary.admin.v1.KeyResponse.key_type)
    pub enum Key_type {
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.admin.v1.KeyResponse.sdk_key)
        SdkKey(super::SdkKeyResponse),
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.admin.v1.KeyResponse.api_key)
        ApiKey(super::ApiKeyResponse),
    }

    impl ::protobuf::Oneof for Key_type {
    }

    impl ::protobuf::OneofFull for Key_type {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::KeyResponse as ::protobuf::MessageFull>::descriptor().oneof_by_name("key_type").unwrap()).clone()
        }
    }

    impl Key_type {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Key_type>("key_type")
        }
    }
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.GetKeysRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetKeysRequest {
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.GetKeysRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetKeysRequest {
    fn default() -> &'a GetKeysRequest {
        <GetKeysRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetKeysRequest {
    pub fn new() -> GetKeysRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetKeysRequest>(
            "GetKeysRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetKeysRequest {
    const NAME: &'static str = "GetKeysRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetKeysRequest {
        GetKeysRequest::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetKeysRequest {
        static instance: GetKeysRequest = GetKeysRequest {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetKeysRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetKeysRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetKeysRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetKeysRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.GetKeysResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetKeysResponse {
    // message fields
    ///  The API and SDK keys visible to the authenticated user.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.GetKeysResponse.keys)
    pub keys: ::std::vec::Vec<KeyResponse>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.GetKeysResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetKeysResponse {
    fn default() -> &'a GetKeysResponse {
        <GetKeysResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetKeysResponse {
    pub fn new() -> GetKeysResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "keys",
            |m: &GetKeysResponse| { &m.keys },
            |m: &mut GetKeysResponse| { &mut m.keys },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetKeysResponse>(
            "GetKeysResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetKeysResponse {
    const NAME: &'static str = "GetKeysResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.keys.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.keys {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.keys {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetKeysResponse {
        GetKeysResponse::new()
    }

    fn clear(&mut self) {
        self.keys.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetKeysResponse {
        static instance: GetKeysResponse = GetKeysResponse {
            keys: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetKeysResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetKeysResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetKeysResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetKeysResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.CreateKeyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CreateKeyRequest {
    // message fields
    ///  The name of the key, used for (human) identification purposes.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.CreateKeyRequest.name)
    pub name: ::std::string::String,
    // message oneof groups
    pub key_type: ::std::option::Option<create_key_request::Key_type>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.CreateKeyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreateKeyRequest {
    fn default() -> &'a CreateKeyRequest {
        <CreateKeyRequest as ::protobuf::Message>::default_instance()
    }
}

impl CreateKeyRequest {
    pub fn new() -> CreateKeyRequest {
        ::std::default::Default::default()
    }

    // .bitdrift.public.unary.admin.v1.CreateKeyRequest.SdkKeyRequest sdk_key = 1;

    pub fn sdk_key(&self) -> &create_key_request::SdkKeyRequest {
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::SdkKey(ref v)) => v,
            _ => <create_key_request::SdkKeyRequest as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_sdk_key(&mut self) {
        self.key_type = ::std::option::Option::None;
    }

    pub fn has_sdk_key(&self) -> bool {
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::SdkKey(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_sdk_key(&mut self, v: create_key_request::SdkKeyRequest) {
        self.key_type = ::std::option::Option::Some(create_key_request::Key_type::SdkKey(v))
    }

    // Mutable pointer to the field.
    pub fn mut_sdk_key(&mut self) -> &mut create_key_request::SdkKeyRequest {
        if let ::std::option::Option::Some(create_key_request::Key_type::SdkKey(_)) = self.key_type {
        } else {
            self.key_type = ::std::option::Option::Some(create_key_request::Key_type::SdkKey(create_key_request::SdkKeyRequest::new()));
        }
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::SdkKey(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_sdk_key(&mut self) -> create_key_request::SdkKeyRequest {
        if self.has_sdk_key() {
            match self.key_type.take() {
                ::std::option::Option::Some(create_key_request::Key_type::SdkKey(v)) => v,
                _ => panic!(),
            }
        } else {
            create_key_request::SdkKeyRequest::new()
        }
    }

    // .bitdrift.public.unary.admin.v1.CreateKeyRequest.ApiKeyRequest api_key = 2;

    pub fn api_key(&self) -> &create_key_request::ApiKeyRequest {
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::ApiKey(ref v)) => v,
            _ => <create_key_request::ApiKeyRequest as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_api_key(&mut self) {
        self.key_type = ::std::option::Option::None;
    }

    pub fn has_api_key(&self) -> bool {
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::ApiKey(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_api_key(&mut self, v: create_key_request::ApiKeyRequest) {
        self.key_type = ::std::option::Option::Some(create_key_request::Key_type::ApiKey(v))
    }

    // Mutable pointer to the field.
    pub fn mut_api_key(&mut self) -> &mut create_key_request::ApiKeyRequest {
        if let ::std::option::Option::Some(create_key_request::Key_type::ApiKey(_)) = self.key_type {
        } else {
            self.key_type = ::std::option::Option::Some(create_key_request::Key_type::ApiKey(create_key_request::ApiKeyRequest::new()));
        }
        match self.key_type {
            ::std::option::Option::Some(create_key_request::Key_type::ApiKey(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_api_key(&mut self) -> create_key_request::ApiKeyRequest {
        if self.has_api_key() {
            match self.key_type.take() {
                ::std::option::Option::Some(create_key_request::Key_type::ApiKey(v)) => v,
                _ => panic!(),
            }
        } else {
            create_key_request::ApiKeyRequest::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, create_key_request::SdkKeyRequest>(
            "sdk_key",
            CreateKeyRequest::has_sdk_key,
            CreateKeyRequest::sdk_key,
            CreateKeyRequest::mut_sdk_key,
            CreateKeyRequest::set_sdk_key,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, create_key_request::ApiKeyRequest>(
            "api_key",
            CreateKeyRequest::has_api_key,
            CreateKeyRequest::api_key,
            CreateKeyRequest::mut_api_key,
            CreateKeyRequest::set_api_key,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &CreateKeyRequest| { &m.name },
            |m: &mut CreateKeyRequest| { &mut m.name },
        ));
        oneofs.push(create_key_request::Key_type::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreateKeyRequest>(
            "CreateKeyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreateKeyRequest {
    const NAME: &'static str = "CreateKeyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.key_type = ::std::option::Option::Some(create_key_request::Key_type::SdkKey(is.read_message()?));
                },
                18 => {
                    self.key_type = ::std::option::Option::Some(create_key_request::Key_type::ApiKey(is.read_message()?));
                },
                26 => {
                    self.name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.name);
        }
        if let ::std::option::Option::Some(ref v) = self.key_type {
            match v {
                &create_key_request::Key_type::SdkKey(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &create_key_request::Key_type::ApiKey(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(3, &self.name)?;
        }
        if let ::std::option::Option::Some(ref v) = self.key_type {
            match v {
                &create_key_request::Key_type::SdkKey(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &create_key_request::Key_type::ApiKey(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreateKeyRequest {
        CreateKeyRequest::new()
    }

    fn clear(&mut self) {
        self.key_type = ::std::option::Option::None;
        self.key_type = ::std::option::Option::None;
        self.name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreateKeyRequest {
        static instance: CreateKeyRequest = CreateKeyRequest {
            name: ::std::string::String::new(),
            key_type: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreateKeyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreateKeyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreateKeyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateKeyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `CreateKeyRequest`
pub mod create_key_request {

    #[derive(Clone,PartialEq,Debug)]
    // @@protoc_insertion_point(oneof:bitdrift.public.unary.admin.v1.CreateKeyRequest.key_type)
    pub enum Key_type {
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.admin.v1.CreateKeyRequest.sdk_key)
        SdkKey(SdkKeyRequest),
        // @@protoc_insertion_point(oneof_field:bitdrift.public.unary.admin.v1.CreateKeyRequest.api_key)
        ApiKey(ApiKeyRequest),
    }

    impl ::protobuf::Oneof for Key_type {
    }

    impl ::protobuf::OneofFull for Key_type {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::CreateKeyRequest as ::protobuf::MessageFull>::descriptor().oneof_by_name("key_type").unwrap()).clone()
        }
    }

    impl Key_type {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Key_type>("key_type")
        }
    }
    // @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.CreateKeyRequest.SdkKeyRequest)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct SdkKeyRequest {
        // message fields
        ///  The app/bundle ID regex that the key is associated with.
        // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.CreateKeyRequest.SdkKeyRequest.bundle_id_regex)
        pub bundle_id_regex: ::std::string::String,
        ///  An optional postfix for the app ID associated with the key. The server
        ///  appends this to the base app ID during authentication.
        // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.CreateKeyRequest.SdkKeyRequest.app_id_postfix)
        pub app_id_postfix: ::std::option::Option<::std::string::String>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.CreateKeyRequest.SdkKeyRequest.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a SdkKeyRequest {
        fn default() -> &'a SdkKeyRequest {
            <SdkKeyRequest as ::protobuf::Message>::default_instance()
        }
    }

    impl SdkKeyRequest {
        pub fn new() -> SdkKeyRequest {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "bundle_id_regex",
                |m: &SdkKeyRequest| { &m.bundle_id_regex },
                |m: &mut SdkKeyRequest| { &mut m.bundle_id_regex },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
                "app_id_postfix",
                |m: &SdkKeyRequest| { &m.app_id_postfix },
                |m: &mut SdkKeyRequest| { &mut m.app_id_postfix },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SdkKeyRequest>(
                "CreateKeyRequest.SdkKeyRequest",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for SdkKeyRequest {
        const NAME: &'static str = "SdkKeyRequest";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.bundle_id_regex = is.read_string()?;
                    },
                    18 => {
                        self.app_id_postfix = ::std::option::Option::Some(is.read_string()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.bundle_id_regex.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.bundle_id_regex);
            }
            if let Some(v) = self.app_id_postfix.as_ref() {
                my_size += ::protobuf::rt::string_size(2, &v);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.bundle_id_regex.is_empty() {
                os.write_string(1, &self.bundle_id_regex)?;
            }
            if let Some(v) = self.app_id_postfix.as_ref() {
                os.write_string(2, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> SdkKeyRequest {
            SdkKeyRequest::new()
        }

        fn clear(&mut self) {
            self.bundle_id_regex.clear();
            self.app_id_postfix = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static SdkKeyRequest {
            static instance: SdkKeyRequest = SdkKeyRequest {
                bundle_id_regex: ::std::string::String::new(),
                app_id_postfix: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for SdkKeyRequest {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("CreateKeyRequest.SdkKeyRequest").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for SdkKeyRequest {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for SdkKeyRequest {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    // @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.CreateKeyRequest.ApiKeyRequest)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ApiKeyRequest {
        // message fields
        ///  The permissions that the key should have. Must have at least one permission.
        // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.CreateKeyRequest.ApiKeyRequest.permissions)
        pub permissions: ::std::vec::Vec<::protobuf::EnumOrUnknown<super::super::permission::Permission>>,
        // special fields
        // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.CreateKeyRequest.ApiKeyRequest.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ApiKeyRequest {
        fn default() -> &'a ApiKeyRequest {
            <ApiKeyRequest as ::protobuf::Message>::default_instance()
        }
    }

    impl ApiKeyRequest {
        pub fn new() -> ApiKeyRequest {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(1);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "permissions",
                |m: &ApiKeyRequest| { &m.permissions },
                |m: &mut ApiKeyRequest| { &mut m.permissions },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ApiKeyRequest>(
                "CreateKeyRequest.ApiKeyRequest",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for ApiKeyRequest {
        const NAME: &'static str = "ApiKeyRequest";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    16 => {
                        self.permissions.push(is.read_enum_or_unknown()?);
                    },
                    18 => {
                        ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.permissions)?
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            my_size += ::protobuf::rt::vec_packed_enum_or_unknown_size(2, &self.permissions);
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            os.write_repeated_packed_enum_or_unknown(2, &self.permissions)?;
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ApiKeyRequest {
            ApiKeyRequest::new()
        }

        fn clear(&mut self) {
            self.permissions.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ApiKeyRequest {
            static instance: ApiKeyRequest = ApiKeyRequest {
                permissions: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for ApiKeyRequest {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("CreateKeyRequest.ApiKeyRequest").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for ApiKeyRequest {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for ApiKeyRequest {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.CreateKeyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CreateKeyResponse {
    // message fields
    ///  The created key.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.CreateKeyResponse.key)
    pub key: ::protobuf::MessageField<KeyResponse>,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.CreateKeyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreateKeyResponse {
    fn default() -> &'a CreateKeyResponse {
        <CreateKeyResponse as ::protobuf::Message>::default_instance()
    }
}

impl CreateKeyResponse {
    pub fn new() -> CreateKeyResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, KeyResponse>(
            "key",
            |m: &CreateKeyResponse| { &m.key },
            |m: &mut CreateKeyResponse| { &mut m.key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreateKeyResponse>(
            "CreateKeyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreateKeyResponse {
    const NAME: &'static str = "CreateKeyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.key)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.key.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreateKeyResponse {
        CreateKeyResponse::new()
    }

    fn clear(&mut self) {
        self.key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreateKeyResponse {
        static instance: CreateKeyResponse = CreateKeyResponse {
            key: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreateKeyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreateKeyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreateKeyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateKeyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.RevokeKeyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RevokeKeyRequest {
    // message fields
    ///  The ID of the key to revoke.
    // @@protoc_insertion_point(field:bitdrift.public.unary.admin.v1.RevokeKeyRequest.id)
    pub id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.RevokeKeyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RevokeKeyRequest {
    fn default() -> &'a RevokeKeyRequest {
        <RevokeKeyRequest as ::protobuf::Message>::default_instance()
    }
}

impl RevokeKeyRequest {
    pub fn new() -> RevokeKeyRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &RevokeKeyRequest| { &m.id },
            |m: &mut RevokeKeyRequest| { &mut m.id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RevokeKeyRequest>(
            "RevokeKeyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RevokeKeyRequest {
    const NAME: &'static str = "RevokeKeyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint64(1, self.id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RevokeKeyRequest {
        RevokeKeyRequest::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RevokeKeyRequest {
        static instance: RevokeKeyRequest = RevokeKeyRequest {
            id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RevokeKeyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RevokeKeyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RevokeKeyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RevokeKeyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:bitdrift.public.unary.admin.v1.RevokeKeyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RevokeKeyResponse {
    // special fields
    // @@protoc_insertion_point(special_field:bitdrift.public.unary.admin.v1.RevokeKeyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RevokeKeyResponse {
    fn default() -> &'a RevokeKeyResponse {
        <RevokeKeyResponse as ::protobuf::Message>::default_instance()
    }
}

impl RevokeKeyResponse {
    pub fn new() -> RevokeKeyResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RevokeKeyResponse>(
            "RevokeKeyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RevokeKeyResponse {
    const NAME: &'static str = "RevokeKeyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RevokeKeyResponse {
        RevokeKeyResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RevokeKeyResponse {
        static instance: RevokeKeyResponse = RevokeKeyResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RevokeKeyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RevokeKeyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RevokeKeyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RevokeKeyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n)bitdrift/public/unary/admin/v1/keys.proto\x12\x1ebitdrift.public.unar\
    y.admin.v1\x1a/bitdrift/public/unary/admin/v1/permission.proto\x1a\x1fgo\
    ogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x88\x01\n\
    \x0eSdkKeyResponse\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12&\n\
    \x0fbundle_id_regex\x18\x02\x20\x01(\tR\rbundleIdRegex\x12)\n\x0eapp_id_\
    postfix\x18\x03\x20\x01(\tH\0R\x0cappIdPostfix\x88\x01\x01B\x11\n\x0f_ap\
    p_id_postfix\"\x92\x01\n\x0eApiKeyResponse\x12\x20\n\x0bfingerprint\x18\
    \x01\x20\x01(\tR\x0bfingerprint\x12\x10\n\x03key\x18\x02\x20\x01(\tR\x03\
    key\x12L\n\x0bpermissions\x18\x04\x20\x03(\x0e2*.bitdrift.public.unary.a\
    dmin.v1.PermissionR\x0bpermissions\"\xe3\x02\n\x0bKeyResponse\x12\x0e\n\
    \x02id\x18\x01\x20\x01(\x04R\x02id\x129\n\ncreated_at\x18\x02\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n\nexpires_at\x18\
    \x03\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n\
    \x07revoked\x18\x04\x20\x01(\x08R\x07revoked\x12I\n\x07sdk_key\x18\x05\
    \x20\x01(\x0b2..bitdrift.public.unary.admin.v1.SdkKeyResponseH\0R\x06sdk\
    Key\x12I\n\x07api_key\x18\x06\x20\x01(\x0b2..bitdrift.public.unary.admin\
    .v1.ApiKeyResponseH\0R\x06apiKey\x12\x12\n\x04name\x18\x07\x20\x01(\tR\
    \x04nameB\n\n\x08key_type\"\x10\n\x0eGetKeysRequest\"R\n\x0fGetKeysRespo\
    nse\x12?\n\x04keys\x18\x01\x20\x03(\x0b2+.bitdrift.public.unary.admin.v1\
    .KeyResponseR\x04keys\"\xf9\x03\n\x10CreateKeyRequest\x12Y\n\x07sdk_key\
    \x18\x01\x20\x01(\x0b2>.bitdrift.public.unary.admin.v1.CreateKeyRequest.\
    SdkKeyRequestH\0R\x06sdkKey\x12Y\n\x07api_key\x18\x02\x20\x01(\x0b2>.bit\
    drift.public.unary.admin.v1.CreateKeyRequest.ApiKeyRequestH\0R\x06apiKey\
    \x12\x1e\n\x04name\x18\x03\x20\x01(\tR\x04nameB\n\xfaB\x07r\x05\x10\x01\
    \x18\xff\x01\x1a\x8b\x01\n\rSdkKeyRequest\x122\n\x0fbundle_id_regex\x18\
    \x01\x20\x01(\tR\rbundleIdRegexB\n\xfaB\x07r\x05\x10\x01\x18\x80\x10\x12\
    3\n\x0eapp_id_postfix\x18\x02\x20\x01(\tH\0R\x0cappIdPostfixB\x08\xfaB\
    \x05r\x03\x18\xff\x01\x88\x01\x01B\x11\n\x0f_app_id_postfix\x1ap\n\rApiK\
    eyRequest\x12_\n\x0bpermissions\x18\x02\x20\x03(\x0e2*.bitdrift.public.u\
    nary.admin.v1.PermissionR\x0bpermissionsB\x11\xfaB\x0e\x92\x01\x0b\x08\
    \x01\x10d\"\x05\x82\x01\x02\x10\x01B\x0f\n\x08key_type\x12\x03\xf8B\x01\
    \"R\n\x11CreateKeyResponse\x12=\n\x03key\x18\x01\x20\x01(\x0b2+.bitdrift\
    .public.unary.admin.v1.KeyResponseR\x03key\"\"\n\x10RevokeKeyRequest\x12\
    \x0e\n\x02id\x18\x01\x20\x01(\x04R\x02id\"\x13\n\x11RevokeKeyResponseJ\
    \xde\x1c\n\x06\x12\x04\x06\0z\x1c\n\xb8\x02\n\x01\x0c\x12\x03\x06\0\x12\
    \x1a\xad\x02\x20api\x20-\x20bitdrift's\x20client/server\x20API\x20defini\
    tions\n\x20Copyright\x20Bitdrift,\x20Inc.\x20All\x20rights\x20reserved.\
    \n\n\x20Use\x20of\x20this\x20source\x20code\x20and\x20APIs\x20are\x20gov\
    erned\x20by\x20a\x20source\x20available\x20license\x20that\x20can\x20be\
    \x20found\x20in\n\x20the\x20LICENSE\x20file\x20or\x20at:\n\x20https://po\
    lyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt\n\
    \n\x08\n\x01\x02\x12\x03\x08\0'\n\t\n\x02\x03\0\x12\x03\n\09\n\t\n\x02\
    \x03\x01\x12\x03\x0b\0)\n\t\n\x02\x03\x02\x12\x03\x0c\0!\n\n\n\x02\x04\0\
    \x12\x04\x0e\0\x18\x01\n\n\n\x03\x04\0\x01\x12\x03\x0e\x08\x16\n1\n\x04\
    \x04\0\x02\0\x12\x03\x10\x02\x11\x1a$\x20The\x20generated\x20key,\x20bas\
    e64\x20encoded.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x10\x02\x08\n\x0c\
    \n\x05\x04\0\x02\0\x01\x12\x03\x10\t\x0c\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\x10\x0f\x10\nG\n\x04\x04\0\x02\x01\x12\x03\x13\x02\x1d\x1a:\x20The\
    \x20app/bundle\x20ID\x20regex\x20that\x20the\x20key\x20is\x20associated\
    \x20with.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x13\x02\x08\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x13\t\x18\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x13\x1b\x1c\n\x8e\x01\n\x04\x04\0\x02\x02\x12\x03\x17\x02%\x1a\
    \x80\x01\x20An\x20optional\x20postfix\x20for\x20the\x20app\x20ID\x20asso\
    ciated\x20with\x20the\x20key.\x20The\x20server\n\x20appends\x20this\x20t\
    o\x20the\x20base\x20app\x20ID\x20during\x20authentication.\n\n\x0c\n\x05\
    \x04\0\x02\x02\x04\x12\x03\x17\x02\n\n\x0c\n\x05\x04\0\x02\x02\x05\x12\
    \x03\x17\x0b\x11\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x17\x12\x20\n\x0c\
    \n\x05\x04\0\x02\x02\x03\x12\x03\x17#$\n\n\n\x02\x04\x01\x12\x04\x1a\0%\
    \x01\n\n\n\x03\x04\x01\x01\x12\x03\x1a\x08\x16\n\x86\x01\n\x04\x04\x01\
    \x02\0\x12\x03\x1d\x02\x19\x1ay\x20The\x20fingerprint\x20of\x20the\x20AP\
    I\x20key,\x20base64\x20encoded.\x20API\x20keys\x20are\x20not\x20stored\
    \x20by\x20the\x20server\x20and\n\x20cannot\x20be\x20recovered\x20if\x20l\
    ost.\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x1d\x02\x08\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03\x1d\t\x14\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\
    \x1d\x17\x18\n\x8c\x01\n\x04\x04\x01\x02\x01\x12\x03!\x02\x11\x1a\x7f\
    \x20The\x20generated\x20key,\x20base64\x20encoded.\x20This\x20value\x20i\
    s\x20returned\x20only\x20when\x20the\n\x20key\x20is\x20created\x20and\
    \x20is\x20empty\x20on\x20subsequent\x20responses.\n\n\x0c\n\x05\x04\x01\
    \x02\x01\x05\x12\x03!\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03!\t\
    \x0c\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03!\x0f\x10\n0\n\x04\x04\x01\
    \x02\x02\x12\x03$\x02F\x1a#\x20The\x20permissions\x20that\x20the\x20key\
    \x20has.\n\n\x0c\n\x05\x04\x01\x02\x02\x04\x12\x03$\x02\n\n\x0c\n\x05\
    \x04\x01\x02\x02\x06\x12\x03$\x0b5\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\
    \x03$6A\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03$DE\n\n\n\x02\x04\x02\x12\
    \x04'\0?\x01\n\n\n\x03\x04\x02\x01\x12\x03'\x08\x13\nR\n\x04\x04\x02\x02\
    \0\x12\x03)\x02\x10\x1aE\x20The\x20ID\x20of\x20the\x20key\x20to\x20be\
    \x20used\x20for\x20revocation\x20and\x20further\x20operations.\n\n\x0c\n\
    \x05\x04\x02\x02\0\x05\x12\x03)\x02\x08\n\x0c\n\x05\x04\x02\x02\0\x01\
    \x12\x03)\t\x0b\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03)\x0e\x0f\n,\n\x04\
    \x04\x02\x02\x01\x12\x03,\x02,\x1a\x1f\x20The\x20creation\x20time\x20of\
    \x20the\x20key.\n\n\x0c\n\x05\x04\x02\x02\x01\x06\x12\x03,\x02\x1c\n\x0c\
    \n\x05\x04\x02\x02\x01\x01\x12\x03,\x1d'\n\x0c\n\x05\x04\x02\x02\x01\x03\
    \x12\x03,*+\n\xb4\x01\n\x04\x04\x02\x02\x02\x12\x030\x02,\x1a\xa6\x01\
    \x20An\x20optional\x20expiration\x20time\x20for\x20the\x20key.\x20If\x20\
    the\x20key\x20expires\x20the\x20behavior\x20will\x20be\x20similar\x20to\
    \n\x20revocation\x20which\x20will\x20cause\x20an\x20unauthenticated\x20r\
    esponse\x20to\x20be\x20returned.\n\n\x0c\n\x05\x04\x02\x02\x02\x06\x12\
    \x030\x02\x1c\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\x030\x1d'\n\x0c\n\x05\
    \x04\x02\x02\x02\x03\x12\x030*+\n6\n\x04\x04\x02\x02\x03\x12\x033\x02\
    \x13\x1a)\x20Whether\x20the\x20key\x20was\x20explicitly\x20revoked.\n\n\
    \x0c\n\x05\x04\x02\x02\x03\x05\x12\x033\x02\x06\n\x0c\n\x05\x04\x02\x02\
    \x03\x01\x12\x033\x07\x0e\n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x033\x11\
    \x12\n\x0c\n\x04\x04\x02\x08\0\x12\x045\x02;\x03\n\x0c\n\x05\x04\x02\x08\
    \0\x01\x12\x035\x08\x10\n?\n\x04\x04\x02\x02\x04\x12\x037\x04?\x1a2\x20T\
    he\x20SDK\x20key\x20details\x20when\x20this\x20key\x20is\x20an\x20SDK\
    \x20key.\n\n\x0c\n\x05\x04\x02\x02\x04\x06\x12\x037\x042\n\x0c\n\x05\x04\
    \x02\x02\x04\x01\x12\x0373:\n\x0c\n\x05\x04\x02\x02\x04\x03\x12\x037=>\n\
    ?\n\x04\x04\x02\x02\x05\x12\x03:\x04?\x1a2\x20The\x20API\x20key\x20detai\
    ls\x20when\x20this\x20key\x20is\x20an\x20API\x20key.\n\n\x0c\n\x05\x04\
    \x02\x02\x05\x06\x12\x03:\x042\n\x0c\n\x05\x04\x02\x02\x05\x01\x12\x03:3\
    :\n\x0c\n\x05\x04\x02\x02\x05\x03\x12\x03:=>\nM\n\x04\x04\x02\x02\x06\
    \x12\x03>\x02\x12\x1a@\x20The\x20name\x20of\x20the\x20key,\x20used\x20fo\
    r\x20(human)\x20identification\x20purposes.\n\n\x0c\n\x05\x04\x02\x02\
    \x06\x05\x12\x03>\x02\x08\n\x0c\n\x05\x04\x02\x02\x06\x01\x12\x03>\t\r\n\
    \x0c\n\x05\x04\x02\x02\x06\x03\x12\x03>\x10\x11\n\t\n\x02\x04\x03\x12\
    \x03A\0\x19\n\n\n\x03\x04\x03\x01\x12\x03A\x08\x16\n\n\n\x02\x04\x04\x12\
    \x04C\0F\x01\n\n\n\x03\x04\x04\x01\x12\x03C\x08\x17\nF\n\x04\x04\x04\x02\
    \0\x12\x03E\x02@\x1a9\x20The\x20API\x20and\x20SDK\x20keys\x20visible\x20\
    to\x20the\x20authenticated\x20user.\n\n\x0c\n\x05\x04\x04\x02\0\x04\x12\
    \x03E\x02\n\n\x0c\n\x05\x04\x04\x02\0\x06\x12\x03E\x0b6\n\x0c\n\x05\x04\
    \x04\x02\0\x01\x12\x03E7;\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03E>?\n\n\n\
    \x02\x04\x05\x12\x04H\0n\x01\n\n\n\x03\x04\x05\x01\x12\x03H\x08\x18\n\
    \x0c\n\x04\x04\x05\x03\0\x12\x04I\x02S\x03\n\x0c\n\x05\x04\x05\x03\0\x01\
    \x12\x03I\n\x17\nJ\n\x06\x04\x05\x03\0\x02\0\x12\x04K\x04N\x07\x1a:\x20T\
    he\x20app/bundle\x20ID\x20regex\x20that\x20the\x20key\x20is\x20associate\
    d\x20with.\n\n\x0e\n\x07\x04\x05\x03\0\x02\0\x05\x12\x03K\x04\n\n\x0e\n\
    \x07\x04\x05\x03\0\x02\0\x01\x12\x03K\x0b\x1a\n\x0e\n\x07\x04\x05\x03\0\
    \x02\0\x03\x12\x03K\x1d\x1e\n\x0f\n\x07\x04\x05\x03\0\x02\0\x08\x12\x04K\
    \x1fN\x06\n\x12\n\n\x04\x05\x03\0\x02\0\x08\xaf\x08\x0e\x12\x04K\x20N\
    \x05\n\x90\x01\n\x06\x04\x05\x03\0\x02\x01\x12\x03R\x04R\x1a\x80\x01\x20\
    An\x20optional\x20postfix\x20for\x20the\x20app\x20ID\x20associated\x20wi\
    th\x20the\x20key.\x20The\x20server\n\x20appends\x20this\x20to\x20the\x20\
    base\x20app\x20ID\x20during\x20authentication.\n\n\x0e\n\x07\x04\x05\x03\
    \0\x02\x01\x04\x12\x03R\x04\x0c\n\x0e\n\x07\x04\x05\x03\0\x02\x01\x05\
    \x12\x03R\r\x13\n\x0e\n\x07\x04\x05\x03\0\x02\x01\x01\x12\x03R\x14\"\n\
    \x0e\n\x07\x04\x05\x03\0\x02\x01\x03\x12\x03R%&\n\x0e\n\x07\x04\x05\x03\
    \0\x02\x01\x08\x12\x03R'Q\n\x11\n\n\x04\x05\x03\0\x02\x01\x08\xaf\x08\
    \x0e\x12\x03R(P\n\x0c\n\x04\x04\x05\x03\x01\x12\x04U\x02^\x03\n\x0c\n\
    \x05\x04\x05\x03\x01\x01\x12\x03U\n\x17\n^\n\x06\x04\x05\x03\x01\x02\0\
    \x12\x04W\x04]\x07\x1aN\x20The\x20permissions\x20that\x20the\x20key\x20s\
    hould\x20have.\x20Must\x20have\x20at\x20least\x20one\x20permission.\n\n\
    \x0e\n\x07\x04\x05\x03\x01\x02\0\x04\x12\x03W\x04\x0c\n\x0e\n\x07\x04\
    \x05\x03\x01\x02\0\x06\x12\x03W\r7\n\x0e\n\x07\x04\x05\x03\x01\x02\0\x01\
    \x12\x03W8C\n\x0e\n\x07\x04\x05\x03\x01\x02\0\x03\x12\x03WFG\n\x0f\n\x07\
    \x04\x05\x03\x01\x02\0\x08\x12\x04WH]\x06\n\x12\n\n\x04\x05\x03\x01\x02\
    \0\x08\xaf\x08\x12\x12\x04WI]\x05\n\x0c\n\x04\x04\x05\x08\0\x12\x04`\x02\
    g\x03\n\x0c\n\x05\x04\x05\x08\0\x01\x12\x03`\x08\x10\n\x0c\n\x05\x04\x05\
    \x08\0\x02\x12\x03a\x04&\n\x0e\n\x07\x04\x05\x08\0\x02\xaf\x08\x12\x03a\
    \x04&\n\"\n\x04\x04\x05\x02\0\x12\x03c\x04O\x1a\x15\x20Creates\x20an\x20\
    SDK\x20key.\n\n\x0c\n\x05\x04\x05\x02\0\x06\x12\x03c\x04B\n\x0c\n\x05\
    \x04\x05\x02\0\x01\x12\x03cCJ\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03cMN\n\
    \"\n\x04\x04\x05\x02\x01\x12\x03f\x04O\x1a\x15\x20Creates\x20an\x20API\
    \x20key.\n\n\x0c\n\x05\x04\x05\x02\x01\x06\x12\x03f\x04B\n\x0c\n\x05\x04\
    \x05\x02\x01\x01\x12\x03fCJ\n\x0c\n\x05\x04\x05\x02\x01\x03\x12\x03fMN\n\
    N\n\x04\x04\x05\x02\x02\x12\x04j\x02m\x05\x1a@\x20The\x20name\x20of\x20t\
    he\x20key,\x20used\x20for\x20(human)\x20identification\x20purposes.\n\n\
    \x0c\n\x05\x04\x05\x02\x02\x05\x12\x03j\x02\x08\n\x0c\n\x05\x04\x05\x02\
    \x02\x01\x12\x03j\t\r\n\x0c\n\x05\x04\x05\x02\x02\x03\x12\x03j\x10\x11\n\
    \r\n\x05\x04\x05\x02\x02\x08\x12\x04j\x12m\x04\n\x10\n\x08\x04\x05\x02\
    \x02\x08\xaf\x08\x0e\x12\x04j\x13m\x03\n\n\n\x02\x04\x06\x12\x04p\0s\x01\
    \n\n\n\x03\x04\x06\x01\x12\x03p\x08\x19\n\x1f\n\x04\x04\x06\x02\0\x12\
    \x03r\x026\x1a\x12\x20The\x20created\x20key.\n\n\x0c\n\x05\x04\x06\x02\0\
    \x06\x12\x03r\x02-\n\x0c\n\x05\x04\x06\x02\0\x01\x12\x03r.1\n\x0c\n\x05\
    \x04\x06\x02\0\x03\x12\x03r45\n\n\n\x02\x04\x07\x12\x04u\0x\x01\n\n\n\
    \x03\x04\x07\x01\x12\x03u\x08\x18\n+\n\x04\x04\x07\x02\0\x12\x03w\x02\
    \x10\x1a\x1e\x20The\x20ID\x20of\x20the\x20key\x20to\x20revoke.\n\n\x0c\n\
    \x05\x04\x07\x02\0\x05\x12\x03w\x02\x08\n\x0c\n\x05\x04\x07\x02\0\x01\
    \x12\x03w\t\x0b\n\x0c\n\x05\x04\x07\x02\0\x03\x12\x03w\x0e\x0f\n\t\n\x02\
    \x04\x08\x12\x03z\0\x1c\n\n\n\x03\x04\x08\x01\x12\x03z\x08\x19b\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::permission::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::validate::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(11);
            messages.push(SdkKeyResponse::generated_message_descriptor_data());
            messages.push(ApiKeyResponse::generated_message_descriptor_data());
            messages.push(KeyResponse::generated_message_descriptor_data());
            messages.push(GetKeysRequest::generated_message_descriptor_data());
            messages.push(GetKeysResponse::generated_message_descriptor_data());
            messages.push(CreateKeyRequest::generated_message_descriptor_data());
            messages.push(CreateKeyResponse::generated_message_descriptor_data());
            messages.push(RevokeKeyRequest::generated_message_descriptor_data());
            messages.push(RevokeKeyResponse::generated_message_descriptor_data());
            messages.push(create_key_request::SdkKeyRequest::generated_message_descriptor_data());
            messages.push(create_key_request::ApiKeyRequest::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
