[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-network-quality"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace           = true
async-trait.workspace      = true
bd-workspace-hack.workspace = true
parking_lot.workspace      = true
tokio.workspace            = true

[dev-dependencies]
tokio-test.workspace = true
