[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-session"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace       = true
bd-client-common.path  = "../bd-client-common"
bd-key-value.path      = "../bd-key-value"
bd-log.path            = "../bd-log"
bd-time.path           = "../bd-time"
log.workspace          = true
parking_lot.workspace  = true
serde.workspace        = true
serde_yaml.workspace   = true
thread_local.workspace = true
time.workspace         = true
tokio.workspace        = true
uuid.workspace         = true

[dev-dependencies]
bd-test-helpers             = { path = "../bd-test-helpers", default-features = false }
ctor.workspace              = true
pretty_assertions.workspace = true
