// proto - bitdrift's client/server API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 35.0
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `bitdrift/public/unary/timeline/v1/api.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n+bitdrift/public/unary/timeline/v1/api.proto\x12!bitdrift.public.unary\
    .timeline.v1\x1a1bitdrift/public/unary/timeline/v1/hydration.proto\x1a,b\
    itdrift/public/unary/timeline/v1/info.proto\x1a,bitdrift/public/unary/ti\
    meline/v1/logs.proto\x1a.bitdrift/public/unary/timeline/v1/search.proto\
    \x1a-bitdrift/public/unary/timeline/v1/spans.proto2\xe5\x06\n\x0fTimelin\
    eService\x12\x85\x01\n\x0eGetSessionLogs\x128.bitdrift.public.unary.time\
    line.v1.GetSessionLogsRequest\x1a9.bitdrift.public.unary.timeline.v1.Get\
    SessionLogsResponse\x12\x85\x01\n\x0eGetSessionInfo\x128.bitdrift.public\
    .unary.timeline.v1.GetSessionInfoRequest\x1a9.bitdrift.public.unary.time\
    line.v1.GetSessionInfoResponse\x12\x85\x01\n\x0eHydrateSession\x128.bitd\
    rift.public.unary.timeline.v1.HydrateSessionRequest\x1a9.bitdrift.public\
    .unary.timeline.v1.HydrateSessionResponse\x12\x91\x01\n\x12GetHydrationS\
    tatus\x12<.bitdrift.public.unary.timeline.v1.GetHydrationStatusRequest\
    \x1a=.bitdrift.public.unary.timeline.v1.GetHydrationStatusResponse\x12\
    \x88\x01\n\x0bSearchSpans\x12;.bitdrift.public.unary.timeline.v1.Session\
    SearchSpanRequest\x1a<.bitdrift.public.unary.timeline.v1.SessionSearchSp\
    anResponse\x12\x9a\x01\n\x15AdvancedSearchSession\x12?.bitdrift.public.u\
    nary.timeline.v1.SessionAdvancedSearchRequest\x1a@.bitdrift.public.unary\
    .timeline.v1.SessionAdvancedSearchResponseJ\x90\x0e\n\x06\x12\x04\x06\04\
    \x01\n\xb8\x02\n\x01\x0c\x12\x03\x06\0\x12\x1a\xad\x02\x20api\x20-\x20bi\
    tdrift's\x20client/server\x20API\x20definitions\n\x20Copyright\x20Bitdri\
    ft,\x20Inc.\x20All\x20rights\x20reserved.\n\n\x20Use\x20of\x20this\x20so\
    urce\x20code\x20and\x20APIs\x20are\x20governed\x20by\x20a\x20source\x20a\
    vailable\x20license\x20that\x20can\x20be\x20found\x20in\n\x20the\x20LICE\
    NSE\x20file\x20or\x20at:\n\x20https://polyformproject.org/wp-content/upl\
    oads/2020/06/PolyForm-Shield-1.0.0.txt\n\n\x08\n\x01\x02\x12\x03\x08\0*\
    \n\t\n\x02\x03\0\x12\x03\n\0;\n\t\n\x02\x03\x01\x12\x03\x0b\06\n\t\n\x02\
    \x03\x02\x12\x03\x0c\06\n\t\n\x02\x03\x03\x12\x03\r\08\n\t\n\x02\x03\x04\
    \x12\x03\x0e\07\nf\n\x02\x06\0\x12\x04\x11\04\x01\x1aZ\x20Provides\x20ac\
    cess\x20to\x20session\x20timeline\x20data,\x20including\x20logs,\x20meta\
    data,\x20and\x20hydration\x20state.\n\n\n\n\x03\x06\0\x01\x12\x03\x11\
    \x08\x17\n\x7f\n\x04\x06\0\x02\0\x12\x04\x15\x02\x93\x01\x1aq\x20Retriev\
    es\x20the\x20logs\x20for\x20a\x20session.\n\n\x20Returns\x20the\x20gRPC\
    \x20NOT_FOUND\x20status\x20if\x20the\x20session\x20has\x20not\x20been\
    \x20hydrated\x20yet.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x15\x06\x14\n\
    \x0c\n\x05\x06\0\x02\0\x02\x12\x03\x15\x15M\n\r\n\x05\x06\0\x02\0\x03\
    \x12\x04\x15X\x91\x01\n\x8f\x01\n\x04\x06\0\x02\x01\x12\x04\x1a\x02\x93\
    \x01\x1a\x80\x01\x20Retrieves\x20metadata\x20and\x20attributes\x20for\
    \x20a\x20session.\n\n\x20Returns\x20the\x20gRPC\x20NOT_FOUND\x20status\
    \x20if\x20the\x20session\x20has\x20not\x20been\x20hydrated\x20yet.\n\n\
    \x0c\n\x05\x06\0\x02\x01\x01\x12\x03\x1a\x06\x14\n\x0c\n\x05\x06\0\x02\
    \x01\x02\x12\x03\x1a\x15M\n\r\n\x05\x06\0\x02\x01\x03\x12\x04\x1aX\x91\
    \x01\n\xa9\x01\n\x04\x06\0\x02\x02\x12\x04\x20\x02\x93\x01\x1a\x9a\x01\
    \x20Triggers\x20hydration\x20of\x20a\x20session.\n\n\x20Hydration\x20pre\
    pares\x20session\x20data\x20for\x20querying.\x20Can\x20also\x20be\x20use\
    d\x20to\x20force\n\x20re-hydration\x20of\x20an\x20already\x20hydrated\
    \x20session.\n\n\x0c\n\x05\x06\0\x02\x02\x01\x12\x03\x20\x06\x14\n\x0c\n\
    \x05\x06\0\x02\x02\x02\x12\x03\x20\x15M\n\r\n\x05\x06\0\x02\x02\x03\x12\
    \x04\x20X\x91\x01\n\x9b\x01\n\x04\x06\0\x02\x03\x12\x04&\x02\x9f\x01\x1a\
    \x8c\x01\x20Retrieves\x20the\x20hydration\x20status\x20of\x20a\x20sessio\
    n.\n\n\x20Returns\x20the\x20gRPC\x20NOT_FOUND\x20status\x20if\x20hydrati\
    on\x20has\x20not\x20been\x20triggered\x20for\x20the\n\x20session\x20yet.\
    \n\n\x0c\n\x05\x06\0\x02\x03\x01\x12\x03&\x06\x18\n\x0c\n\x05\x06\0\x02\
    \x03\x02\x12\x03&\x19U\n\r\n\x05\x06\0\x02\x03\x03\x12\x04&`\x9d\x01\n\
    \x9b\x01\n\x04\x06\0\x02\x04\x12\x04+\x02\x96\x01\x1a\x8c\x01\x20Searche\
    s\x20spans\x20within\x20a\x20session.\n\n\x20Supports\x20filtering\x20by\
    \x20span\x20name\x20or\x20span\x20ID\x20and\x20can\x20limit\x20returned\
    \x20child\x20depth\x20and\x20top-level\x20pagination.\n\n\x0c\n\x05\x06\
    \0\x02\x04\x01\x12\x03+\x06\x11\n\x0c\n\x05\x06\0\x02\x04\x02\x12\x03+\
    \x12M\n\r\n\x05\x06\0\x02\x04\x03\x12\x04+X\x94\x01\n\x98\x02\n\x04\x06\
    \0\x02\x05\x12\x043\x02\xa8\x01\x1a\x89\x02\x20Performs\x20an\x20advance\
    d\x20search\x20across\x20logs\x20in\x20a\x20session.\n\n\x20Supports\x20\
    filtering\x20by\x20field\x20values,\x20log\x20types,\x20log\x20levels,\
    \x20and\x20full-text\n\x20content\x20using\x20a\x20flexible\x20query\x20\
    model\x20with\x20AND/OR\x20logic.\n\n\x20Returns\x20the\x20gRPC\x20NOT_F\
    OUND\x20status\x20if\x20the\x20session\x20has\x20not\x20been\x20hydrated\
    \x20yet.\n\n\x0c\n\x05\x06\0\x02\x05\x01\x12\x033\x06\x1b\n\x0c\n\x05\
    \x06\0\x02\x05\x02\x12\x033\x1c[\n\r\n\x05\x06\0\x02\x05\x03\x12\x043f\
    \xa6\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::hydration::file_descriptor().clone());
            deps.push(super::info::file_descriptor().clone());
            deps.push(super::logs::file_descriptor().clone());
            deps.push(super::search::file_descriptor().clone());
            deps.push(super::spans::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
