load("//tools/lint:linters.bzl", "rust_binary", "rust_library")
load("//tools/rust:feature_variants.bzl", "all_crate_deps_with_overrides")

package(default_visibility = ["//visibility:public"])

LOGGER_CLI_DEPS = all_crate_deps_with_overrides(
    normal = True,
    dependency_overrides = {
        "//shared-core/bd-client-stats": "//shared-core/bd-client-stats:bd-client-stats-logger-cli",
    },
)

rust_library(
    name = "logger-cli",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "logger_cli",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = LOGGER_CLI_DEPS,
)

rust_binary(
    name = "logger-cli-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["default"],
    crate_name = "logger_cli",
    crate_root = "src/main.rs",
    edition = "2024",
    deps = LOGGER_CLI_DEPS + [":logger-cli"],
)

rust_binary(
    name = "logger-mcp",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["default"],
    crate_name = "logger_mcp",
    crate_root = "src/bin/mcp.rs",
    edition = "2024",
    deps = LOGGER_CLI_DEPS + [":logger-cli"],
)
